"""
Tratamento padrão-ouro parasitário — fontes oficiais brasileiras.
Fontes: PCDT-MS, SVS/GVS 5ª ed. 2022, SBMT, SBI, ANVISA.

Formato: lista de tuplas
(pat_substr, antip_principal, combinacao, regime_resumido, duracao_resumida,
 justificativa, alt_alergia, alt_resistencia, obs_especiais,
 grau_recomendacao, nivel_evidencia, fonte_sigla, ano_diretriz)
"""

TRATAMENTO_PADRAO_OURO_PARASITARIO = [
    # ── Malária ──────────────────────────────────────────────────────────────
    ("Malária por Plasmodium falciparum",
     "Artemeter/Lumefantrina",
     "Dose única de 6 comprimidos 480 mg lumefantrina nos tempos 0h, 8h, 24h, 36h, 48h, 60h",
     "6 comprimidos 80/480 mg nos tempos: 0h, 8h, 24h, 36h, 48h, 60h — total 3 dias — com alimento gorduroso",
     "3 dias",
     "Única combinação base-artemisinina registrada no MS/FUNASA para P. falciparum não complicado no Brasil (PCDT-MALARIA 2022); eficácia > 95%; segura em crianças e adultos; menor número de comprimidos que quinino",
     "Quinino + clindamicina 7 dias (gestação 1º trimestre ou alergia)",
     "Artesunato IV se malária grave; avaliar falha em 72h e troca de esquema",
     "Malária grave: Artesunato IV 2,4 mg/kg (0h, 12h, 24h, depois 1x/dia) até poder usar oral; completar com artemeter/lumefantrina oral",
     "A", "I", "PCDT-MALARIA", 2022),

    ("Malária por Plasmodium vivax",
     "Cloroquina",
     "Cloroquina 25 mg base/kg em 3 dias + Primaquina 0,5 mg/kg/dia por 7 dias",
     "Cloroquina: D1 10 mg/kg + D2 10 mg/kg + D3 5 mg/kg | Primaquina: 0,5 mg/kg/dia por 7 dias (após G6PD)",
     "3 dias (cloroquina) + 7 dias (primaquina)",
     "Esquema padrão do PCDT-MALARIA 2022 para P. vivax; cloroquina elimina formas eritrocitárias; primaquina é obrigatória para radical cure (elimina hipnozoítas e previne recidivas); triagem G6PD antes da primaquina",
     "Artemisininas (formas eritrocitárias) se intolerância à cloroquina",
     "Artemeter/lumefantrina se suspeita de resistência à cloroquina (caso importado de Papua-Nova Guiné)",
     "G6PD deficiência grave: cloroquina sem primaquina (monitorar para recidivas); G6PD intermediário: primaquina 0,25 mg/kg/dia por 14 dias; gestantes: cloroquina apenas (primaquina contraindicada)",
     "A", "I", "PCDT-MALARIA", 2022),

    ("Malária por Plasmodium malariae",
     "Cloroquina",
     "Cloroquina 25 mg base/kg em 3 dias (sem primaquina)",
     "Cloroquina: D1 10 mg/kg + D2 10 mg/kg + D3 5 mg/kg oral",
     "3 dias",
     "P. malariae: sem hipnozoítas hepáticos, portanto primaquina não é necessária; cloroquina permanece eficaz para P. malariae globalmente",
     "Artemeter/lumefantrina se intolerância à cloroquina",
     "Sem alternativa de primeira linha documentada",
     "Síndrome nefrótica quartã em crianças com infecção crônica: tratar com cloroquina; nefropatia pode persistir mesmo após cura parasitológica",
     "A", "II", "PCDT-MALARIA", 2022),

    # ── Leishmanioses ─────────────────────────────────────────────────────────
    ("Leishmaniose Tegumentar Americana",
     "Antimoniato de N-metilglucamina",
     "Antimoniato 20 mg SbV/kg/dia IM por 20 dias (cutânea) ou 30 dias (mucosa)",
     "20 mg SbV/kg/dia IM 1x/dia — máx 3 ampolas/dia — 20 dias LTA cutânea localizada; 30 dias LTA mucosa",
     "20-30 dias",
     "Padrão-ouro LTA no Brasil segundo PCDT-LEISH-TEG 2022; maior experiência clínica acumulada; custo-efetividade; disponível SUS; monitoramento cardíaco, hepático e renal obrigatório durante tratamento",
     "Anfotericina B lipossomal (gestantes, IRC, cardiopatias — contraindicações ao antimoniato)",
     "Miltefosina 28 dias ou anfotericina B lipossomal em falha",
     "Cura clínica definida como cicatrização completa da úlcera; controle em 90 dias (cutânea) e 6 meses (mucosa); não usar em gestação — Anf. B lipo é a alternativa",
     "A", "I", "PCDT-LEISH-TEG", 2022),

    ("Leishmaniose Visceral (Calazar)",
     "Anfotericina B lipossomal",
     "Anfotericina B lipossomal 3-5 mg/kg/dia EV por 7 dias (dose total 21-40 mg/kg)",
     "3-5 mg/kg/dia EV em 30-60 min | 7 dias consecutivos | internação obrigatória",
     "7 dias",
     "1ª linha LV em grupos especiais (gestantes, < 1 ano, > 50 anos, IRC, cardiopatias, insucesso de antimoniato); eficácia > 97%; menor toxicidade renal que antimoniato; menor tempo de hospitalização; PCDT-LEISH-VIS 2022",
     "Antimoniato de N-metilglucamina (adultos imunocompetentes sem contraindicações)",
     "Miltefosina oral se nova falha (pacientes que não toleram nenhuma das opções parenterais)",
     "Critério de cura LV: ausência de febre + redução do baço + melhora clínica ao fim do tratamento; controle parasitológico não obrigatório se resposta clínica satisfatória; profilaxia secundária em HIV/AIDS (Anf. B lipo mensal)",
     "A", "I", "PCDT-LEISH-VIS", 2022),

    # ── Doença de Chagas ─────────────────────────────────────────────────────
    ("Doença de Chagas Aguda",
     "Benznidazol",
     "Benznidazol 5-7 mg/kg/dia VO em 2 doses por 60 dias",
     "5-7 mg/kg/dia VO 12/12h | comprimidos de 100 mg | 60 dias",
     "60 dias",
     "1ª linha fase aguda: cura parasitológica > 80%; iniciar o mais precocemente possível — quanto mais precoce, maior a taxa de cura; disponível SUS; PCDT-CHAGAS 2022",
     "Nifurtimox 8-10 mg/kg/dia adultos por 60-90 dias (intolerância ao benznidazol)",
     "Nifurtimox em falha documentada ao benznidazol",
     "Efeitos adversos frequentes (dermatose 30%, neuropatia periférica 10-20%, leucopenia); monitorar hemograma a cada 2 semanas; suspender se leucócitos < 2.500; crianças: 5-10 mg/kg/dia por 60 dias — melhor tolerância",
     "A", "I", "PCDT-CHAGAS", 2022),

    ("Doença de Chagas Crônica",
     "Benznidazol",
     "Benznidazol 5 mg/kg/dia VO em 2 doses por 60 dias",
     "5 mg/kg/dia VO 12/12h | comprimidos de 100 mg | 60 dias",
     "60 dias",
     "Fase crônica indeterminada em adultos jovens (< 50 anos): benefício comprovado em estudos; cardiopatia leve (FEVE > 40%): considerar; ensaio BENEFIT (2015): sem redução de desfechos cardíacos em fase avançada; PCDT-CHAGAS 2022",
     "Nifurtimox em intolerância grave ao benznidazol",
     "Sem alternativa eficaz documentada para casos de falha dupla",
     "Cardiomiopatia chagásica avançada (FEVE < 40%): benefício do antiparasitário incerto; tratar manifestações cardíacas (amiodarona, CDI, transplante) e digestivas (cirurgia para megaesôfago/megacólon) independentemente; não tratar gestantes (benznidazol teratogênico — categoria C)",
     "B", "II", "PCDT-CHAGAS", 2022),

    # ── Toxoplasmose ─────────────────────────────────────────────────────────
    ("Toxoplasmose em Imunocomprometidos",
     "Sulfadiazina",
     "Sulfadiazina 1,5 g 6/6h + Pirimetamina 200 mg ataque depois 75 mg/dia + Ácido folínico 25 mg/dia",
     "Sulfadiazina 1,5 g 6/6h VO | Pirimetamina 200 mg D1 depois 75 mg/dia | Ácido folínico 25 mg/dia | mínimo 6 semanas",
     "6 semanas (fase aguda) + profilaxia 2ª dose indefinida",
     "Esquema padrão-ouro encefalite toxoplásmica HIV/AIDS pelo PCDT-HIV/AIDS 2022; melhora clínica esperada em 7-14 dias; ausência de melhora em 2 semanas sugere diagnóstico alternativo (linfoma primário SNC, TB cerebral)",
     "Clindamicina 600 mg 6/6h + pirimetamina + ácido folínico (alergia a sulfonamidas)",
     "Clindamicina + pirimetamina se falha à sulfadiazina",
     "Profilaxia 2ª: sulfadiazina 1 g 12/12h + pirimetamina 25 mg/dia + ácido folínico — até CD4 > 200 células/mm³ por ≥ 6 meses com TARV; iniciar TARV 2-3 semanas após início do tratamento antiparasitário",
     "A", "I", "PCDT-TOXO", 2022),

    ("Toxoplasmose Congênita",
     "Sulfadiazina",
     "Sulfadiazina 100 mg/kg/dia em 2 doses + Pirimetamina 1 mg/kg/dia + Ácido folínico 10 mg/dia por 12 meses",
     "Sulfadiazina 100 mg/kg/dia 12/12h VO | Pirimetamina 1 mg/kg/dia VO | Ácido folínico 10 mg/dia VO | 12 meses",
     "12 meses",
     "Tratamento prolongado (12 meses) reduz sequelas neurológicas e oculares em neonatos com toxoplasmose congênita confirmada; PCDT-TOXO MS 2022 e consenso SBP/SBI",
     "Clindamicina em alergia a sulfonamidas neonatais (risco de kernicterus — substituir em RN < 1 mês)",
     "Espiramicina (eficácia inferior — usar apenas se alternativas indisponíveis)",
     "Monitorar retina a cada 3 meses no 1º ano; hemograma mensal; controle neurológico e audiológico; informar pais sobre sinais de coriorretinite recorrente",
     "A", "II", "PCDT-TOXO", 2022),

    ("Toxoplasmose em Imunocompetentes",
     "Sulfadiazina",
     "Sulfadiazina 1 g 6/6h + Pirimetamina 25 mg/dia + Ácido folínico 10 mg/dia por 4-6 semanas",
     "Sulfadiazina 1 g 6/6h VO | Pirimetamina 25 mg/dia | Ácido folínico 10 mg/dia | 4-6 semanas (apenas se forma grave ou ocular ameaçando mácula)",
     "4-6 semanas",
     "Toxoplasmose em imunocompetente geralmente autolimitada — não trata rotineiramente; indicação: lesão ocular maior que 1,5 diâmetro de disco ameaçando mácula ou nervo óptico; encefalopatia; gestação (espiramicina para prevenir transmissão vertical)",
     "Clindamicina + pirimetamina em alergia a sulfonamidas",
     "Atovaquona em casos especiais (off-label)",
     "Gestação: espiramicina 1 g 8/8h até o parto para reduzir transmissão vertical (não trata feto infectado); se infecção fetal confirmada (PCR líquido amniótico): sulfadiazina + pirimetamina + ácido folínico após 14ª semana",
     "B", "II", "SBI-PARASIT", 2022),

    # ── Amebíase ─────────────────────────────────────────────────────────────
    ("Amebíase Intestinal",
     "Metronidazol",
     "Metronidazol 750 mg 8/8h VO por 5-10 dias + paramomicina 25-35 mg/kg/dia 8/8h por 7 dias",
     "Metronidazol 750 mg 8/8h por 5-10 dias | Seguir com paramomicina 25-35 mg/kg/dia 8/8h por 7 dias (amebicida luminal)",
     "12-17 dias",
     "Metronidazol elimina trofozoítas teciduais mas não os cistos luminais; paramomicina (amebicida luminal) é obrigatória para eliminar cistos e prevenir recidivas e transmissão; SVS/GVS 5ª ed. 2022",
     "Tinidazol 2 g/dia por 3-5 dias (alternativa ao metronidazol com melhor tolerância)",
     "Secnidazol 2 g dose única em casos leves",
     "Abstinência de álcool durante metronidazol; evitar diagnóstico de E. histolytica sem confirmação (E. dispar não patogênica e não requer tratamento)",
     "A", "I", "SVS-PARASIT", 2022),

    ("Abscesso Hepático Amebiano",
     "Metronidazol",
     "Metronidazol 750 mg 8/8h VO ou IV por 10 dias + paramomicina luminal",
     "Metronidazol 750 mg 8/8h VO/IV por 10 dias | Seguir com paramomicina 25-35 mg/kg/dia 8/8h 7 dias",
     "17 dias",
     "Resposta clínica rápida ao metronidazol em 24-72h é esperada e confirma diagnóstico; drenagem percutânea apenas para abscessos > 10 cm, risco iminente de ruptura ou falha clínica em 72h; padrão SVS/GVS 2022",
     "Tinidazol 2 g/dia por 5 dias",
     "Drenagem percutânea se falha terapêutica",
     "Resolução da imagem ultrassonográfica leva meses após cura clínica — não usar imagem como critério de cura; manter seguimento mensal por 6 meses",
     "A", "I", "SVS-PARASIT", 2022),

    # ── Giardíase / Tricomoníase ──────────────────────────────────────────────
    ("Giardíase",
     "Tinidazol",
     "Tinidazol 2 g dose única VO com alimento",
     "2 g dose única com refeição | crianças > 3 anos: 50 mg/kg dose única (máx 2 g)",
     "1 dia",
     "Superior ao metronidazol em dose única: maior taxa de cura (90% vs 85%), melhor tolerância GI, maior adesão; SVS/GVS 5ª ed. 2022; metronidazol permanece 1ª linha do SUS por disponibilidade",
     "Metronidazol 250-500 mg 8/8h por 5-7 dias (1ª linha SUS)",
     "Nitazoxanida 500 mg 12/12h por 3-7 dias em falha de nitroimidazóis",
     "Investigar reinfecção familiar; tratar todos os membros da família sintomáticos; fervura ou filtração de água (Giardia resistente ao cloro)",
     "A", "I", "SVS-PARASIT", 2022),

    ("Tricomoníase",
     "Metronidazol",
     "Metronidazol 2 g dose única VO",
     "2 g dose única VO | tratar parceiro/parceira simultaneamente",
     "1 dia",
     "Dose única favorece adesão e garante tratamento simultâneo do parceiro; eficácia 88-92%; PCDT IST MS 2022; abstinência/preservativo até 7 dias após tratamento",
     "Tinidazol 2 g dose única (maior eficácia e tolerância — preferida nas recorrências)",
     "Tinidazol 2 g/dia por 7 dias em falha do metronidazol",
     "Resistência crescente ao metronidazol documentada; em falha após 2 ciclos: tinidazol 2 g/dia por 7 dias; rastreio de outras ISTs concomitantes (HIV, sífilis, clamídia, gonorreia)",
     "A", "I", "SVS-PARASIT", 2022),

    # ── Criptosporidiose ──────────────────────────────────────────────────────
    ("Criptosporidiose",
     "Nitazoxanida",
     "Nitazoxanida 500 mg 12/12h VO por 3 dias (imunocompetentes)",
     "500 mg 12/12h por 3 dias | crianças 1-3 anos: 100 mg 12/12h; 4-11 anos: 200 mg 12/12h",
     "3-7 dias",
     "Única droga com aprovação específica para criptosporidiose; eficácia moderada em imunocompetentes (melhora em 80%); em HIV/AIDS, a reconstituição imune com TARV é mais eficaz que qualquer antiparasitário",
     "Hidratação oral/IV intensiva (tratamento de suporte essencial)",
     "Nenhuma alternativa com eficácia comprovada em imunossuprimidos",
     "HIV/AIDS: TARV é o pilar do tratamento — sem reconstituição imune, criptosporidiose não se resolve; nitazoxanida pode ser adjuvante; em transplantados: reduzir imunossupressão se possível",
     "B", "II", "SBI-PARASIT", 2022),

    # ── Helmintoses Intestinais ───────────────────────────────────────────────
    ("Ascaridíase",
     "Albendazol",
     "Albendazol 400 mg dose única VO",
     "400 mg dose única | crianças 1-2 anos: 200 mg dose única",
     "1 dia",
     "Altamente eficaz (> 95%), bem tolerado, baixo custo, disponível no SUS; padrão-ouro SVS/GVS 5ª ed. 2022; dose única facilita campanhas de quimioprofilaxia em massa",
     "Mebendazol 500 mg dose única",
     "Pirantel pamoato 11 mg/kg dose única (gestantes > 1º trimestre)",
     "Obstrução intestinal: cirurgia de urgência ou, em casos selecionados, óleo mineral + piperazina para relaxar vermes; obstrução biliar: endoscopia + albendazol",
     "A", "I", "SVS-PARASIT", 2022),

    ("Ancilostomíase / Necatoríase (Hookworm)",
     "Albendazol",
     "Albendazol 400 mg/dia VO por 3 dias",
     "400 mg 1x/dia por 3 dias | infecções leves: dose única",
     "3 dias",
     "Eficácia 75-88% para Necator americanus com 3 dias (superior a dose única); associar ferro elementar 60 mg/dia por 3-6 meses para anemia ferropriva; SVS/GVS 5ª ed. 2022",
     "Mebendazol 100 mg 12/12h por 3 dias",
     "Pirantel pamoato 11 mg/kg/dia por 3 dias (gestantes)",
     "Monitorar hemoglobina após tratamento; prevalências altas em comunidades — tratamento periódico a cada 6-12 meses + melhorias de saneamento",
     "A", "I", "SVS-PARASIT", 2022),

    ("Tricuríase",
     "Mebendazol",
     "Mebendazol 100 mg 12/12h VO por 3 dias",
     "100 mg 12/12h por 3 dias",
     "3 dias",
     "Ligeiramente superior ao albendazol para T. trichiura; eficácia moderada (60-70%); casos graves com prolapso retal: múltiplos ciclos; SVS/GVS 5ª ed. 2022",
     "Albendazol 400 mg/dia por 3 dias",
     "Ivermectina + albendazol (combinação aumenta eficácia para ~80%)",
     "Prolapso retal em criança: reduzir manualmente + vários ciclos de mebendazol; investigar coinfecções com Ascaris e ancilostomídeos",
     "A", "I", "SVS-PARASIT", 2022),

    ("Estrongiloidíase",
     "Ivermectina",
     "Ivermectina 200 mcg/kg/dia VO por 2 dias consecutivos",
     "200 mcg/kg/dia VO por 2 dias | em jejum (30 min antes das refeições)",
     "2 dias",
     "1ª linha: superiora ao albendazol em estudos randomizados (cura 95% vs 70%); autoinfecção crônica — tratar todos os pacientes imunossuprimidos mesmo assintomáticos; SVS/GVS 5ª ed. 2022",
     "Albendazol 400 mg/dia por 5-7 dias",
     "Combinação ivermectina + albendazol em hiperinfecção",
     "Rastrear S. stercoralis antes de iniciar corticoterapia ou imunossupressão — tratar se positivo; hiperinfecção: ivermectina + albendazol + antibioticoterapia para sepse gram-negativa; TARV para HIV se coinfectado",
     "A", "I", "SVS-PARASIT", 2022),

    ("Estrongiloidíase com Síndrome de Hiperinfecção",
     "Ivermectina",
     "Ivermectina 200 mcg/kg/dia + Albendazol 400 mg 12/12h — manter até negativação de 2 parasitológicos consecutivos",
     "Ivermectina 200 mcg/kg/dia + Albendazol 400 mg 12/12h | Duração: até negativação de fezes (geralmente 5-14 dias) | + antibióticos para sepse gram-negativa",
     "5-14 dias ou mais",
     "Síndrome de hiperinfecção tem mortalidade > 80% sem tratamento; combinação de dois antiparasitários pela alta carga de larvas; tratar simultaneamente a sepse bacteriana; UTI na maioria dos casos; SVS/GVS 5ª ed. 2022",
     "Ivermectina SC (via não aprovada mas usada em pacientes sem absorção oral)",
     "Nenhuma alternativa validada — manter combinação e suporte intensivo",
     "UTI frequentemente necessária; reduzir imunossupressão quando possível; reconstituição imune em HIV; identificar e tratar a condição imunossupressora de base",
     "B", "III", "SVS-PARASIT", 2022),

    ("Enterobíase (Oxiuríase)",
     "Albendazol",
     "Albendazol 400 mg dose única — repetir em 14 dias — tratar toda a família",
     "400 mg dose única VO | Repetir dose em 14 dias para eliminar ovos ingeridos antes do 1º tratamento | Tratar TODOS os contactantes domiciliares simultaneamente",
     "1 dia (x2 com intervalo de 14 dias)",
     "Altamente eficaz (> 95%); tratar toda a família simultaneamente é obrigatório para evitar reinfecção; lavar roupas de cama e toalhas em água quente; cortar unhas; banho matinal; SVS/GVS 5ª ed. 2022",
     "Mebendazol 100 mg dose única (repetir em 14 dias)",
     "Pirantel pamoato 11 mg/kg dose única em gestantes",
     "Pente fino de lêndeas não se aplica à enterobíase; diagnóstico pela fita-adesiva anal (Scotch test) realizado pela manhã antes do banho; verificar reinfeção após 4 semanas; creches: tratar todas as crianças e funcionários",
     "A", "I", "SVS-PARASIT", 2022),

    ("Teníase",
     "Praziquantel",
     "Praziquantel 5-10 mg/kg dose única VO — após TC de crânio para excluir NCC",
     "5-10 mg/kg dose única | T. solium: TC crânio obrigatória antes; T. saginata: TC não obrigatória",
     "1 dia",
     "Alta eficácia (95-98%); dose única; disponível SUS; para T. solium é obrigatória TC prévia para excluir NCC — praziquantel pode desencadear crise epiléptica em NCC não diagnosticada; SVS/GVS 5ª ed. 2022",
     "Niclosamida 2 g dose única (não absorvida — preferida se TC indisponível e houver suspeita de NCC)",
     "Albendazol 400 mg/dia por 3 dias",
     "Confirmar expulsão da escólex nas fezes após tratamento; investigar contatos domiciliares; notificar vigilância epidemiológica — controle de cisticercose",
     "A", "I", "SVS-PARASIT", 2022),

    # ── Neurocisticercose ─────────────────────────────────────────────────────
    ("Neurocisticercose",
     "Albendazol",
     "Albendazol 15 mg/kg/dia em 2 doses (máx 400 mg 12/12h) + Dexametasona 0,1 mg/kg/dia — 8-30 dias",
     "Albendazol 15 mg/kg/dia VO 12/12h | Dexametasona 0,1-0,15 mg/kg/dia (iniciar 2-3 dias antes do albendazol) | 8-30 dias conforme forma clínica",
     "8-30 dias",
     "1ª linha NCC parenquimatosa viável segundo PCDT-NCC MS 2022; dexametasona obrigatória para prevenir edema cerebral pela morte dos cistos; melhora a eficácia e a segurança; anticonvulsivante se histórico de epilepsia",
     "Praziquantel 50 mg/kg/dia por 15 dias + dexametasona (NCC parenquimatosa sem contraindicação ao praziquantel)",
     "Cirurgia (hidrocefalia, cistos gigantes subaracnóideos, NCC espinal)",
     "Formas calcificadas: NÃO tratar com antiparasitário (não beneficia); NCC ventricular: cirurgia endoscópica; NCC subaracnóidea basilar: albendazol por meses + dexametasona + cirurgia de DVP se hidrocefalia; controle TC/RNM a cada 3-6 meses",
     "A", "I", "PCDT-NCC", 2022),

    # ── Esquistossomose ───────────────────────────────────────────────────────
    ("Esquistossomose Mansoni",
     "Praziquantel",
     "Praziquantel 60 mg/kg dose única VO (adultos); 50 mg/kg (crianças < 30 kg)",
     "60 mg/kg dose única VO com alimento | crianças < 30 kg: 50 mg/kg dose única",
     "1 dia",
     "Padrão-ouro para S. mansoni no Brasil segundo PCDT-ESQUIS 2022; dose única com alimento aumenta absorção; taxa de cura 80-90%; retratamento se persistência de ovos em 60-90 dias; vantagem logística em campanhas em massa",
     "Oxamniquina 15 mg/kg dose única (alternativa regional — resistência documentada no NE)",
     "Retratamento com praziquantel em 60 dias se ovos presentes nas fezes",
     "Forma hepatoesplênica: tratar com praziquantel mesmo em fase avançada; varizes de esôfago: EDA + laqueadura/esclerose + propranolol; manter vigilância epidemiológica e controle de Biomphalaria",
     "A", "I", "PCDT-ESQUIS", 2022),

    # ── Filariose ─────────────────────────────────────────────────────────────
    ("Filariose Linfática (Bancroftose)",
     "Dietilcarbamazina (DEC)",
     "DEC 6 mg/kg/dia VO em 3 doses por 12 dias (tratamento individual) OU DEC dose única + Albendazol 400 mg (MDA anual)",
     "Tratamento individual: DEC 6 mg/kg/dia 8/8h por 12 dias | MDA programa eliminação: DEC 6 mg/kg dose única + Albendazol 400 mg anual",
     "12 dias (individual) ou dose única anual (MDA)",
     "DEC é o antifilaria de escolha para W. bancrofti segundo PCDT-FILARIA 2022; microfilaricida com eficácia > 95%; programa MDA com DEC+albendazol+ivermectina está eliminando W. bancrofti em Recife e Maceió",
     "Ivermectina 150 mcg/kg + albendazol 400 mg (MDA em áreas coendêmicas com oncocercose)",
     "Nenhuma alternativa bem validada para o tratamento individual",
     "Reação de Mazzotti (febre, artralgia, prurido) nas primeiras 48h — tratar sintomaticamente; CONTRAINDICADO na oncocercose (risco de cegueira); manejo do linfedema: higiene, massagem linfática, meias compressivas, cirurgia em casos selecionados",
     "A", "I", "PCDT-FILARIA", 2022),

    # ── Toxocaríase ───────────────────────────────────────────────────────────
    ("Toxocaríase (Larva Migrans Visceral)",
     "Albendazol",
     "Albendazol 400 mg 12/12h VO por 5-7 dias (adultos) + corticoide em formas graves",
     "400 mg 12/12h por 5-7 dias | Associar prednisona 1 mg/kg/dia se forma pulmonar grave ou ocular",
     "5-7 dias",
     "Primeira escolha para toxocaríase visceral; penetra tecidos onde as larvas migram; corticoide obrigatório em formas com inflamação significativa (pulmonar, ocular, cerebral); SVS/GVS 5ª ed. 2022",
     "Mebendazol 100-200 mg 12/12h por 5 dias (menor absorção — menos eficaz para formas teciduais)",
     "Nenhuma alternativa bem validada",
     "Toxocaríase ocular: albendazol + corticoide sistêmico + colírio corticoide; oftalmo obrigatório; fotocoagulação a laser em casos selecionados; vermifugação regular de cães e gatos é a principal prevenção",
     "B", "II", "SVS-PARASIT", 2022),

    # ── Larva Migrans Cutânea ─────────────────────────────────────────────────
    ("Larva Migrans Cutânea",
     "Albendazol",
     "Albendazol 400 mg 1x/dia VO por 3 dias",
     "400 mg 1x/dia VO por 3 dias",
     "3 dias",
     "1ª linha: altamente eficaz (> 95%), bem tolerado, conveniente; superior ao tiabendazol tópico para lesões múltiplas ou extensas; prurido melhora em 24-48h; SVS/GVS 5ª ed. 2022",
     "Ivermectina 200 mcg/kg dose única (eficácia similar)",
     "Tiabendazol tópico 10-15% para lesões únicas isoladas",
     "Congelar lesão com CO₂ líquido ou cloreto de etila é ineficaz (larva geralmente está além da margem visível da lesão); não usar remoção cirúrgica; profilaxia: não andar descalço em praias e parques com areia",
     "A", "I", "SVS-PARASIT", 2022),

    # ── Hidatidose ────────────────────────────────────────────────────────────
    ("Hidatidose / Equinococose Cística",
     "Albendazol",
     "Albendazol 400 mg 12/12h VO em ciclos de 28 dias com intervalo de 14 dias + cirurgia ou PAIR",
     "Albendazol 400 mg 12/12h em ciclos 28 dias / 14 dias descanso | Iniciar 2 semanas antes da cirurgia ou PAIR e manter 1 mês após",
     "Ciclos de 28 dias (até 3-6 meses total) + procedimento cirúrgico/PAIR",
     "Albendazol adjuvante à cirurgia ou PAIR (punção-aspiração-injeção-reaspiração): reduz vitalidade do cisto, risco de semeadura e recidiva; cirurgia permanece o padrão-ouro para cistos hepatopulmonares acessíveis; SVS/GVS 5ª ed. 2022",
     "PAIR + albendazol em pacientes sem condições cirúrgicas",
     "Múltiplos ciclos de albendazol sem cirurgia em cistos pequenos e de baixa vitalidade",
     "Ruptura do cisto durante cirurgia: risco de anafilaxia e semeadura peritoneal — pré-medicar e isolar o cisto; diagnóstico tardio é comum; vigilância em áreas pecuárias do RS",
     "B", "II", "SVS-PARASIT", 2022),

    # ── Oncocercose ───────────────────────────────────────────────────────────
    ("Oncocercose",
     "Ivermectina",
     "Ivermectina 150 mcg/kg dose única VO a cada 6 meses (programa de eliminação)",
     "150 mcg/kg dose única VO a cada 6 meses | programa de eliminação PNCO Yanomami",
     "Dose semestral pelo período do programa (até eliminação confirmada)",
     "Microfilaricida altamente eficaz; suprime microfilaremia por 6-12 meses; interrompido o ciclo de transmissão com MDA; programa de eliminação das Américas (OPS) — Brasil próximo da eliminação nas aldeias Yanomami; SVS/GVS 5ª ed. 2022",
     "Nenhuma alternativa aprovada para oncocercose",
     "Doxiciclina + ivermectina (doxiciclina mata Wolbachia simbiótica, reduzindo viabilidade de vermes adultos)",
     "DEC é CONTRAINDICADA na oncocercose (provoca reação de Mazzotti ocular grave com cegueira); nodulectomia de oncocercomas para reduzir carga de vermes adultos; exame ocular anual para monitorar progressão",
     "A", "I", "SVS-PARASIT", 2022),

    # ── Fasciolíase ───────────────────────────────────────────────────────────
    ("Fasciolíase",
     "Triclabendazol",
     "Triclabendazol 10 mg/kg dose única VO com refeição gordurosa (repetir após 12h se infecção intensa)",
     "10 mg/kg dose única com refeição | repetir dose após 12h em infecções intensas ou fase crônica avançada",
     "1-2 doses",
     "Único fármaco eficaz para Fasciola hepatica (praziquantel é inativo nesta espécie); eficácia > 90%; solicitar via acesso especial ANVISA (portaria MS 204/2016); SVS/GVS 5ª ed. 2022",
     "Nenhuma alternativa eficaz disponível no Brasil",
     "Nitazoxanida em casos excepcionais (eficácia inferior e inconsistente)",
     "Praziquantel é ineficaz para Fasciola — nunca usar; na indisponibilidade de triclabendazol: contatar SVS/MS para importação emergencial; fase crônica avançada (obstrução biliar): CPRE + colangite cirúrgica antes do antiparasitário",
     "A", "I", "SVS-PARASIT", 2022),

    # ── Ectoparasitoses ───────────────────────────────────────────────────────
    ("Pediculose do Couro Cabeludo",
     "Permetrina",
     "Permetrina loção 1% — aplicar no couro cabeludo 10 min, enxaguar — repetir em 7-10 dias",
     "Permetrina 1% loção: aplicar no cabelo levemente úmido do couro cabeludo até as pontas | deixar 10 min | enxaguar | repetir em 7-10 dias | pente fino para remoção de lêndeas",
     "2 aplicações (dia 1 e dia 7-10)",
     "Piretroides são o padrão-ouro para pediculose do couro cabeludo; eficácia 90%; segura em gestantes e lactantes a partir de 2 meses; SVS/GVS 5ª ed. 2022",
     "Ivermectina oral 400 mcg/kg dose única repetida em 7-10 dias (resistência à permetrina ou falha tópica)",
     "Dimeticona 4% (solução silicone — mecanismo físico, sem resistência; não registrada no BR)",
     "Resistência à permetrina documentada em algumas regiões; pente fino diário por 2 semanas; lavar roupas e lençóis acima de 60°C; acessórios de cabelo: selar em saco plástico por 72h; tratar contactantes",
     "A", "I", "SVS-PARASIT", 2022),

    ("Escabiose (Sarna)",
     "Permetrina",
     "Permetrina creme 5% — aplicar do pescoço para baixo 8-12h — repetir em 7 dias — tratar todos os contactantes",
     "Permetrina 5%: aplicar em todo o corpo (pescoço para baixo, incluindo interdigitais, genitais e solas) | 8-12h | banho | trocar roupas | repetir dia 7 | tratar TODOS os contactantes no mesmo dia",
     "2 aplicações (dia 1 e dia 7)",
     "Padrão-ouro para escabiose; eficácia 95%; segura em gestantes e crianças > 2 meses; melhor tolerância que benzil benzoato; tratar todos os contactantes simultaneamente é obrigatório para evitar re-infestação; SVS/GVS 5ª ed. 2022",
     "Benzil benzoato 25% por 3-5 dias (1ª linha SUS — maior disponibilidade)",
     "Ivermectina oral 200 mcg/kg dose única repetida em 14 dias (sarna crostosa ou falha tópica)",
     "Sarna crostosa (norueguesa): ivermectina oral 200 mcg/kg/dia por 2 dias + repetir semanal por 2-3 semanas + permetrina tópica diária; lavar roupas e lençóis a > 60°C ou selar em saco plástico por 72h; tratar toda a família e contatos próximos",
     "A", "I", "SVS-PARASIT", 2022),

    ("Miiase",
     "Ivermectina",
     "Ivermectina 200 mcg/kg VO dose única + remoção mecânica das larvas",
     "Ivermectina 200 mcg/kg VO dose única (facilita remoção) | Remoção mecânica manual ou por pressão | Tampão oclusivo (vaselina/parafina) para asfixiar as larvas antes da extração",
     "1 dose + procedimento",
     "Tratamento essencial é mecânico (remoção das larvas); ivermectina oral facilita a extração ao imobilizar as larvas; limpeza e curativo adequado após remoção; SVS/GVS 5ª ed. 2022",
     "Remoção mecânica isolada (sem ivermectina) — eficaz mas mais difícil",
     "Cloreto de etila tópico para imobilizar larvas antes da extração",
     "Nunca comprimir o cisto (pode matar a larva dentro do tecido causando reação inflamatória grave); limpeza cirúrgica de tecido necrótico após remoção; antibioticoterapia apenas se infecção bacteriana secundária; prevenção: cobertura de feridas abertas",
     "B", "III", "SVS-PARASIT", 2022),
]
