# Critérios Diagnósticos — Patologias Virais (IDs 105–143)
# Fontes: MS/PCDT 2023/2024, MS-SVS, SBI 2023, SBH (Hepatologia) 2023,
#          SBPT 2022, SBP, ABN 2022, CFM, ANVISA, OMS — diretrizes mais recentes

CRITERIOS_VIRAIS = [
    # ─── ARBOVIROSES (IDs 105–109) ────────────────────────────────────────────
    {
        "patologia_nome": "Dengue (formas leve, moderada e grave)",
        "criterios": [
            {
                "nome": "NS1 positivo (antígeno viral) nos primeiros 5 dias de febre",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA ou imunocromatografia para NS1; sensibilidade 60–90% nos primeiros 5 dias; negativo não exclui dengue",
                "valor_referencia": "NS1 positivo",
                "fonte": "MS/PCDT Dengue 2024; MS Nota Técnica Arboviroses 2024",
                "ordem": 1,
            },
            {
                "nome": "IgM anti-dengue positivo (a partir do 5º dia de febre)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM; positivo a partir do 5º dia; resultado no mesmo dia com kits rápidos disponíveis no SUS",
                "valor_referencia": "IgM positivo",
                "fonte": "MS/PCDT Dengue 2024",
                "ordem": 2,
            },
            {
                "nome": "RT-PCR para dengue positivo (primeiros 5 dias — fase virêmica)",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Padrão-ouro na fase aguda; sorotipia (DENV 1–4); laboratório de referência (LACEN/FIOCRUZ)",
                "valor_referencia": "RT-PCR positivo",
                "fonte": "MS/PCDT Dengue 2024",
                "ordem": 3,
            },
            {
                "nome": "Febre aguda (2–7 dias) + ≥ 2: cefaleia, dor retro-orbital, mialgia, artralgia, exantema, sangramentos",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Critério clínico MS: febre + ≥ 2 manifestações; dengue grave: extravasamento de plasma, sangramento grave ou disfunção orgânica",
                "valor_referencia": "Febre 2–7 dias + ≥ 2 critérios",
                "fonte": "MS/PCDT Dengue 2024",
                "ordem": 4,
            },
            {
                "nome": "Trombocitopenia (plaquetas < 100.000/mm³) e leucopenia",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Plaquetopenia progressiva na fase crítica (dias 4–6); leucopenia (< 4.000/mm³) é característica",
                "valor_referencia": "Plaquetas < 100.000/mm³",
                "fonte": "MS/PCDT Dengue 2024",
                "ordem": 5,
            },
            {
                "nome": "Hematócrito aumentado ≥ 20% em relação ao baseline (extravasamento plasmático — dengue grave)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Hemoconcentração: Ht ≥ 20% acima do basal indica extravasamento; ascite ou derrame pleural ao USG",
                "valor_referencia": "Ht ≥ 20% acima do basal",
                "fonte": "MS/PCDT Dengue 2024",
                "ordem": 6,
            },
        ],
        "escores": [
            {
                "nome_escore": "Classificação MS — Grupos A/B/C/D",
                "descricao": "Grupo A: dengue sem sinais de alarme + sem comorbidade · B: sem sinais de alarme + comorbidade ou risco social · C: COM sinais de alarme · D: dengue grave (extravasamento grave, sangramento grave, disfunção orgânica)",
                "interpretacao": "A: ambulatorial · B: hidratação supervisionada/observação · C: internação + hidratação IV · D: UTI",
                "fonte": "MS/PCDT Dengue 2024",
                "ordem": 1,
            },
        ],
    },
    {
        "patologia_nome": "Zika (infecção aguda e síndrome congênita)",
        "criterios": [
            {
                "nome": "RT-PCR para ZIKV positivo em soro (< 7 dias) ou urina (até 14 dias de sintomas)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Urina tem maior janela de detecção; laboratório LACEN ou FIOCRUZ; soro: primeiros 5 dias",
                "valor_referencia": "RT-PCR positivo",
                "fonte": "MS/PCDT Zika 2022; MS Nota Técnica 2024",
                "ordem": 1,
            },
            {
                "nome": "Sorologia IgM anti-ZIKV positiva (> 5 dias) — reação cruzada com dengue (interpretar com cautela)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "ELISA IgM; reação cruzada com outros flavivírus (DENV, YFV); neutralização plaqueiforme (PRNT) para confirmar",
                "valor_referencia": "IgM positivo",
                "fonte": "MS/PCDT Zika 2022",
                "ordem": 2,
            },
            {
                "nome": "Exantema maculopapular pruriginoso + febre baixa + artralgia + conjuntivite não-purulenta",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Febre baixa (37,8–38,5°C) ou ausente; exantema pruriginoso ascendente; conjuntivite não-purulenta; artralgia de pequenas articulações",
                "valor_referencia": None,
                "fonte": "MS/PCDT Zika 2022",
                "ordem": 3,
            },
            {
                "nome": "Gestante: USG obstétrica com microcefalia ou alterações cerebrais fetais (síndrome congênita)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Microcefalia: PC < 2 DP para IG; calcificações corticais, ventriculomegalia, hipoplasia cerebelar — síndrome congênita do Zika",
                "valor_referencia": "PC < 2 DP para IG",
                "fonte": "MS/PCDT Síndrome Congênita Zika 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Chikungunya (aguda e crônica)",
        "criterios": [
            {
                "nome": "RT-PCR para CHIKV positivo em soro (< 7 dias de febre)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Alta viremia nos primeiros 3–5 dias; sensibilidade > 90% na fase virêmica; laboratório LACEN",
                "valor_referencia": "RT-PCR positivo",
                "fonte": "MS/PCDT Chikungunya 2023",
                "ordem": 1,
            },
            {
                "nome": "IgM anti-CHIKV positivo (a partir do 5º dia)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM; persiste por meses; confirmação de infecção recente",
                "valor_referencia": "IgM positivo",
                "fonte": "MS/PCDT Chikungunya 2023",
                "ordem": 2,
            },
            {
                "nome": "Febre de início súbito (≥ 38,5°C) + artralgia/artrite intensa e bilateral de grandes e pequenas articulações",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Artralgia incapacitante é o sintoma cardinal; simétrica, poliarticular, acomete mãos, punhos, tornozelos; exantema maculopapular em 40–75%",
                "valor_referencia": "Febre ≥ 38,5°C + artralgia intensa",
                "fonte": "MS/PCDT Chikungunya 2023",
                "ordem": 3,
            },
            {
                "nome": "Artralgia/artrite persistente > 3 meses (fase crônica) com PCR/VHS elevados",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "30–40% evoluem para fase crônica (> 3 meses) ou persistente (> 12 meses); pode simular artrite reumatoide",
                "valor_referencia": "Sintomas > 3 meses",
                "fonte": "MS/PCDT Chikungunya 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Febre Amarela (silvestre e urbana)",
        "criterios": [
            {
                "nome": "RT-PCR para vírus da febre amarela positivo em soro (fase virêmica, 1–5 dias)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Coleta na fase febril (antes do 5º dia); alta sensibilidade na viremia; laboratório de referência (FIOCRUZ/IEC)",
                "valor_referencia": "RT-PCR positivo",
                "fonte": "MS/SVS Guia FA 2017; MS Nota Técnica 2023",
                "ordem": 1,
            },
            {
                "nome": "Sorologia IgM anti-FA positiva (ELISA) a partir do 5º dia",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Confirmação sorológica; reação cruzada com outros flavivírus; PRNT para diferenciação",
                "valor_referencia": "IgM positivo",
                "fonte": "MS/SVS 2017",
                "ordem": 2,
            },
            {
                "nome": "Tríade clínica da FA grave: febre + icterícia + insuficiência renal + fenômenos hemorrágicos",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Síndrome de Faget: bradicardia relativa com febre; fase tóxica: icterícia, hemorragia, vômito negro, oligúria; mortalidade 20–50%",
                "valor_referencia": None,
                "fonte": "MS/SVS 2017",
                "ordem": 3,
            },
            {
                "nome": "Nexo epidemiológico: área de risco para FA + ausência de vacinação",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Áreas de transição e florestas; surtos em MG, ES, SP, PR (2016–2019); transmissão por Haemagogus e Sabethes",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023; PNI/MS",
                "ordem": 4,
            },
            {
                "nome": "ALT/AST muito elevadas (> 10× LSN) e bilirrubinas (icterícia mista) na FA grave",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "TGO e TGP marcadamente elevadas com pico entre 7–10 dias; bilirrubinas elevadas; coagulopatia (alargamento de TP/INR)",
                "valor_referencia": "AST/ALT > 10× LSN",
                "fonte": "MS/SVS 2017",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Febre do Nilo Ocidental (casos importados e autóctones)",
        "criterios": [
            {
                "nome": "IgM anti-WNV em LCR ou soro positivo (ELISA ou PRNT)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "IgM no LCR é altamente específico para neuroinvasão por WNV; persiste por ≥ 1 mês",
                "valor_referencia": "IgM WNV positivo",
                "fonte": "MS/SVS; CDC adaptado; OMS 2023",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para WNV em soro ou LCR positivo (fase virêmica precoce)",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Sensibilidade limitada (viremia breve); útil nos primeiros 3–5 dias",
                "valor_referencia": "RT-PCR positivo",
                "fonte": "MS/SVS; OMS 2023",
                "ordem": 2,
            },
            {
                "nome": "Síndrome febril com ou sem encefalite/meningite/paralisia flácida em viajante de área endêmica",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "80% assintomáticos; 20% febre do Nilo (febre, cefaleia, mialgia, exantema); < 1% neuroinvasão (encefalite, meningite, paralisia flácida)",
                "valor_referencia": None,
                "fonte": "MS/SVS",
                "ordem": 3,
            },
            {
                "nome": "Nexo epidemiológico: viagem a EUA, Europa, Oriente Médio, África ou exposição a pernilongo em área endêmica",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Transmissão por Culex; reservatório em aves; casos autóctones raros no Brasil; notificação compulsória",
                "valor_referencia": None,
                "fonte": "MS/SVS",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    # ─── HEPATITES VIRAIS (IDs 110–114) ───────────────────────────────────────
    {
        "patologia_nome": "Hepatite A",
        "criterios": [
            {
                "nome": "Anti-HAV IgM positivo (fase aguda)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM anti-HAV: diagnóstico definitivo de hepatite A aguda; positividade do 2º ao 6º mês; pico na 1ª semana de icterícia",
                "valor_referencia": "IgM anti-HAV positivo",
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 1,
            },
            {
                "nome": "ALT/AST elevadas (> 10× LSN) com síndrome ictérica aguda",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Citólise marcada; ALT tipicamente > AST; bilirrubinas com predomínio de direta; FA elevada; sem cronicidade",
                "valor_referencia": "ALT > 10× LSN",
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 2,
            },
            {
                "nome": "Síndrome pré-ictérica: febre, náuseas, vômitos, anorexia e dor em hipocôndrio direito",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Pródromo de 3–10 dias; colúria precede icterícia; acolia e prurido; auto-limitada em 95% dos casos",
                "valor_referencia": None,
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 3,
            },
            {
                "nome": "Nexo epidemiológico: ingestão de água/alimento contaminado, viagem a área endêmica",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "Transmissão fecal-oral; surtos em creches, familiares; frutos do mar crus; endêmica em regiões de saneamento precário",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hepatite B (aguda e crônica)",
        "criterios": [
            {
                "nome": "HBsAg positivo por ≥ 6 meses (hepatite B crônica) OU HBsAg + IgM anti-HBc (hepatite B aguda)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Aguda: HBsAg + IgM anti-HBc (título alto). Crônica: HBsAg persistente ≥ 6 meses + IgG anti-HBc",
                "valor_referencia": "HBsAg positivo ≥ 6 meses",
                "fonte": "MS/PCDT Hepatite B 2022; SBH 2023",
                "ordem": 1,
            },
            {
                "nome": "HBV DNA quantitativo (carga viral) elevado (≥ 2.000 UI/mL na HBsAg+/HBeAg−)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Indicação de tratamento: HBV DNA ≥ 2.000 UI/mL + ALT elevada; HBeAg+: ≥ 20.000 UI/mL",
                "valor_referencia": "≥ 2.000 UI/mL",
                "fonte": "MS/PCDT Hepatite B 2022",
                "ordem": 2,
            },
            {
                "nome": "ALT/AST elevadas (citólise) na hepatite ativa",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Critério de atividade: ALT > 1× LSN indica citólise; ALT normal pode ocorrer em portadores inativos",
                "valor_referencia": "ALT > LSN",
                "fonte": "MS/PCDT Hepatite B 2022; SBH 2023",
                "ordem": 3,
            },
            {
                "nome": "Biópsia hepática ou elastografia (FibroScan) para estadiamento de fibrose (F0–F4)",
                "categoria": "histopatologico",
                "tipo": "suporte",
                "descricao": "Fibrose avançada (F3–F4/METAVIR) indica tratamento independente do DNA. Elastografia: > 9 kPa = F3–F4",
                "valor_referencia": "METAVIR F3–F4 ou kPa > 9",
                "fonte": "MS/PCDT Hepatite B 2022; SBH 2023",
                "ordem": 4,
            },
            {
                "nome": "Pesquisa de mutações de resistência e genotipia do HBV (guia de tratamento)",
                "categoria": "laboratorial",
                "tipo": "suporte",
                "descricao": "Genotipagem A–H; no Brasil, genótipo A (45%) e D (35%) predominam; resistência a entecavir é rara",
                "valor_referencia": None,
                "fonte": "MS/PCDT Hepatite B 2022",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hepatite C (aguda e crônica)",
        "criterios": [
            {
                "nome": "Anti-HCV positivo (ELISA 3ª geração) confirmado + HCV RNA positivo (carga viral)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Diagnóstico: anti-HCV + HCV RNA por RT-PCR; anti-HCV positivo sem RNA = infecção resolvida ou falso-positivo",
                "valor_referencia": "Anti-HCV + HCV RNA positivos",
                "fonte": "MS/PCDT Hepatite C 2022; SBH 2023",
                "ordem": 1,
            },
            {
                "nome": "HCV RNA quantitativo (carga viral) e genotipagem (1–6) para orientar tratamento",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Genótipos 1 (70%), 3 (25%), 2 e 4 no Brasil; genotipagem necessária para escolha do DAA",
                "valor_referencia": "HCV RNA > LLOQ",
                "fonte": "MS/PCDT Hepatite C 2022",
                "ordem": 2,
            },
            {
                "nome": "Elastografia hepática ou FIB-4 para estadiamento de fibrose (F0–F4/METAVIR)",
                "categoria": "funcional",
                "tipo": "maior",
                "descricao": "FIB-4 = [Idade × AST] / [Plaquetas × √ALT]; < 1,3: F0–F1; > 3,25: F3–F4; elastografia > 9,5 kPa = F3–F4",
                "valor_referencia": "FIB-4 > 3,25 ou kPa > 9,5",
                "fonte": "MS/PCDT Hepatite C 2022; SBH 2023",
                "ordem": 3,
            },
            {
                "nome": "Resposta virológica sustentada (RVS12): HCV RNA indetectável 12 semanas após fim do tratamento",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "RVS12 = cura da hepatite C em > 95% dos casos com DAAs; critério de cura definitivo",
                "valor_referencia": "HCV RNA indetectável 12 sem pós-tto",
                "fonte": "MS/PCDT Hepatite C 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hepatite D (Coinfecção e Superinfecção por HDV)",
        "criterios": [
            {
                "nome": "Anti-HDV total positivo (IgM + IgG) em paciente HBsAg positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "HDV só infecta portadores de HBV (HBsAg+); anti-HDV IgM indica infecção ativa/aguda; IgG indica exposição",
                "valor_referencia": "Anti-HDV positivo em HBsAg+",
                "fonte": "MS/PCDT Hepatites Virais 2022; SBH 2023",
                "ordem": 1,
            },
            {
                "nome": "HDV RNA quantitativo positivo (carga viral) por RT-PCR",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Padrão-ouro de infecção ativa por HDV; necessário para decisão de tratamento com IFN-peguilado/bulevirtide",
                "valor_referencia": "HDV RNA positivo",
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 2,
            },
            {
                "nome": "Diferenciação: coinfecção (IgM anti-HBc + anti-HDV+) vs superinfecção (IgG anti-HBc + anti-HDV+)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Coinfecção: infecção simultânea HBV+HDV (autolimitada na maioria). Superinfecção: HDV em portador crônico de HBV (90% cronicidade)",
                "valor_referencia": None,
                "fonte": "SBH 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hepatite E",
        "criterios": [
            {
                "nome": "Anti-HEV IgM positivo (fase aguda)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM anti-HEV; positividade a partir da 1ª–2ª semana; declínio em 3–5 meses; laboratorios de referência",
                "valor_referencia": "IgM anti-HEV positivo",
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para HEV positivo em soro ou fezes (primeiros 2 semanas)",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Fase de viremia/excreção fecal; HEV RNA em fezes 1 semana antes até 2 semanas após icterícia",
                "valor_referencia": "HEV RNA positivo",
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 2,
            },
            {
                "nome": "Síndrome ictérica aguda autolimitada com anti-HBV e anti-HAV negativos (diagnóstico diferencial)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Semelhante à hepatite A; alta letalidade em gestantes (15–25%); zoonose por carne de suíno mal cozida (genótipos 3 e 4)",
                "valor_referencia": None,
                "fonte": "MS/PCDT Hepatites Virais 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    # ─── HIV/AIDS E RETROVÍRUS (IDs 115–116) ──────────────────────────────────
    {
        "patologia_nome": "HIV/AIDS (infecção aguda, crônica e AIDS estabelecida)",
        "criterios": [
            {
                "nome": "Teste de triagem reagente (ELISA 4ª geração anti-HIV + p24 Ag) + teste confirmatório (Western blot ou NAT)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Algoritmo MS 2023: 1º Teste rápido ou ELISA 4ª gen → 2º Confirmação (WB, RIBA, NAT); diagnóstico em 2 amostras",
                "valor_referencia": "2 testes reagentes em amostras diferentes",
                "fonte": "MS/PCDT HIV 2023; NOTA TÉCNICA SVS 2023",
                "ordem": 1,
            },
            {
                "nome": "CD4 (linfócitos T CD4+) < 200 células/mm³ OU < 14% = critério de AIDS",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "CD4 < 200 = imunodeficiência grave; define AIDS independente de infecção oportunista; indicação de profilaxias",
                "valor_referencia": "CD4 < 200 células/mm³",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 2,
            },
            {
                "nome": "Carga viral HIV RNA (copies/mL) para diagnóstico de síndrome retroviral aguda e monitoramento",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Síndrome aguda: carga viral muito elevada (> 100.000 cp/mL) com ELISA negativo ou indeterminado; supressão viral < 50 cp/mL = meta da TARV",
                "valor_referencia": "< 50 cp/mL (supressão) ou > 100.000 (fase aguda)",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 3,
            },
            {
                "nome": "Doença indicadora de AIDS: pneumocistose, toxoplasmose cerebral, CMV, criptococose, TB disseminada (lista CDC/MS)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Infecção oportunista ou neoplasia definidora de AIDS em PVHIV = diagnóstico de AIDS independente do CD4",
                "valor_referencia": None,
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Infecção pelo HTLV-1 (portador e formas clínicas)",
        "criterios": [
            {
                "nome": "Anti-HTLV-1/2 positivo (ELISA) + confirmação por Western blot ou PCR (diferenciação HTLV-1 de HTLV-2)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Triagem: ELISA; confirmação: WB ou PCR quantitativo para proviral DNA; diferenciação HTLV-1 vs HTLV-2 necessária",
                "valor_referencia": "Anti-HTLV-1 confirmado",
                "fonte": "MS/PCDT HTLV 2020; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "PCR quantitativo (carga proviral) para HTLV-1 — monitoramento e risco de progressão",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Carga proviral > 1% de PBMCs aumenta risco de HAM/TSP e ATLL; monitoramento semestral",
                "valor_referencia": "Carga proviral > 1%",
                "fonte": "MS/PCDT HTLV 2020",
                "ordem": 2,
            },
            {
                "nome": "Transmissão: aleitamento materno, sexual (HSH e heterossexual), transfusão, UDIV",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "Bahia, PE, MA têm maior prevalência no Brasil; triagem obrigatória em doadores de sangue desde 1993",
                "valor_referencia": None,
                "fonte": "MS/PCDT HTLV 2020; HEMOBRAS",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    # ─── HERPESVÍRUS (IDs 117–121) ────────────────────────────────────────────
    {
        "patologia_nome": "Herpes Simples (orolabial, genital e neonatal)",
        "criterios": [
            {
                "nome": "PCR para HSV-1 ou HSV-2 positivo em swab de lesão, LCR ou secreção",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "PCR é o método de escolha (sensibilidade > 95%); diferenciar HSV-1 (orolabial) de HSV-2 (genital); HSV no LCR = encefalite",
                "valor_referencia": "PCR HSV positivo",
                "fonte": "MS/PCDT IST 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Vesículas ou úlceras dolorosas agrupadas sobre base eritematosa no local de inoculação",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Vesículas em cacho sobre base eritematosa → úlceras superficiais dolorosas → crosta; herpes genital: lesão genitália, períneo",
                "valor_referencia": None,
                "fonte": "MS/PCDT IST 2022",
                "ordem": 2,
            },
            {
                "nome": "Citodiagnóstico de Tzanck com células gigantes multinucleadas (método de suporte — baixa especificidade)",
                "categoria": "laboratorial",
                "tipo": "menor",
                "descricao": "Raspado de base da vesícula; células gigantes multinucleadas são sugestivas mas não diferenciam HSV de VZV",
                "valor_referencia": "Células gigantes multinucleadas",
                "fonte": "MS/PCDT IST 2022",
                "ordem": 3,
            },
            {
                "nome": "IgM anti-HSV (primoinfecção) ou IgG elevado (reativação/antecedente)",
                "categoria": "laboratorial",
                "tipo": "menor",
                "descricao": "Sorologia pouco útil na fase aguda de lesão localizada; IgG indica soroprevalência (não infecção ativa)",
                "valor_referencia": None,
                "fonte": "MS/PCDT IST 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Varicela (catapora)",
        "criterios": [
            {
                "nome": "Exantema vesicular pruriginoso em diferentes estágios evolutivos (máculas, pápulas, vesículas, crostas) simultâneos",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesões polimorfas em diferentes estádios no mesmo momento ('céu estrelado'); predominam no tronco; enantema (vesículas mucosas)",
                "valor_referencia": None,
                "fonte": "SBP 2022; SBD 2022; MS/SVS",
                "ordem": 1,
            },
            {
                "nome": "Diagnóstico clínico na maioria dos casos; PCR para VZV em lesão vesicular (casos graves, atípicos ou imunocomprometidos)",
                "categoria": "microbiologico",
                "tipo": "suporte",
                "descricao": "PCR em conteúdo vesicular; cultura viral; imunofluorescência direta em casos de dúvida diagnóstica",
                "valor_referencia": "PCR VZV positivo",
                "fonte": "SBP 2022",
                "ordem": 2,
            },
            {
                "nome": "Febre baixa (37,5–38,5°C) precedendo exantema em 1–2 dias + prurido intenso",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Pródromos discretos; contagioso 1–2 dias antes até todas as lesões em crosta",
                "valor_referencia": None,
                "fonte": "SBP 2022",
                "ordem": 3,
            },
            {
                "nome": "Nexo epidemiológico: contato com caso de varicela ou herpes zoster nos 10–21 dias anteriores",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "PI 10–21 dias (média 14–16 dias); transmissão aérea e por contato direto; altamente contagioso",
                "valor_referencia": "IP: 10–21 dias",
                "fonte": "MS/SVS",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Herpes Zoster (cobreiro)",
        "criterios": [
            {
                "nome": "Erupção vesicular unilateral dermatomérica com dor neuropática precedente (≥ 72h antes do exantema)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Dor ou queimação intensa em dermátomo → eritema → vesículas agrupadas; unilateral; não cruza a linha média",
                "valor_referencia": None,
                "fonte": "SBD 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "PCR para VZV em swab vesicular (confirmação em casos atípicos, sem exantema — zoster sine herpete)",
                "categoria": "microbiologico",
                "tipo": "suporte",
                "descricao": "Útil em zoster craniano, oftálmico (V1), neurológico grave; VZV DNA em LCR em meningite/encefalite",
                "valor_referencia": "PCR VZV positivo",
                "fonte": "SBD 2022; ABN 2022",
                "ordem": 2,
            },
            {
                "nome": "Fator predisponente: imunossupressão, idade > 50 anos, neoplasia, estresse",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "Reativação do VZV latente em gânglio dorsal; risco aumenta com a idade; imunossuprimidos podem ter formas disseminadas",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 3,
            },
            {
                "nome": "Neuralgia pós-herpética (NPH): dor persistente no dermátomo > 3 meses após cura das lesões",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Complicação em 10–30% dos casos; mais frequente em > 60 anos; dor neuropática (queimação, alodinia)",
                "valor_referencia": "Dor > 3 meses pós-lesão",
                "fonte": "SBD 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Citomegalovirose (CMV) em Imunocomprometidos",
        "criterios": [
            {
                "nome": "CMV DNA quantitativo (carga viral) em sangue (plasma ou sangue total) positivo por PCR",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Limiar de tratamento: > 500 UI/mL (plasma) em transplantados; monitoramento semanal em alto risco; resultado em UI/mL (padronizado OMS)",
                "valor_referencia": "> 500 UI/mL (plasma)",
                "fonte": "SBI 2023; ABTO 2022",
                "ordem": 1,
            },
            {
                "nome": "Evidência histológica de inclusões intranucleares 'olho de coruja' em biópsia do órgão alvo",
                "categoria": "histopatologico",
                "tipo": "obrigatorio",
                "descricao": "Células com inclusão nuclear grandes; imuno-histoquímica anti-CMV confirma; retinite/colite/esofagite/pneumonite por CMV",
                "valor_referencia": "Inclusões virais + IHQ CMV+",
                "fonte": "SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Síndrome viral por CMV: febre + leucopenia + trombocitopenia + elevação de transaminases",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Síndrome CMV em transplantados sem evidência de invasão orgânica; diagnóstico clínico + viremia",
                "valor_referencia": None,
                "fonte": "SBI 2023; ABTO 2022",
                "ordem": 3,
            },
            {
                "nome": "Contexto de imunodeficiência grave: transplante, HIV/CD4 < 50, corticóide alto dose",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "CMV oportunista; transplantado soronegativo recebendo órgão CMV+ tem maior risco",
                "valor_referencia": None,
                "fonte": "SBI 2023; ABTO 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Mononucleose Infecciosa (EBV)",
        "criterios": [
            {
                "nome": "Monoteste (anticorpos heterófilos de Paul-Bunnell) positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade 85% em adultos; menos sensível em < 10 anos; positividade na 1ª–2ª semana dos sintomas",
                "valor_referencia": "Monoteste positivo",
                "fonte": "SBP 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Tríade clínica: faringite exsudativa + febre + adenomegalia cervical posterior",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Faringite grave com exsudato branco; adenomegalia cervical posterior e generalizada; esplenomegalia em 50%",
                "valor_referencia": None,
                "fonte": "SBP 2022",
                "ordem": 2,
            },
            {
                "nome": "Linfocitose com linfócitos atípicos > 10% no diferencial do hemograma",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Linfocitose absoluta > 4.500/mm³; linfócitos atípicos (virocitos) > 10% são característicos",
                "valor_referencia": "Linfócitos atípicos > 10%",
                "fonte": "SBP 2022",
                "ordem": 3,
            },
            {
                "nome": "Anti-VCA IgM positivo (sorologia específica para EBV — fase aguda)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Anti-VCA IgM confirma infecção primária aguda por EBV; anti-VCA IgG + anti-EBNA negativos = infecção aguda",
                "valor_referencia": "Anti-VCA IgM positivo",
                "fonte": "SBP 2022; SBI 2023",
                "ordem": 4,
            },
            {
                "nome": "Transaminases elevadas (ALT/AST 2–5×) e/ou hepatomegalia",
                "categoria": "laboratorial",
                "tipo": "menor",
                "descricao": "Hepatite por EBV presente em > 80% dos casos; icterícia em < 10%",
                "valor_referencia": "ALT/AST 2–5× LSN",
                "fonte": "SBP 2022",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    # ─── RESPIRATÓRIO VIRAL (IDs 122–125) ─────────────────────────────────────
    {
        "patologia_nome": "Influenza (gripe sazonal e pandêmica)",
        "criterios": [
            {
                "nome": "RT-PCR para influenza A ou B positivo em swab nasofaríngeo ou aspirado nasofaríngeo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Padrão-ouro diagnóstico; coleta nas primeiras 72h; identificação do subtipo (A/H3N2, A/H1N1pdm09, B/Vic, B/Yam)",
                "valor_referencia": "RT-PCR influenza positivo",
                "fonte": "MS/SVS Guia Influenza 2023",
                "ordem": 1,
            },
            {
                "nome": "Teste rápido de antígeno para influenza A/B (TRFIA) positivo (sensibilidade 50–70%)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Resultado em 15–30 min; especificidade > 90%; negativo não exclui em período epidêmico",
                "valor_referencia": "Positivo",
                "fonte": "MS/SVS 2023",
                "ordem": 2,
            },
            {
                "nome": "Síndrome gripal: febre ≥ 38°C de início súbito + ≥ 1: tosse, dor de garganta, rinorreia, cefaleia, mialgia, artralgia",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Definição de caso de síndrome gripal (SG) MS 2023: febre ≥ 38°C de início abrupto + ≥ 1 sintoma respiratório",
                "valor_referencia": "Febre ≥ 38°C + ≥ 1 sintoma",
                "fonte": "MS/SVS 2023",
                "ordem": 3,
            },
            {
                "nome": "Síndrome respiratória aguda grave (SRAG): necessidade de hospitalização por pneumonia/SARA",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "SRAG: SG + dispneia/SpO₂ < 95% ou SatO₂ caindo → hospitalização; notificação compulsória",
                "valor_referencia": "SpO₂ < 95%",
                "fonte": "MS/SVS 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "COVID-19 (infecção aguda, grave e síndrome pós-COVID)",
        "criterios": [
            {
                "nome": "RT-PCR para SARS-CoV-2 positivo em swab nasofaríngeo ou orofaríngeo (padrão-ouro na fase aguda)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Coleta nos primeiros 5–7 dias; sensibilidade depende da coleta correta e da carga viral; resultado em 4–6h",
                "valor_referencia": "RT-PCR SARS-CoV-2 positivo",
                "fonte": "MS/PCDT COVID-19 2022; MS Nota Técnica 2023",
                "ordem": 1,
            },
            {
                "nome": "Teste de antígeno para SARS-CoV-2 positivo (sensibilidade 70–85%, especificidade > 97%)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Antígeno viral (Ag-RDT); resultado em 15–30 min; útil nos primeiros 5 dias de sintomas; negativo não exclui",
                "valor_referencia": "Ag SARS-CoV-2 positivo",
                "fonte": "MS/PCDT COVID-19 2022",
                "ordem": 2,
            },
            {
                "nome": "Síndrome clínica COVID-19: febre ou calafrios + tosse/falta de ar ± perda de olfato/paladar",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Anosmia e ageusia são altamente específicas; cefaleia, mialgia, fadiga; variantes Omicron: sintomas mais faríngeos",
                "valor_referencia": None,
                "fonte": "MS/PCDT COVID-19 2022",
                "ordem": 3,
            },
            {
                "nome": "TC de tórax com opacidades em vidro fosco bilaterais periféricas e basais (COVID-19 pneumonia)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Padrão típico: vidro fosco bilateral + consolidação + padrão pavimentado (crazy paving); pontuação CO-RADS 4–5",
                "valor_referencia": "CO-RADS 4–5 ou típico",
                "fonte": "CBR/SBMR 2020; MS/PCDT 2022",
                "ordem": 4,
            },
            {
                "nome": "Marcadores de gravidade: D-dímero elevado, ferritina > 500, IL-6, LDH, troponina, PCR > 100 mg/L",
                "categoria": "laboratorial",
                "tipo": "suporte",
                "descricao": "D-dímero > 1.000 ng/mL: risco de TEP/CID; ferritina > 1.000: tempestade de citocinas; usar para guiar anticoagulação e corticóide",
                "valor_referencia": "D-dímero > 1.000; ferritina > 500",
                "fonte": "MS/PCDT COVID-19 2022",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Infecção pelo Vírus Sincicial Respiratório (VSR/RSV)",
        "criterios": [
            {
                "nome": "Teste rápido de antígeno para VSR positivo ou RT-PCR para VSR positivo em aspirado nasofaríngeo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Teste rápido: sensibilidade 70–90% em lactentes; RT-PCR: maior sensibilidade em adultos e idosos; subtipo A e B",
                "valor_referencia": "Antígeno VSR positivo",
                "fonte": "SBP 2022; MS/SVS SRAG 2023",
                "ordem": 1,
            },
            {
                "nome": "Bronquiolite aguda: sibilo expiratório + hiperinsuflação + dificuldade respiratória em lactente < 2 anos",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Taquipneia, retrações intercostais e subcostais, sibilância e crepitações; SpO₂ < 92% indica gravidade",
                "valor_referencia": "SpO₂ < 92% = grave",
                "fonte": "SBP 2022",
                "ordem": 2,
            },
            {
                "nome": "Radiografia de tórax com hiperinsuflação e atelectasias segmentares (bronquiolite)",
                "categoria": "imagem",
                "tipo": "menor",
                "descricao": "RX não é obrigatório em bronquiolite típica; indicado em SpO₂ < 90%, febre elevada ou dúvida diagnóstica",
                "valor_referencia": None,
                "fonte": "SBP 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Infecção por Adenovírus Respiratório",
        "criterios": [
            {
                "nome": "PCR ou teste rápido para adenovírus positivo em amostra respiratória (swab nasofaríngeo ou lavado broncoalveolar)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "RT-PCR múltiplex em painel respiratório; cultura viral em linhagem celular (HEp-2, A549); sorotipos 1, 2, 3, 4, 7 mais comuns",
                "valor_referencia": "PCR adenovírus positivo",
                "fonte": "MS/SVS SRAG 2023; SBP 2022",
                "ordem": 1,
            },
            {
                "nome": "Febre alta persistente (≥ 39°C, > 5 dias) com faringite e/ou conjuntivite folicular",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Febre faringoconjuntival (FFC): clássico de Adenovírus 3 e 7; febre alta prolongada, conjuntivite folicular unilateral ou bilateral, faringite",
                "valor_referencia": "Febre ≥ 39°C > 5 dias",
                "fonte": "SBP 2022",
                "ordem": 2,
            },
            {
                "nome": "Leucocitose pode estar presente (diferencia de influenza que causa leucopenia)",
                "categoria": "laboratorial",
                "tipo": "menor",
                "descricao": "Adenovírus pode causar leucocitose moderada; PCR elevada; simula infecção bacteriana",
                "valor_referencia": None,
                "fonte": "SBP 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    # ─── EXANTEMAS / ENTÉRICOS / NEUROLÓGICOS VIRAIS (IDs 126–143) ─────────────
    {
        "patologia_nome": "Sarampo",
        "criterios": [
            {
                "nome": "IgM anti-sarampo positivo (a partir do 3º dia de exantema)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM; coleta soro ou saliva; laboratório LACEN; positivo a partir do 3º dia de exantema",
                "valor_referencia": "IgM positivo",
                "fonte": "MS/SVS Guia Sarampo 2020; PNI/MS 2023",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para vírus do sarampo em swab nasofaríngeo, urina ou LCR positivo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Padrão-ouro; coleta até 5–7 dias após exantema; genotipagem para vigilância epidemiológica",
                "valor_referencia": "RT-PCR sarampo positivo",
                "fonte": "MS/SVS 2020",
                "ordem": 2,
            },
            {
                "nome": "Tríade Koplik + exantema maculopapular craniocaudal + febre alta (4Cs: Coriza, Conjuntivite, Cough, Koplik)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Manchas de Koplik (patognomônicas): manchas brancas na mucosa bucal antes do exantema; exantema começa no rosto; febre ≥ 38,5°C",
                "valor_referencia": None,
                "fonte": "MS/SVS 2020",
                "ordem": 3,
            },
            {
                "nome": "Histórico vacinal incompleto (< 2 doses SCR/MMR) ou não vacinado",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Brasil: surtos em 2018–2020 (SP, AM); notificação compulsória imediata; 2 doses de SCR a partir dos 12 meses",
                "valor_referencia": None,
                "fonte": "PNI/MS 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Rubéola (adquirida e congênita)",
        "criterios": [
            {
                "nome": "IgM anti-rubéola positivo em soro ou saliva (exantema agudo)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM; positivo a partir do 1º dia de exantema; laboratório LACEN; coleta até 28 dias do exantema",
                "valor_referencia": "IgM anti-rubéola positivo",
                "fonte": "MS/SVS Guia Rubéola 2023; PNI/MS",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para vírus da rubéola em swab nasofaríngeo, urina ou LCR positivo",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Genotipagem para vigilância; coleta nos primeiros 4–7 dias do exantema",
                "valor_referencia": "RT-PCR rubéola positivo",
                "fonte": "MS/SVS 2023",
                "ordem": 2,
            },
            {
                "nome": "Exantema maculopapular róseo craniocaudal + adenomegalia retroauricular/cervical posterior + febre baixa",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Linfonodos retroauriculares e cervicais posteriores dolorosos (patognomônicos); exantema dura 3 dias; artralgia em adultos",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 3,
            },
            {
                "nome": "Síndrome da Rubéola Congênita (SRC): tríade de Gregg — catarata, cardiopatia congênita, surdez",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "SRC em RN de mãe infectada no 1º trimestre; IgM anti-rubéola no RN + manifestações clínicas da tríade",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Caxumba / Parotidite Epidêmica",
        "criterios": [
            {
                "nome": "IgM anti-caxumba positivo (fase aguda) OU soroconversão de IgG (≥ 4×)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "ELISA IgM: sensibilidade reduzida em vacinados (falso-negativo em até 50% dos vacinados com 2 doses); coleta no 1º–5º dia",
                "valor_referencia": "IgM positivo ou soroconversão",
                "fonte": "MS/SVS 2023; PNI/MS",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para vírus da caxumba em swab bucal/saliva ou urina positivo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Método de escolha em vacinados (sorologia menos sensível); coleta nos primeiros 3–8 dias de parotidite",
                "valor_referencia": "RT-PCR caxumba positivo",
                "fonte": "MS/SVS 2023",
                "ordem": 2,
            },
            {
                "nome": "Parotidite bilateral (ou unilateral) dolorosa com edema em ângulo mandibular + febre",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Parotidite em 95% dos casos; edema pré-auricular; pode haver orquite (30% homens pós-puberdade), meningite asséptica, pancreatite",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Doença Mão-Pé-Boca (Enterovírus 71 e Coxsackievírus A16)",
        "criterios": [
            {
                "nome": "Vesículas e/ou úlceras na cavidade oral + lesões em palmas e plantas (vesículas ovais)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Enantema: vesículas e úlceras dolorosas em mucosa oral, língua, gengiva; exantema: vesículas ovais em palmas, plantas, nádegas",
                "valor_referencia": None,
                "fonte": "SBP 2022; MS/SVS 2023",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para Enterovírus A71 ou Coxsackievírus A16 em swab orofaríngeo ou fezes",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "PCR específico para tipagem; EV-A71 tem maior potencial de complicações neurológicas (encefalite, paralisia)",
                "valor_referencia": "RT-PCR enterovírus positivo",
                "fonte": "SBP 2022",
                "ordem": 2,
            },
            {
                "nome": "Criança < 5 anos com febre + lesões típicas em surto familiar ou escolar",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Altamente contagiosa; transmissão fecal-oral e por contato; PI 3–7 dias; surtos em creches e pré-escolas",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Rotavirose (diarreia por Rotavírus)",
        "criterios": [
            {
                "nome": "Teste rápido de imunocromatografia ou ELISA para antígeno de Rotavírus nas fezes positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Detecção de antígeno VP6 nas fezes; sensibilidade > 90%; resultado em 30 min; indicado em lactentes com diarreia intensa",
                "valor_referencia": "Ag Rotavírus positivo",
                "fonte": "SBP 2022; MS/SVS",
                "ordem": 1,
            },
            {
                "nome": "Diarreia aquosa volumosa (3–8 dias), vômitos e febre em lactentes e pré-escolares",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Desidratação rapidamente progressiva; pico de incidência 6–24 meses; sazonalidade: inverno no Sul/Sudeste",
                "valor_referencia": None,
                "fonte": "SBP 2022",
                "ordem": 2,
            },
            {
                "nome": "Ausência de vacinação para rotavírus (fator de risco)",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "Vacina Rotarix (monovalente) no calendário PNI; esquema: 2 doses (2 e 4 meses); redução de > 80% das hospitalizações",
                "valor_referencia": None,
                "fonte": "PNI/MS 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Norovirose (diarreia e vômito por Norovírus)",
        "criterios": [
            {
                "nome": "RT-PCR para Norovírus genogrupos GI ou GII em fezes positivo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Padrão-ouro; ELISA tem sensibilidade menor; RT-PCR em tempo real em fezes coletadas na fase aguda",
                "valor_referencia": "RT-PCR norovírus positivo",
                "fonte": "MS/SVS 2023",
                "ordem": 1,
            },
            {
                "nome": "Síndrome de vômitos e diarreia aquosa de curta duração (12–72h) em surto coletivo",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Vômitos intensos + diarreia aquosa sem sangue + náuseas; alta contagiosidade; PI 12–48h; auto-limitada em 1–3 dias",
                "valor_referencia": "Duração < 72h",
                "fonte": "MS/SVS 2023",
                "ordem": 2,
            },
            {
                "nome": "Nexo epidemiológico: surto alimentar (moluscos, saladas, água contaminada) ou surto em ambiente fechado",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Causa mais comum de gastroenterite viral em adultos; surtos em cruzeiros, hotéis, hospitais, escolas",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Raiva (raiva humana transmitida por cão, morcego ou animais silvestres)",
        "criterios": [
            {
                "nome": "Detecção de antígeno do vírus rábico por imunofluorescência direta (IFD) em biópsia de nuca ou esfregaço corneal",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "IFD em nuca (biópsia de folículo piloso) ou córnea (esfregaço); sensibilidade 60–100%; confirmação post-mortem no SNC",
                "valor_referencia": "IFD positivo",
                "fonte": "MS/SVS Guia Raiva 2022",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para vírus rábico em saliva, LCR, urina ou biópsia de nuca positivo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "PCR em tempo real é mais sensível que IFD em amostras de vida (ante-mortem); laboratório FIOCRUZ/IEC/LACEN",
                "valor_referencia": "RT-PCR rábico positivo",
                "fonte": "MS/SVS 2022",
                "ordem": 2,
            },
            {
                "nome": "Exposição a animal suspeito (mordida, arranhadura, lambedura em mucosa) + síndrome neurológica progressiva fatal",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "PI 20–60 dias; cão (raiva urbana) e morcego (raiva silvestre) são os principais transmissores no Brasil; profilaxia pós-exposição",
                "valor_referencia": "PI: 20–60 dias",
                "fonte": "MS/SVS 2022",
                "ordem": 3,
            },
            {
                "nome": "Síndrome encefalítica: hidrofobia, aerofobia, espasmos faríngeos, agitação extrema (forma furiosa)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Hidrofobia e aerofobia são patognomônicas da forma furiosa (80%); forma paralítica: paralisia flácida ascendente (20%)",
                "valor_referencia": None,
                "fonte": "MS/SVS 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Encefalite Herpética (HSV-1)",
        "criterios": [
            {
                "nome": "PCR para HSV-1 (ou HSV-2) em LCR positivo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Padrão-ouro; sensibilidade > 95%, especificidade > 99%; pode ser negativo nas primeiras 24–72h — repetir se forte suspeita",
                "valor_referencia": "HSV DNA no LCR positivo",
                "fonte": "ABN 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "RM de encéfalo com hipersinal em T2/FLAIR em lobo temporal (uni ou bilateral) + giro cíngulo",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Acometimento temporal (especialmente mesial/insular) com edema; restrição à difusão (DWI); hemorragia petequial",
                "valor_referencia": "Hipersinal T2/FLAIR temporal",
                "fonte": "ABN 2022",
                "ordem": 2,
            },
            {
                "nome": "Síndrome de encefalopatia subaguda: febre + confusão + convulsões + afasia/alteração comportamental",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Início subagudo (horas–dias); febre + alteração comportamental (sintomas psiquiátricos) + convulsões focais temporais",
                "valor_referencia": None,
                "fonte": "ABN 2022",
                "ordem": 3,
            },
            {
                "nome": "EEG com atividade periódica lateralizada (PLEDs/LPDs) no lobo temporal",
                "categoria": "funcional",
                "tipo": "maior",
                "descricao": "LPDs (Lateralized Periodic Discharges) a cada 1–2s no temporal são altamente sugestivos; pode ter NCSE",
                "valor_referencia": "LPDs temporais",
                "fonte": "ABN 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Meningite Viral (enterovírus e outros)",
        "criterios": [
            {
                "nome": "LCR com pleocitose mononuclear (10–500 células), proteínas levemente elevadas, glicose normal",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "LCR límpido/xantocrômico; células predom. mononucleares (linfócitos); proteínas 50–150 mg/dL; glicose normal (> 60% da sérica)",
                "valor_referencia": "PMN < 50%, glicose normal",
                "fonte": "ABN 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "RT-PCR para enterovírus em LCR positivo (mais frequente) ou para outros vírus (HSV, VZV, EBV, CMV)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Enterovírus: 85–95% das meningites virais; PCR em painel multiplex; identifica o agente em 30–70%",
                "valor_referencia": "RT-PCR viral positivo no LCR",
                "fonte": "ABN 2022",
                "ordem": 2,
            },
            {
                "nome": "Síndrome meníngea: cefaleia + rigidez de nuca + febre sem alteração de consciência (Glasgow ≥ 14)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Benignidade relativa vs meningite bacteriana; resolução espontânea em 5–14 dias; forma asséptica",
                "valor_referencia": "Glasgow ≥ 14",
                "fonte": "ABN 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Infecção pelo HPV (verrugas genitais e lesões precursoras)",
        "criterios": [
            {
                "nome": "Diagnóstico clínico de condiloma acuminado (verruga genital) por inspeção visual",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesões exofíticas papilomatosas, rosadas ou acastanhadas, em genitália, períneo, ânus; teste do ácido acético (acetobranqueamento)",
                "valor_referencia": None,
                "fonte": "MS/PCDT IST 2022",
                "ordem": 1,
            },
            {
                "nome": "PCR para HPV com genotipagem em amostra cervical, anal ou de lesão (HPV de alto risco: 16, 18, 31, 33, 45)",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "HPV 16 e 18: alto risco oncogênico (70% dos CEC de colo uterino); genotipagem orienta vigilância",
                "valor_referencia": "HPV alto risco positivo",
                "fonte": "MS/PCDT IST 2022; FEBRASGO 2023",
                "ordem": 2,
            },
            {
                "nome": "Citologia oncótica (Papanicolaou) com alterações coilocitóticas (LSIL/HSIL) + colposcopia",
                "categoria": "histopatologico",
                "tipo": "maior",
                "descricao": "LSIL (NIC 1): infecção produtiva por HPV; HSIL (NIC 2-3): lesão precursora de alto grau; biópsia confirma",
                "valor_referencia": "HSIL = NIC 2–3",
                "fonte": "MS/PCDT Câncer Colo Útero 2022; FEBRASGO 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hantavirose (Síndrome Cardiopulmonar por Hantavírus — SCPH)",
        "criterios": [
            {
                "nome": "IgM anti-hantavírus positivo (ELISA) ou RT-PCR para hantavírus em soro positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "IgM positivo na fase prodrômica; RT-PCR mais sensível na viremia (dias 1–5); laboratório FIOCRUZ/IEC",
                "valor_referencia": "IgM ou RT-PCR positivo",
                "fonte": "MS/SVS Guia Hantavirose 2013; MS 2023",
                "ordem": 1,
            },
            {
                "nome": "Síndrome cardiopulmonar: dispneia progressiva + infiltrado intersticial bilateral + choque cardiogênico em contexto rural",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Pródromo febril 2–5 dias; depois dispneia súbita; infiltrado bilateral na RX; choque e SARA; mortalidade 30–40%",
                "valor_referencia": None,
                "fonte": "MS/SVS 2013",
                "ordem": 2,
            },
            {
                "nome": "Nexo epidemiológico: área rural/periurbana + exposição a roedores silvestres (Oligoryzomys spp.)",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Transmissão por inalação de aerossol de fezes/urina de roedores; Cerrado, Mata Atlântica; estados: SP, MG, RS, PR, MS",
                "valor_referencia": None,
                "fonte": "MS/SVS 2023",
                "ordem": 3,
            },
            {
                "nome": "Trombocitopenia grave (< 100.000/mm³) + leucocitose com imunoblastos + hematócrito elevado",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Plaquetopenia precoce; imunoblastos no diferencial; hemoconcentração por extravasamento capilar",
                "valor_referencia": "Plaquetas < 100.000/mm³",
                "fonte": "MS/SVS 2013",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Síndrome Congênita do Zika Vírus",
        "criterios": [
            {
                "nome": "Microcefalia (PC < −2 DP para IG e sexo) OU comprometimento congênito do SNC em RN/lactente de mãe com Zika confirmada",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "PC < −2 DP é o critério principal; associado a: calcificações corticais, displasia, lisencefalia, ventriculomegalia, hipoplasia cerebelar",
                "valor_referencia": "PC < −2 DP",
                "fonte": "MS/PCDT Síndrome Congênita Zika 2022",
                "ordem": 1,
            },
            {
                "nome": "PCR ou IgM anti-ZIKV positivo no soro ou LCR do RN",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "IgM anti-ZIKV no soro do RN (não transferido passivamente pela mãe = indica infecção congênita)",
                "valor_referencia": "IgM anti-ZIKV positivo",
                "fonte": "MS/PCDT Síndrome Congênita Zika 2022",
                "ordem": 2,
            },
            {
                "nome": "TC ou RM de crânio com calcificações corticais/subcorticais na junção córtex-substância branca",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Calcificações em junção córtex-SB são específicas para Zika congênita; TC de crânio é 1ª escolha em RN",
                "valor_referencia": None,
                "fonte": "MS/PCDT Síndrome Congênita Zika 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "CMV Congênito",
        "criterios": [
            {
                "nome": "PCR quantitativo para CMV em urina ou saliva coletada até os 21 dias de vida",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Padrão-ouro: CMV na urina nas 3 primeiras semanas indica infecção congênita (vs pós-natal pelo leite materno); > 10⁵ cópias/mL",
                "valor_referencia": "CMV DNA positivo < 21 dias de vida",
                "fonte": "SBP 2023; MS/PCDT",
                "ordem": 1,
            },
            {
                "nome": "Manifestações ao nascimento: petéquias, hepatoesplenomegalia, icterícia, microcefalia, perda auditiva",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "90% assintomáticos ao nascimento; 10% sintomáticos com alto risco de sequelas neurológicas; SNHL é a sequela mais frequente",
                "valor_referencia": None,
                "fonte": "SBP 2023",
                "ordem": 2,
            },
            {
                "nome": "Triagem neonatal para SNHL (perda auditiva neurossensorial) por PEATE com limiares alterados",
                "categoria": "funcional",
                "tipo": "suporte",
                "descricao": "SNHL bilateral progressiva é a sequela mais comum do CMV congênito; triagem PEATE obrigatória em todas as crianças",
                "valor_referencia": "PEATE com resposta > 35 dBnHL",
                "fonte": "SBP 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hepatite B Perinatal (transmissão vertical)",
        "criterios": [
            {
                "nome": "HBsAg positivo no RN após 9–12 meses de vida (confirma infecção crônica perinatal)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "HBsAg testado nos 9–12 meses; anti-HBs negativo (falha vacinal ou infecção); HBsAg + = infecção crônica",
                "valor_referencia": "HBsAg positivo aos 9–12 meses",
                "fonte": "MS/PCDT Hepatite B 2022; SBP 2023",
                "ordem": 1,
            },
            {
                "nome": "Mãe HBsAg positiva (especialmente HBeAg+ ou HBV DNA > 200.000 UI/mL) como fator de risco",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Risco de transmissão: HBeAg+ mãe = 70–90%; HBeAg− = 10–40%; HBV DNA > 200.000 = alto risco",
                "valor_referencia": "HBeAg+ ou HBV DNA > 200.000 UI/mL",
                "fonte": "MS/PCDT Hepatite B 2022",
                "ordem": 2,
            },
            {
                "nome": "Imunoprofilaxia do RN: vacina HBV + HBIG nas primeiras 12h de vida (prevenção)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Vacina + HBIG ≤ 12h: eficácia 85–95%; sem profilaxia em mãe HBeAg+: risco 70–90% de infecção crônica",
                "valor_referencia": "Vacina + HBIG ≤ 12h",
                "fonte": "MS/PCDT Hepatite B 2022; PNI/MS",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Herpes Neonatal (HSV)",
        "criterios": [
            {
                "nome": "PCR para HSV positivo em swab de lesão, LCR, sangue ou superfície (olhos, boca, nasofaringe, reto)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "PCR em múltiplos sítios de superfície; PCR LCR para neurológica e disseminada; coleta antes do aciclovir",
                "valor_referencia": "PCR HSV positivo",
                "fonte": "SBP 2023; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Classificação clínica: SEM (pele/olhos/boca), SNC (encefalite), Disseminada",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "SEM: vesículas cutâneas + ceratoconjuntivite (melhor prognóstico). SNC: convulsões + LCR alterado. Disseminada: sepse + disfunção orgânica (maior mortalidade)",
                "valor_referencia": None,
                "fonte": "SBP 2023",
                "ordem": 2,
            },
            {
                "nome": "Mãe com herpes genital ativo ou primoinfecção por HSV no 3º trimestre",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Primoinfecção materna no 3º trimestre: risco > 50% de transmissão; herpes genital recorrente: risco < 3%",
                "valor_referencia": None,
                "fonte": "SBP 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Poliomielite (pólio)",
        "criterios": [
            {
                "nome": "Isolamento do vírus pólio (selvagem ou vacinal) em fezes ou LCR por cultura viral",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Cultura de 2 amostras de fezes coletadas com intervalo ≥ 24h e até 14 dias do início da paralisia; laboratório de referência",
                "valor_referencia": "Poliovírus isolado",
                "fonte": "MS/SVS Guia Poliomielite 2020; PNI/MS",
                "ordem": 1,
            },
            {
                "nome": "Paralisia flácida aguda (PFA) assimétrica de início súbito em criança < 15 anos",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Critério de vigilância MS: qualquer criança < 15 anos com PFA de qualquer causa é caso suspeito e deve ser notificado",
                "valor_referencia": None,
                "fonte": "MS/SVS 2020",
                "ordem": 2,
            },
            {
                "nome": "Ausência de vacinação completa (< 4 doses VIP/VOP) ou criança não vacinada",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Brasil livre de pólio selvagem desde 1989; risco de reintrodução em vacinação inadequada; vigilância da PFA",
                "valor_referencia": None,
                "fonte": "PNI/MS 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "HTLV — Leucemia/Linfoma de Células T do Adulto (ATLL)",
        "criterios": [
            {
                "nome": "Anti-HTLV-1 positivo confirmado (Western blot) + morfologia de células em flor no esfregaço de sangue periférico",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Células com núcleo multilobulado (flower cells/lobulated) em sangue periférico; CD4+CD25+ por citometria de fluxo",
                "valor_referencia": "Flower cells + HTLV-1 positivo",
                "fonte": "MS/PCDT HTLV 2020; APCBT",
                "ordem": 1,
            },
            {
                "nome": "Biópsia de linfonodo, sangue ou lesão de pele com linfoma de células T CD4+CD25+CD7−",
                "categoria": "histopatologico",
                "tipo": "obrigatorio",
                "descricao": "Imunofenotipagem: CD4+, CD25+, CD7−, TCR alfa-beta+; integração clonal do HTLV-1 por Southern blot",
                "valor_referencia": "CD4+CD25+CD7−",
                "fonte": "MS/PCDT HTLV 2020",
                "ordem": 2,
            },
            {
                "nome": "Hipercalcemia, lesões ósseas líticas e linfadenopatia generalizada (forma aguda/linfomatosa)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Hipercalcemia mediada por PTHrP (síndrome humoral); lesões ósseas osteolíticas; hepatoesplenomegalia; leucocitose maligna",
                "valor_referencia": "Ca++ > 10,5 mg/dL",
                "fonte": "MS/PCDT HTLV 2020",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "HTLV — Mielopatia Associada ao HTLV / Paraparesia Espástica Tropical (HAM/TSP)",
        "criterios": [
            {
                "nome": "Anti-HTLV-1 positivo no soro E no LCR (Western blot ou ELISA confirmatório)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Critérios diagnósticos OMS/Castro: HTLV-1 positivo no soro E LCR + clínica + exclusão de outras mielopatias",
                "valor_referencia": "Anti-HTLV-1 positivo no soro e LCR",
                "fonte": "MS/PCDT HTLV 2020; OMS (Castro 1989)",
                "ordem": 1,
            },
            {
                "nome": "Paraparesia espástica progressiva com espasticidade, fraqueza de MMII e hiperreflexia",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Mielopatia espástica progressiva de meses a anos; bexiga neurogênica, constipação, disfunção erétil; acomete adultos 40–60 anos",
                "valor_referencia": None,
                "fonte": "MS/PCDT HTLV 2020; ABN 2022",
                "ordem": 2,
            },
            {
                "nome": "RM de medula com hipersinal em T2 em região torácica e atrofia medular (fase tardia)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "RM medular pode ser normal na fase inicial; atrofia medular torácica é achado tardio; exclui outras causas compressivas",
                "valor_referencia": None,
                "fonte": "ABN 2022",
                "ordem": 3,
            },
            {
                "nome": "LCR com pleocitose mononuclear leve e bandas oligoclonais positivas",
                "categoria": "laboratorial",
                "tipo": "menor",
                "descricao": "LCR: células 5–50/mm³; proteínas levemente elevadas; bandas oligoclonais indicam síntese intratecal de anticorpos",
                "valor_referencia": "Pleocitose leve + bandas oligoclonais",
                "fonte": "MS/PCDT HTLV 2020",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
]
