CRITERIOS_PARASITARIAS = [
    {
        "patologia_nome": "Malária por Plasmodium falciparum",
        "criterios": [
            {
                "nome": "Gota espessa positiva para Plasmodium falciparum",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Método de referência; detecta espécies e estima parasitemia (parasitos/µL)",
                "valor_referencia": None,
                "fonte": "MS/CGDE – Guia de Tratamento da Malária no Brasil 2022",
                "ordem": 1,
            },
            {
                "nome": "Teste Rápido (TDR) positivo para P. falciparum (HRP-2)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "TDR baseado em HRP-2; positivo mesmo abaixo do limiar da microscopia",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 2,
            },
            {
                "nome": "Febre ou história de febre nas últimas 48 h + procedência de área endêmica",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Ciclo febril terçã (48 h); calafrio, sudorese, cefaleia intensa",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 3,
            },
            {
                "nome": "Critérios OMS/MS para malária grave (falciparum)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Presença de ≥1: prostração, alteração consciência, convulsões repetidas, dificuldade respiratória, coagulopatia, hipoglicemia <40 mg/dL, anemia grave Hb <7 g/dL, insuficiência renal, icterícia + outra disfunção, parasitemia ≥ 5%",
                "valor_referencia": None,
                "fonte": "WHO 2023 / MS/CGDE 2022",
                "ordem": 4,
            },
            {
                "nome": "Parasitemia quantificada por gota espessa",
                "categoria": "laboratorial",
                "tipo": "suporte",
                "descricao": "Utilizada para monitoramento de resposta terapêutica; D1, D3, D7",
                "valor_referencia": "Grave: ≥ 5% eritrócitos parasitados",
                "fonte": "MS/CGDE 2022",
                "ordem": 5,
            },
            {
                "nome": "PCR para Plasmodium (espécie-específica)",
                "categoria": "laboratorial",
                "tipo": "suporte",
                "descricao": "Confirma espécie em casos de microscopia duvidosa; detecta infecções mistas",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 6,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Malária por Plasmodium vivax",
        "criterios": [
            {
                "nome": "Gota espessa positiva para Plasmodium vivax",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Método padrão ouro; permite distinção morfológica de P. vivax (eritrócito aumentado, granulações Schüffner)",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 1,
            },
            {
                "nome": "TDR positivo para P. vivax (pLDH pan ou pLDH Pv)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Alternativa diagnóstica em localidades sem microscopia imediata",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 2,
            },
            {
                "nome": "Febre com ciclo terçã benigno + esplenomegalia + anemia",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Ciclo cada 48 h; recaídas por hipnozoítas hepáticos; anemia hemolítica",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 3,
            },
            {
                "nome": "Dosagem de G6PD antes do uso de primaquina",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Obrigatória para evitar hemólise por primaquina em deficientes de G6PD",
                "valor_referencia": "Normal: ≥ 30% da atividade mediana; deficiente: < 30%",
                "fonte": "MS/CGDE 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Malária por Plasmodium malariae",
        "criterios": [
            {
                "nome": "Gota espessa positiva para Plasmodium malariae",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Morfologia característica: eritrócito de tamanho normal, manchas Ziemann, trofozoíta em banda",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 1,
            },
            {
                "nome": "Febre quartan (ciclo de 72 h)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Ciclo febril a cada 72 h; esplenomegalia crônica; baixa parasitemia habitual",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 2,
            },
            {
                "nome": "Proteinúria / síndrome nefrótica em casos crônicos",
                "categoria": "laboratorial",
                "tipo": "suporte",
                "descricao": "Nefropatia quartã por deposição de imunocomplexos; verificar proteinúria de 24 h",
                "valor_referencia": None,
                "fonte": "MS/CGDE 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Leishmaniose Tegumentar Americana (LTA)",
        "criterios": [
            {
                "nome": "Úlcera cutânea de bordas elevadas (em moldura) com presença de Leishmania",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesão indolor, fundo granulomatoso, bordas infiltradas – aspecto clássico de LTA",
                "valor_referencia": None,
                "fonte": "MS – Manual de Vigilância da Leishmaniose Tegumentar 2017",
                "ordem": 1,
            },
            {
                "nome": "Intradermorreação de Montenegro (IDRM) positiva",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Leitura 48–72 h; considera-se positiva induração ≥ 5 mm",
                "valor_referencia": "≥ 5 mm de induração",
                "fonte": "MS 2017",
                "ordem": 2,
            },
            {
                "nome": "Demonstração do parasito (raspado, biópsia, imprint)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Exame direto de raspado de borda da lesão ou biópsia; pesquisa de amastigotas",
                "valor_referencia": None,
                "fonte": "MS 2017",
                "ordem": 3,
            },
            {
                "nome": "Cultura em meio NNN/LIT ou PCR positivos",
                "categoria": "microbiologico",
                "tipo": "suporte",
                "descricao": "PCR de biópsia ou swab com primers de kDNA; alta sensibilidade e especificidade",
                "valor_referencia": None,
                "fonte": "MS 2017",
                "ordem": 4,
            },
            {
                "nome": "Comprometimento de mucosas (mucosa nasal, oral, palato)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Forma mucosa (espúndia): destruição progressiva de septo, palato, faringe; associada à L. braziliensis",
                "valor_referencia": None,
                "fonte": "MS 2017",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Leishmaniose Visceral (Calazar)",
        "criterios": [
            {
                "nome": "Febre prolongada (> 2 semanas) + esplenomegalia + caquexia em área endêmica",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Tríade clássica; hepatoesplenomegalia proeminente; hipoalbuminemia; pancitopenia",
                "valor_referencia": None,
                "fonte": "MS – Manual de Vigilância da Leishmaniose Visceral 2014 (reimp. 2021)",
                "ordem": 1,
            },
            {
                "nome": "Sorologia positiva (RIFI ≥ 1:80 ou ELISA/TDR rK39)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "TDR rK39 (imunocromatografia) é o padrão atual do MS; sensibilidade ~93%, especificidade ~97%",
                "valor_referencia": "RIFI: título ≥ 1:80; TDR rK39: positivo",
                "fonte": "MS 2014/2021",
                "ordem": 2,
            },
            {
                "nome": "Parasitemia em aspirado de medula óssea, baço ou linfonodo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Pesquisa de amastigotas em medula óssea é o padrão ouro confirmativo; evitar punção esplênica sem estrutura cirúrgica",
                "valor_referencia": None,
                "fonte": "MS 2014/2021",
                "ordem": 3,
            },
            {
                "nome": "Pancitopenia + hipoalbuminemia + hiperglobulinemia",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Inversão albumina/globulina; anemia Hb < 8 g/dL; plaquetopenia; leucopenia",
                "valor_referencia": "Albumina < 3 g/dL; globulina > 4 g/dL",
                "fonte": "MS 2014/2021",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Doença de Chagas Aguda",
        "criterios": [
            {
                "nome": "Parasitemia direta positiva: pesquisa de Trypanosoma cruzi no sangue periférico",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Exame a fresco de gota espessa ou microhematócrito; trypomastigotas visíveis na fase aguda",
                "valor_referencia": None,
                "fonte": "MS – Consenso Brasileiro em Doença de Chagas 2015 / SVS 2023",
                "ordem": 1,
            },
            {
                "nome": "Sinal de Romaña (edema bipalpebral unilateral) ou Chagoma de inoculação",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Sinal de Romaña: porta de entrada conjuntival; chagoma: lesão cutânea na porta de entrada",
                "valor_referencia": None,
                "fonte": "MS 2015",
                "ordem": 2,
            },
            {
                "nome": "Febre prolongada (> 7 dias) + adenomegalia + hepatoesplenomegalia + síndrome de insuficiência cardíaca aguda",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Miocardite aguda chagásica pode cursar com ICC, pericardite, arritmias; meningoencefalite em imunodeprimidos",
                "valor_referencia": None,
                "fonte": "MS 2015",
                "ordem": 3,
            },
            {
                "nome": "Sorologia anti-T. cruzi positiva (2 testes de princípios distintos: ELISA + RIFI ou HAI)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Na fase aguda, soroconversão pode demorar 3–4 semanas; parasitemia direta é mais sensível na fase aguda",
                "valor_referencia": None,
                "fonte": "MS 2015",
                "ordem": 4,
            },
            {
                "nome": "Epidemiologia: residência em área endêmica, ingestão de alimentos contaminados (suco de açaí) ou transfusão",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "Transmissão oral por suco de açaí/cana representa novo padrão epidêmico no Brasil",
                "valor_referencia": None,
                "fonte": "MS 2015 / NOTA TÉCNICA SVS 2019",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Doença de Chagas Crônica",
        "criterios": [
            {
                "nome": "Sorologia positiva em 2 testes de princípios distintos (ELISA + RIFI ou HAI)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Critério diagnóstico padrão na fase crônica; ambos os testes devem ser positivos para confirmação",
                "valor_referencia": None,
                "fonte": "MS – Consenso Brasileiro Doença de Chagas 2015",
                "ordem": 1,
            },
            {
                "nome": "ECG com padrão chagásico",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "BRD + HBAE, extrassístoles ventriculares polimórficas, BAV de 2º/3º grau, ondas Q em região inferior e lateral",
                "valor_referencia": None,
                "fonte": "SBC – Diretriz de Doença de Chagas 2023",
                "ordem": 2,
            },
            {
                "nome": "Radiografia de tórax com cardiomegalia ou megaesôfago/megacólon",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "ICT > 0,5 indica cardiomegalia; megaesôfago graus I-IV (Rezende) na forma digestiva",
                "valor_referencia": "ICT > 0,5",
                "fonte": "MS 2015 / SBC 2023",
                "ordem": 3,
            },
            {
                "nome": "Ecocardiograma com disfunção sistólica e/ou aneurisma apical",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "FE < 40%, aneurisma apical do VE (típico), trombo mural; preditor de morte súbita",
                "valor_referencia": "FE < 40% = cardiomiopatia significativa",
                "fonte": "SBC 2023",
                "ordem": 4,
            },
            {
                "nome": "Estadiamento clínico de Kuschnir e estratificação de Rassi",
                "categoria": "escore",
                "tipo": "suporte",
                "descricao": "Kuschnir I–IV por critérios clínicos/ECG/ECO; Rassi score prediz mortalidade em 10 anos",
                "valor_referencia": None,
                "fonte": "SBC 2023",
                "ordem": 5,
            },
        ],
        "escores": [
            {
                "nome_escore": "Rassi Score (Chagas)",
                "descricao": "6 variáveis: classe NYHA III/IV (+5), cardiomegalia ao Rx (+5), disfunção VE ao eco (+3), TVNS ao Holter (+3), alteração de ST-T no ECG (+3), sexo masculino (+2)",
                "interpretacao": "Baixo risco 0-6: mortalidade 10% em 10 anos; Intermediário 7-11: 44%; Alto ≥12: 84%",
                "fonte": "SBC 2023 / Rassi Jr A, NEJM 2006",
                "ordem": 1,
            },
        ],
    },
    {
        "patologia_nome": "Toxoplasmose em Imunocompetentes",
        "criterios": [
            {
                "nome": "Sorologia IgG e IgM anti-Toxoplasma gondii positiva",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "IgM positiva indica infecção recente (< 6 meses); IgG avidity alta sugere infecção > 3–4 meses",
                "valor_referencia": "IgM+/IgG+: primoinfecção; IgG+/IgM-: infecção passada",
                "fonte": "MS – Protocolo de Toxoplasmose Gestacional 2022",
                "ordem": 1,
            },
            {
                "nome": "Linfadenomegalia cervical/occipital + febrícula + fadiga",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Quadro semelhante à mononucleose; maioria assintomática; linfadenite occipital é sugestiva",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Toxoplasmose em Imunocomprometidos (HIV/AIDS)",
        "criterios": [
            {
                "nome": "Lesão focal cerebral com realce em anel à TC ou RM em paciente com HIV/CD4 < 100",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "TC com contraste: lesão(ões) hipodensas com realce anelar, edema perilesional; RM é mais sensível",
                "valor_referencia": "CD4 < 100 células/µL aumenta muito o risco",
                "fonte": "MS – PCDT Adulto HIV 2018 / SBPT 2021",
                "ordem": 1,
            },
            {
                "nome": "IgG anti-Toxoplasma positiva (> 95% dos casos de encefalite toxoplásmica)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "IgG negativa torna o diagnóstico menos provável; IgM geralmente negativa na reativação",
                "valor_referencia": "IgM geralmente ausente na reativação",
                "fonte": "MS PCDT 2018",
                "ordem": 2,
            },
            {
                "nome": "Resposta clínica e radiológica ao tratamento empírico em 14 dias",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Resposta terapêutica com pirimetamina+sulfadiazina confirma diagnóstico presuntivo; ausência indica biópsia",
                "valor_referencia": "Melhora clínica e redução das lesões em 14 dias",
                "fonte": "MS PCDT 2018",
                "ordem": 3,
            },
            {
                "nome": "PCR para Toxoplasma no LCR (quando biópsia não disponível)",
                "categoria": "microbiologico",
                "tipo": "suporte",
                "descricao": "Sensibilidade 50–60% no LCR; especificidade > 95%; útil quando diagnóstico diferencial inclui linfoma primário do SNC",
                "valor_referencia": None,
                "fonte": "MS PCDT 2018",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Toxoplasmose Congênita",
        "criterios": [
            {
                "nome": "Sorologia materna: IgG+/IgM+ ou IgG com baixa avidez na gestação",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "IgG avidez < 30% indica infecção recente (< 3–4 meses); indicação de tratamento gestacional e investigação fetal",
                "valor_referencia": "Avidez < 30%: provável infecção recente",
                "fonte": "MS – PCDT Toxoplasmose Gestacional e Congênita 2022",
                "ordem": 1,
            },
            {
                "nome": "PCR para T. gondii no líquido amniótico (amniocentese a partir de 18 semanas)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade 64–80%; especificidade > 99%; realizado 4+ semanas após infecção materna estimada",
                "valor_referencia": None,
                "fonte": "MS PCDT 2022",
                "ordem": 2,
            },
            {
                "nome": "Ultrassonografia obstétrica: hidrocefalia, calcificações intracranianas, ascite, espessamento placentário",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Achados sugestivos de toxoplasmose fetal grave; hidrocefalia e calcificações são os mais específicos",
                "valor_referencia": None,
                "fonte": "MS PCDT 2022",
                "ordem": 3,
            },
            {
                "nome": "IgM ou IgA anti-Toxoplasma no RN (sangue periférico ou LCR)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "IgM não atravessa a placenta; positividade indica síntese própria do neonato (infecção congênita); IgA é mais sensível que IgM no RN",
                "valor_referencia": None,
                "fonte": "MS PCDT 2022",
                "ordem": 4,
            },
            {
                "nome": "Tétrade de Sabin: coriorretinite, hidrocefalia, calcificações cerebrais, retardo neurológico",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Apresentação clínica clássica da toxoplasmose congênita grave",
                "valor_referencia": None,
                "fonte": "MS PCDT 2022",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Amebíase Intestinal",
        "criterios": [
            {
                "nome": "Exame parasitológico de fezes (EPF): cistos ou trofozoítos de Entamoeba histolytica",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "3 amostras em dias alternados aumenta sensibilidade; distinção de E. dispar requer teste antigênico ou PCR",
                "valor_referencia": None,
                "fonte": "MS – Guia de Vigilância em Saúde (5ª ed.) 2022",
                "ordem": 1,
            },
            {
                "nome": "Antígeno fecal Gal/GalNAc lectina de E. histolytica (ELISA fecal)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Distingue E. histolytica de E. dispar; sensibilidade ~95%, especificidade ~98%",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Diarreia sanguinolenta (disenteria amebiana) com muco, sem febre alta (diferente de Shigella)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Colite amebiana: dor abdominal, tenesmo, fezes com sangue e muco; cólica difusa",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
            {
                "nome": "Retossigmoidoscopia com úlceras em frasco de champanhe (flask-shaped)",
                "categoria": "imagem",
                "tipo": "suporte",
                "descricao": "Úlceras com colo estreito e base ampla na mucosa colônica; biópsia revela trofozoítos",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Abscesso Hepático Amebiano",
        "criterios": [
            {
                "nome": "Ultrassonografia ou TC de abdome: lesão cística/hipoecoica hepática (lobo direito)",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Lesão solitária hipoecoica, lobo direito em > 75% dos casos; 'pasta de anchovas' no conteúdo drenado",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / SBH",
                "ordem": 1,
            },
            {
                "nome": "Sorologia anti-Entamoeba histolytica positiva (ELISA ou HAI)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Positividade > 95% nos casos de abscesso hepático amebiano; persiste por anos",
                "valor_referencia": "HAI ≥ 1:128; ELISA IgG positivo",
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Febre + hepatomegalia dolorosa + dor no QSD/ombro direito",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Síndrome febril prolongada com leucocitose, VHS elevado; sem eosinofilia (tipicamente)",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
            {
                "nome": "Resposta terapêutica ao metronidazol em 72–96 h",
                "categoria": "clinico",
                "tipo": "suporte",
                "descricao": "Melhora clínica rápida após início de metronidazol (defervescência em 2–3 dias)",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Giardíase",
        "criterios": [
            {
                "nome": "EPF positivo para cistos ou trofozoítos de Giardia lamblia/intestinalis",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "3 amostras seriadas em dias alternados; sensibilidade de exame único ~50–70%; concentração de Faust/Ritchie aumenta sensibilidade",
                "valor_referencia": None,
                "fonte": "MS – GVS 5ª ed. 2022",
                "ordem": 1,
            },
            {
                "nome": "Antígeno fecal de Giardia (ELISA ou imunocromatografia)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade ~98%, especificidade ~97%; preferível ao EPF para triagem única",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Diarreia gordurosa (esteatorreia), flatulência, distensão abdominal sem sangue ou muco",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Síndrome de má absorção; fezes pastosas, pálidas, flutuantes; anorexia; perda de peso; mais grave em imunodeprimidos",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Tricomoníase",
        "criterios": [
            {
                "nome": "Microscopia direta a fresco do corrimento vaginal: trofozoítos móveis de Trichomonas vaginalis",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade ~60–70%; especificidade alta quando positivo; trofozoítos piriformes com flagelos",
                "valor_referencia": None,
                "fonte": "MS – Protocolo Clínico IST 2022 (PCDT DST/Aids)",
                "ordem": 1,
            },
            {
                "nome": "NAAT (PCR/TMA) para T. vaginalis em amostra vaginal ou uretral",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Método mais sensível (> 95%); padrão recomendado quando disponível",
                "valor_referencia": None,
                "fonte": "MS PCDT IST 2022",
                "ordem": 2,
            },
            {
                "nome": "pH vaginal > 4,5 + corrimento amarelo-esverdeado espumoso + colpite em framboesa",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Corrimento abundante, fétido; eritema vaginal; colpite macular ('framboesa') ao espéculo",
                "valor_referencia": "pH > 4,5",
                "fonte": "MS PCDT IST 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Criptosporidiose",
        "criterios": [
            {
                "nome": "EPF com coloração de Ziehl-Neelsen modificada (ZN): oocistos de Cryptosporidium spp.",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Oocistos ácido-resistentes, 4–6 µm; 3 amostras em dias alternados; técnica de concentração de Sheather",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Antígeno fecal de Cryptosporidium (ELISA ou imunocromatografia)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade ~98%; padrão preferencial ao EPF isolado",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Diarreia aquosa profusa autolimitada (imunocompetente) ou grave crônica (CD4 < 50)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Em HIV: diarreia coleriformes 3–10 L/dia; caquexia; colangiopatia criptosporídica",
                "valor_referencia": "CD4 < 50: doença grave, crônica",
                "fonte": "MS 2022 / PCDT HIV 2018",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Ascaridíase",
        "criterios": [
            {
                "nome": "EPF positivo para ovos de Ascaris lumbricoides (método de Lutz/HPJ ou Willis)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Ovos cortical mamilonada (ovos fecundados) ou descorticados; carga parasitária avaliada por Kato-Katz",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Eliminação de vermes adultos pelas fezes ou visualização endoscópica/cirúrgica",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Confirmação direta do parasito adulto",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Síndrome de Löffler (fase larvária): eosinofilia + infiltrado pulmonar migratório + tosse seca",
                "categoria": "clinico",
                "tipo": "suporte",
                "descricao": "Tosse, hemoptise leve, febre baixa; infiltrado pulmonar transitório à radiografia; eosinofilia > 1.500/µL",
                "valor_referencia": "Eosinofilia > 1.500/µL",
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Ancilostomíase / Necatoríase (Hookworm)",
        "criterios": [
            {
                "nome": "EPF positivo para ovos de Ancylostoma duodenale ou Necator americanus (Kato-Katz)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Ovos ovalados de casca fina; carga parasitária por Kato-Katz (ovos por grama de fezes)",
                "valor_referencia": "Infecção leve: < 2.000 opg; moderada: 2.000–3.999; grave: ≥ 4.000",
                "fonte": "MS – GVS 2022 / OMS",
                "ordem": 1,
            },
            {
                "nome": "Anemia ferropriva microcítica + hipoalbuminemia em área endêmica",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Perda de sangue intestinal crônica; Hb < 11 g/dL com hipoalbuminemia em infecções intensas",
                "valor_referencia": "Hb < 11 g/dL; ferritina baixa",
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Dermatite larvária (ground itch): prurido no local de penetração percutânea",
                "categoria": "clinico",
                "tipo": "suporte",
                "descricao": "Erupção papulovesicular pruriginosa nos pés; síndrome de Löffler possível durante migração larval",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Tricuríase",
        "criterios": [
            {
                "nome": "EPF positivo para ovos de Trichuris trichiura (Lutz/HPJ ou Kato-Katz)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Ovos em forma de limão/barril com tampões polares hialinos; carga parasitária por Kato-Katz",
                "valor_referencia": "Grave: > 10.000 ovos/g fezes",
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Diarreia mucossanguinolenta + prolapso retal (casos graves em crianças)",
                "categoria": "clinico",
                "tipo": "suporte",
                "descricao": "Síndrome disenteriforme em alta carga parasitária; prolapso retal recorrente em crianças desnutridas",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Estrongiloidíase",
        "criterios": [
            {
                "nome": "EPF: larvas rabditoides de Strongyloides stercoralis (método de Rugai/Baermann-Moraes)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Método de Baermann é o padrão; 3 amostras seriadas; cultura em placa de ágar aumenta sensibilidade",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "ELISA IgG anti-Strongyloides: sensibilidade ~90%",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Útil em infecções de baixa carga (EPF frequentemente negativo); confirmar positivo com EPF",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Eosinofilia periférica + dor epigástrica + urticária larva currens",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Larva currens: urticária serpiginosa perianal de progressão rápida (2–5 cm/h); eosinofilia > 500/µL",
                "valor_referencia": "Eosinofilia > 500/µL",
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Estrongiloidíase com Síndrome de Hiperinfecção",
        "criterios": [
            {
                "nome": "Larvas fibrariformes (L3) em fezes, escarro, LCR ou outros sítios extraintestinais",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Migração larval acelerada em imunodeprimidos (corticoides, HTLV-1, transplante); carga larval maciça",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / SBPT 2021",
                "ordem": 1,
            },
            {
                "nome": "Imunossupressão (corticoterapia, HTLV-1, transplante, desnutrição grave) como fator predisponente",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Corticoides são o principal fator de risco para hiperinfecção; rastrear Strongyloides antes de iniciar imunossupressores",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Sepse por gram-negativos entéricos (E. coli, Klebsiella) simultânea",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Bactérias entéricas carreadas pelas larvas perfuram a mucosa intestinal causando bacteremia/sepse",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Enterobíase (Oxiuríase)",
        "criterios": [
            {
                "nome": "Teste da fita adesiva (scotch tape test) com ovos de Enterobius vermicularis",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Coleta perianal ao amanhecer (antes de banho/evacuação) em 3 dias consecutivos; ovos assimétricos achatados",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Prurido anal noturno intenso (pruido perianal noturno)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Fêmea migra à região perianal à noite para oviposição; prurido interfere no sono; irritabilidade em crianças",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Teníase",
        "criterios": [
            {
                "nome": "EPF com proglotes ou ovos de Taenia spp. (T. solium ou T. saginata)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Proglotes grávidos nas fezes; ovos esféricos com embrião hexacanto; distinção de espécie requer morfologia de proglote ou PCR",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Eliminação espontânea de proglotes nas fezes",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Proglotes de T. saginata são móveis; T. solium são menos ativos; anamnese epidemiológica (carne suína/bovina malpassada)",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Neurocisticercose",
        "criterios": [
            {
                "nome": "Critérios Del Brutto revisados 2017 (diagnóstico absoluto, maior ou menor)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Diagnóstico absoluto: achado histopatológico OU cisto com escólex em TC/RM OU lesões diagnósticas na fundoscopia",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / Del Brutto 2017",
                "ordem": 1,
            },
            {
                "nome": "TC de crânio: cistos com escólex (ponto hiperdensopor dentro de cisto hipodensso) ou calcificações",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Cistos em diferentes estágios evolutivos (vesicular, coloidal, nodular, calcificado); pode haver hidrocefalia",
                "valor_referencia": None,
                "fonte": "MS 2022 / ABN",
                "ordem": 2,
            },
            {
                "nome": "RM de crânio com contraste (mais sensível que TC para cistos pequenos e locais atípicos)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Superior à TC para cistos subaracnóideos, ventriculares e da fossa posterior; padrão ouro para estadiamento",
                "valor_referencia": None,
                "fonte": "ABN – Guideline Neurocisticercose 2019",
                "ordem": 3,
            },
            {
                "nome": "Sorologia: EITB (enzyme-linked immunoelectrotransfer blot) em soro ou LCR",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "EITB: sensibilidade 98% para múltiplos cistos; menor sensibilidade para cisto único ou calcificado; especificidade > 99%",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 4,
            },
            {
                "nome": "Epilepsia de início tardio + leucócitos e eosinófilos no LCR + hipertensão intracraniana",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Epilepsia é a manifestação mais comum (50–80%); cefaleia crônica, hidrocefalia, déficit focal",
                "valor_referencia": None,
                "fonte": "ABN 2019",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Esquistossomose Mansoni",
        "criterios": [
            {
                "nome": "EPF com ovos de Schistosoma mansoni (método de Kato-Katz)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Ovos com espículo lateral; Kato-Katz: 2 lâminas de 2 amostras; carga parasitária (ovos/grama)",
                "valor_referencia": "Infecção leve: < 100 opg; moderada: 100–399; grave: ≥ 400",
                "fonte": "MS – PCTVE Esquistossomose 2014 / GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Ultrassonografia hepática (protocolo de Niamey/Cairo): fibrose periportal",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Fibrose periportal ('cabeça de peixe' ou 'imagem em tela') é patognomônica da forma crônica hepatoesplênica",
                "valor_referencia": None,
                "fonte": "MS 2014 / PAHO/WHO Niamey Protocol",
                "ordem": 2,
            },
            {
                "nome": "Biópsia retal ou hepática com granuloma esquistossomótico",
                "categoria": "histopatologico",
                "tipo": "suporte",
                "descricao": "Granuloma periovo com eosinófilos e células gigantes; padrão ouro histopatológico",
                "valor_referencia": None,
                "fonte": "MS 2014",
                "ordem": 3,
            },
            {
                "nome": "Procedência de área endêmica + contato com água de rio/lago infestada",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Regiões endêmicas: MG, BA, PE, AL, SE, RN, PB, CE, MA, GO, ES; infecção percutânea por cercárias",
                "valor_referencia": None,
                "fonte": "MS 2014",
                "ordem": 4,
            },
            {
                "nome": "Sorologia ELISA anti-Schistosoma (fase aguda/baixa carga)",
                "categoria": "laboratorial",
                "tipo": "suporte",
                "descricao": "Útil em fase aguda (antes da positividade do EPF) e em infecções de baixa carga",
                "valor_referencia": None,
                "fonte": "MS 2014",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Filariose Linfática (Bancroftose)",
        "criterios": [
            {
                "nome": "Microfilaremia noturna: pesquisa de Wuchereria bancrofti em sangue periférico (22h–02h)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Coleta obrigatória à noite (periodicidade noturna); gota espessa corada com Giemsa; microfilária com bainha",
                "valor_referencia": None,
                "fonte": "MS – PCTVE Filariose 2009 / GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "TDR imunocromatográfico (Og4C3 antigenemia) para Wuchereria bancrofti",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Detecta antígeno circulante; sensibilidade > 96% em adultos microfilarêmicos; pode ser coletado a qualquer hora",
                "valor_referencia": None,
                "fonte": "MS 2009 / WHO",
                "ordem": 2,
            },
            {
                "nome": "Linfedema progressivo de membros inferiores + elefantíase + hidrocele",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Manifestações crônicas por obstrução linfática; elefantíase = linfedema crônico grave; hidrocele filariásica no homem",
                "valor_referencia": None,
                "fonte": "MS 2009",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Toxocaríase (Larva Migrans Visceral)",
        "criterios": [
            {
                "nome": "ELISA IgG anti-Toxocara (antígeno de larvas TES) positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade ~78%; especificidade ~92%; título > 1:32 sugere infecção ativa; reações cruzadas com Ascaris",
                "valor_referencia": "Título ELISA > 1:32 (laboratorial)",
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "Eosinofilia intensa (> 30%) + hepatomegalia + pneumonite + febre",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Larva migrans visceral: larvas de Toxocara canis/cati migram sem completar ciclo em humanos",
                "valor_referencia": "Eosinofilia > 30% (> 3.000/µL)",
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Lesão ocular ao fundoscópio (granuloma retiniano) — Larva Migrans Ocular",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Toxocaríase ocular: granuloma no polo posterior, perda visual unilateral, estrabismo; em crianças 5–10 anos",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Larva Migrans Cutânea",
        "criterios": [
            {
                "nome": "Diagnóstico clínico: lesão serpiginosa pruriginosa de progressão lenta (1–2 cm/dia)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Túnel eritematoso, linear e serpiginoso na derme; prurido intenso; causado por larvas de Ancylostoma braziliense/caninum",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / SBD",
                "ordem": 1,
            },
            {
                "nome": "Exposição a areia/solo contaminado com fezes de cães/gatos",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Contato com praias, praças, parques com fezes de animais; pés e nádegas são os sítios mais acometidos",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Hidatidose / Equinococose Cística",
        "criterios": [
            {
                "nome": "Ultrassonografia abdominal: cisto hepático com membrana interna (pericisto) — classificação OMS CE 1–5",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Estadiamento por US: CE1 (ativo), CE2 (multivesicular), CE3a/3b (transição), CE4/5 (inativo); fígado > 70%",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / WHO-IWGE 2019",
                "ordem": 1,
            },
            {
                "nome": "Sorologia: ELISA + HAI (arco 5 em imunodifusão/arco de Caproni = alta especificidade)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Falso negativos em cistos calcificados; arco 5 é patognomônico; 40% de falso negativos em cistos pulmonares",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "TC ou RM: detalhamento do cisto (vesículas filhas, calcificação, localização)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "TC superior para avaliação de cistos hepáticos e pulmonares; RM para localização biliar e vascular",
                "valor_referencia": None,
                "fonte": "WHO-IWGE 2019",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Oncocercose",
        "criterios": [
            {
                "nome": "Biópsia de pele (skin snip) com microfilárias de Onchocerca volvulus",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Biópsia sem sangue de crista ilíaca ou escápula; microfilária migra ao meio líquido em 30 min–24 h",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / WHO",
                "ordem": 1,
            },
            {
                "nome": "Nódulos subcutâneos (oncocercomas) palpáveis contendo vermes adultos",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Nódulos firmes, indolores, sobre prominências ósseas; biópsia revela verme adulto",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "Exame oftalmológico com lâmpada de fenda: microfilárias na câmara anterior",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Oncocercose ocular ('cegueira dos rios'): queratite esclerosante, uveíte, atrofia do nervo óptico",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Fasciolíase",
        "criterios": [
            {
                "nome": "EPF com ovos de Fasciola hepatica (Lutz/HPJ ou Kato-Katz)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Ovos grandes (130–150 µm), operculados, elipsoidal; coleta de 3 amostras; negatividade na fase aguda (pré-patente)",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022",
                "ordem": 1,
            },
            {
                "nome": "ELISA anti-Fasciola (antígeno de excreção/secreção) positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Útil na fase aguda (antes da patência); sensibilidade > 95%; confirmar com EPF quando possível",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
            {
                "nome": "TC/RM: lesões hepáticas hipodensas com trajeto tubular ('tunel')",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Lesões hepáticas periféricas com trajeto linear (migração da larva); eosinofilia intensa na fase aguda",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Pediculose do Couro Cabeludo",
        "criterios": [
            {
                "nome": "Visualização de piolhos adultos (Pediculus humanus capitis) ou lêndeas viáveis no cabelo",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Diagnóstico clínico direto; pente fino úmido aumenta sensibilidade; lêndeas < 1 cm do couro cabeludo são viáveis",
                "valor_referencia": "Lêndeas viáveis: < 1 cm do couro cabeludo",
                "fonte": "MS – GVS 2022 / SBD",
                "ordem": 1,
            },
            {
                "nome": "Prurido occipital/retroauricular intenso + escoriações + infecção secundária",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Prurido por reação alérgica à saliva do ectoparasito; linfadenomegalia cervical occipital pode ocorrer",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Escabiose (Sarna)",
        "criterios": [
            {
                "nome": "Visualização de galerias/túneis lineares + ácaro Sarcoptes scabiei ao dermatoscópio ou raspado",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Dermatoscopia: sinal delta-wing/jet (cabeça do ácaro + túnel); raspado de galeria ao microscópio confirma o ácaro",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / SBD",
                "ordem": 1,
            },
            {
                "nome": "Prurido noturno intenso com distribuição típica (espaços interdigitais, pulsos, genitais, axilas)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Prurido piora à noite; lesões pápulo-vesiculares, escoriações; distribuição característica",
                "valor_referencia": None,
                "fonte": "MS 2022 / SBD",
                "ordem": 2,
            },
            {
                "nome": "Contexto epidêmico: múltiplos membros da família/instituição com prurido simultâneo",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Alta transmissibilidade por contato íntimo; rastrear e tratar contactantes",
                "valor_referencia": None,
                "fonte": "MS 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Miiase",
        "criterios": [
            {
                "nome": "Visualização de larvas (vermes) de mosca em lesão cutânea ou cavidade corporal",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Diagnóstico clínico direto; identificação da larva pela morfologia (espiráculos posteriores, espinhos) determina a espécie",
                "valor_referencia": None,
                "fonte": "MS – GVS 2022 / SBD",
                "ordem": 1,
            },
            {
                "nome": "Tipos: furunculoide (Dermatobia hominis), cavitária (Cochliomyia hominivorax), migratória",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Miiase furunculoide: nódulo com orifício central e larva; cavitária: lesões odorosas necróticas; migratória: larva migra sob pele",
                "valor_referencia": None,
                "fonte": "SBD / MS 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
]
