"""
Dados de parasitos e antiparasitários — fontes oficiais brasileiras.
Fontes: PCDT-MS, SVS/GVS 5ª ed. 2022, SBMT, SBI, ANVISA.
"""

FONTES_PARASITARIAS = [
    # (sigla, nome, orgao, tipo, url, ano, descricao)
    ("PCDT-MALARIA",    "Protocolo Clínico e Diretrizes Terapêuticas para Malária",
     "Ministério da Saúde / SVS", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/malaria/pcdt-malaria-2022.pdf",
     2022, "PCDT Malária MS 2022 — esquemas por espécie, malária grave, profilaxia, populações especiais"),
    ("PCDT-LEISH-TEG",  "Protocolo Clínico e Diretrizes Terapêuticas para Leishmaniose Tegumentar Americana",
     "Ministério da Saúde", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/leishmaniose/pcdt-lta-2022.pdf",
     2022, "PCDT LTA MS 2022 — antimoniato, anfotericina, miltefosina, critérios de cura"),
    ("PCDT-LEISH-VIS",  "Protocolo Clínico e Diretrizes Terapêuticas para Leishmaniose Visceral",
     "Ministério da Saúde", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/leishmaniose/pcdt-lv-2022.pdf",
     2022, "PCDT LV MS 2022 — anfotericina B lipossomal como 1ª linha em grupos especiais; critérios de internação"),
    ("PCDT-CHAGAS",     "Protocolo Clínico e Diretrizes Terapêuticas para Doença de Chagas",
     "Ministério da Saúde", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/chagas/pcdt-chagas-2022.pdf",
     2022, "PCDT Chagas MS 2022 — benznidazol, nifurtimox, indicações de tratamento etiológico por fase"),
    ("PCDT-ESQUIS",     "Protocolo Clínico e Diretrizes Terapêuticas para Esquistossomose",
     "Ministério da Saúde / SVS", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/esquistossomose/pcdt-esquistossomose-2022.pdf",
     2022, "PCDT Esquistossomose MS 2022 — praziquantel dose única, critérios de retratamento, forma hepatoesplênica"),
    ("SVS-PARASIT",     "Guia de Vigilância em Saúde — Parasitoses",
     "Ministério da Saúde / SVS", "Diretriz",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/guia-de-vigilancia-em-saude",
     2022, "GVS 5ª ed. 2022 — capítulos de parasitoses: geo-helmintos, protozooses, ectoparasitoses, vigilância epidemiológica"),
    ("PCDT-NCC",        "Protocolo Clínico e Diretrizes Terapêuticas para Neurocisticercose",
     "Ministério da Saúde", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/neurocisticercose/pcdt-ncc-2022.pdf",
     2022, "PCDT NCC MS 2022 — albendazol + dexametasona, praziquantel, indicações cirúrgicas, seguimento"),
    ("PCDT-FILARIA",    "Protocolo Clínico e Diretrizes Terapêuticas para Filariose Linfática",
     "Ministério da Saúde / SVS", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/filariose/pcdt-filariose-2022.pdf",
     2022, "PCDT Filariose Linfática MS 2022 — DEC, ivermectina, programa de eliminação, manejo do linfedema"),
    ("SBMT-PARASIT",    "Diretrizes de Parasitologia Clínica — Sociedade Brasileira de Medicina Tropical",
     "Sociedade Brasileira de Medicina Tropical", "Diretriz",
     "https://www.sbmt.org.br", 2022,
     "Diretrizes SBMT para parasitoses tropicais no Brasil: diagnóstico, tratamento e controle"),
    ("SBI-PARASIT",     "Diretrizes de Parasitoses — Sociedade Brasileira de Infectologia",
     "Sociedade Brasileira de Infectologia", "Diretriz",
     "https://www.infectologia.org.br", 2022,
     "Diretrizes SBI para parasitoses em imunocompetentes e imunocomprometidos"),
    ("ANVISA-PARASIT",  "Bulas e Notas Técnicas de Antiparasitários — ANVISA",
     "ANVISA", "Nota Técnica",
     "https://www.anvisa.gov.br/datavisa/fila_bula/index.asp", 2023,
     "Bulas ANVISA de antiparasitários registrados no Brasil e notas técnicas de farmacovigilância"),
    ("PCDT-TOXO",       "Protocolo Clínico e Diretrizes Terapêuticas para Toxoplasmose em HIV/AIDS",
     "Ministério da Saúde", "PCDT",
     "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/hiv-aids/pcdt-adultos-hiv-2022.pdf",
     2022, "PCDT HIV/AIDS MS 2022 — cap. toxoplasmose: sulfadiazina+pirimetamina, profilaxia primária e secundária"),
]

FAMILIAS_PARASITARIAS = [
    # (nome, reino, filo)
    # Protozoários
    ("Plasmodiidae",       "Protozoa", "Apicomplexa"),
    ("Trypanosomatidae",   "Protozoa", "Kinetoplastea"),
    ("Sarcocystidae",      "Protozoa", "Apicomplexa"),
    ("Entamoebidae",       "Protozoa", "Amoebozoa"),
    ("Hexamitidae",        "Protozoa", "Metamonada"),
    ("Trichomonadidae",    "Protozoa", "Parabasalia"),
    ("Cryptosporidiidae",  "Protozoa", "Apicomplexa"),
    # Nematoda
    ("Ascarididae",        "Helmintha", "Nematoda"),
    ("Ancylostomatidae",   "Helmintha", "Nematoda"),
    ("Trichuridae",        "Helmintha", "Nematoda"),
    ("Strongyloididae",    "Helmintha", "Nematoda"),
    ("Oxyuridae",          "Helmintha", "Nematoda"),
    ("Onchocercidae",      "Helmintha", "Nematoda"),
    ("Toxocaridae",        "Helmintha", "Nematoda"),
    # Trematoda
    ("Schistosomatidae",   "Helmintha", "Trematoda"),
    ("Fasciolidae",        "Helmintha", "Trematoda"),
    # Cestoda
    ("Taeniidae",          "Helmintha", "Cestoda"),
    ("Echinococcidae",     "Helmintha", "Cestoda"),
    # Ectoparasitos
    ("Pediculidae",        "Ectoparasita", "Arthropoda — Insecta"),
    ("Sarcoptidae",        "Ectoparasita", "Arthropoda — Arachnida"),
    ("Calliphoridae",      "Ectoparasita", "Arthropoda — Insecta"),
]

PARASITOS = [
    # (nome_cientifico, nome_comum, familia_nome, tipo, transmissao, reservatorio, distribuicao_br)
    # ── Protozoários ──────────────────────────────────────────
    ("Plasmodium falciparum",
     "Plasmodium falciparum (malária terçã maligna)",
     "Plasmodiidae", "protozoario",
     "Picada de fêmea de Anopheles spp. infectada",
     "Humanos (hospedeiro definitivo); Anopheles (hospedeiro intermediário)",
     "Amazônia Legal: AM, PA, RR, AC, RO, AP, TO; responsável por ~15% dos casos de malária no Brasil mas pela maioria das formas graves"),
    ("Plasmodium vivax",
     "Plasmodium vivax (malária terçã benigna)",
     "Plasmodiidae", "protozoario",
     "Picada de fêmea de Anopheles spp. infectada; transfusão sanguínea (rara)",
     "Humanos; Anopheles darlingi principal vetor no Brasil",
     "Amazônia Legal: AM, PA, RR, AC, RO, AP, TO, MA, MT; responsável por ~84% dos casos de malária no Brasil; hipnozoítas causam recidivas"),
    ("Plasmodium malariae",
     "Plasmodium malariae (malária quartã)",
     "Plasmodiidae", "protozoario",
     "Picada de Anopheles spp.; transfusão sanguínea",
     "Humanos; primatas não humanos (reservatório secundário)",
     "Amazônia Legal; focos residuais fora da Amazônia; responsável por ~1% dos casos; síndrome nefrótica quartã crônica"),
    ("Leishmania braziliensis",
     "Leishmania (Viannia) braziliensis — LTA",
     "Trypanosomatidae", "protozoario",
     "Picada de flebotomíneos (Lutzomyia spp.) infectados",
     "Roedores silvestres, marsupiais, edentados; humanos são hospedeiros acidentais",
     "Distribuição ampla no Brasil; principal agente de LTA mucosa; NE, Norte, CO, MG, ES, RJ, SP"),
    ("Leishmania amazonensis",
     "Leishmania (Leishmania) amazonensis — LTA difusa",
     "Trypanosomatidae", "protozoario",
     "Picada de Lutzomyia flaviscutellata e L. olmeca",
     "Roedores (Proechimys spp.) no ambiente florestal",
     "Floresta Amazônica e cerrado; associada à leishmaniose cutânea difusa anérgica; AM, PA, MA, BA"),
    ("Leishmania infantum (chagasi)",
     "Leishmania infantum (chagasi) — Leishmaniose Visceral",
     "Trypanosomatidae", "protozoario",
     "Picada de Lutzomyia longipalpis (principal vetor no Brasil)",
     "Cão doméstico (principal reservatório urbano); raposas (Cerdocyon thous) no ambiente silvestre",
     "Urbanização crescente; endêmica no NE, Norte, CO; expansão para SP, MG, MS, PR; surtos em capitais"),
    ("Trypanosoma cruzi",
     "Trypanosoma cruzi — Doença de Chagas",
     "Trypanosomatidae", "protozoario",
     "Contaminação por fezes de triatomíneos (barbeiro); transmissão oral (açaí, caldo de cana); vertical; transfusional; transplante",
     "Triatomíneos (Triatoma infestans, Rhodnius prolixus, Panstrongylus megistus); gambás; tatus; cão",
     "Endêmica no NE, Norte, MG, GO; surtos orais crescentes no Norte (AM, PA); 2-3 milhões de infectados no Brasil"),
    ("Toxoplasma gondii",
     "Toxoplasma gondii — Toxoplasmose",
     "Sarcocystidae", "protozoario",
     "Ingestão de oocistos em alimentos/água; ingestão de cistos em carne crua/malcozida; transmissão vertical; transfusão/transplante",
     "Gatos (hospedeiro definitivo — excretam oocistos); todos os animais homeotérmicos (hospedeiros intermediários)",
     "Soroprevalência 60-80% na população adulta brasileira; toxoplasmose congênita ~3.000 casos/ano; toxoplasmose ocular frequente no Sul"),
    ("Entamoeba histolytica",
     "Entamoeba histolytica — Amebíase",
     "Entamoebidae", "protozoario",
     "Fecal-oral: água e alimentos contaminados por cistos; contato direto; sexual (MSM)",
     "Humanos (único reservatório significativo)",
     "Regiões com saneamento precário: Norte, NE; surtos esporádicos em populações vulneráveis; amebíase invasiva em MSM"),
    ("Giardia lamblia (intestinalis/duodenalis)",
     "Giardia lamblia — Giardíase",
     "Hexamitidae", "protozoario",
     "Fecal-oral: água (resistente ao cloro), alimentos, contato pessoa-a-pessoa; zoonótica (cão, castor)",
     "Humanos; cão, gato, castor (reservatórios zoonóticos)",
     "Distribuição nacional; prevalência 10-20% em crianças; alta em creches e pré-escolas; diarreia do viajante"),
    ("Trichomonas vaginalis",
     "Trichomonas vaginalis — Tricomoníase",
     "Trichomonadidae", "protozoario",
     "Sexual (IST); contato direto com secreções genitais; fômites (rara)",
     "Humanos (único hospedeiro natural)",
     "Distribuição nacional; prevalência 2-8% em mulheres sexualmente ativas; subnotificada; associada a outras ISTs"),
    ("Cryptosporidium parvum",
     "Cryptosporidium parvum — Criptosporidiose",
     "Cryptosporidiidae", "protozoario",
     "Fecal-oral: água (resistente ao cloro e ozônio); alimentos; contato direto; zoonótica",
     "Humanos, bovinos (principal reservatório zoonótico), ovinos, caprinos",
     "Distribuição nacional; surtos hídricos documentados; prevalência 5-10% em crianças hospitalizadas com diarreia; grave em HIV/AIDS"),
    # ── Nematoda ─────────────────────────────────────────────
    ("Ascaris lumbricoides",
     "Ascaris lumbricoides — Ascaridíase",
     "Ascarididae", "helminto_nematoda",
     "Ingestão de ovos embrionados em solo/alimentos contaminados; fecal-oral",
     "Humanos (único hospedeiro definitivo)",
     "Endêmica no Norte e NE; prevalência 30-50% em crianças de zonas rurais; geohelmintose mais prevalente no Brasil"),
    ("Necator americanus",
     "Necator americanus — Ancilostomíase/Necatoríase",
     "Ancylostomatidae", "helminto_nematoda",
     "Penetração cutânea de larvas filarióides de solo contaminado; menos frequente: oral",
     "Humanos (hospedeiro definitivo)",
     "Predominante sobre A. duodenale no Brasil; endêmico no Norte, NE e CO; causa anemia ferropriva crônica em zonas rurais"),
    ("Ancylostoma duodenale",
     "Ancylostoma duodenale — Ancilostomíase",
     "Ancylostomatidae", "helminto_nematoda",
     "Penetração cutânea de larvas; ingestão oral de larvas (via menos comum no Brasil)",
     "Humanos (hospedeiro definitivo)",
     "Coexiste com N. americanus no Brasil; maior em regiões mais frias (Sul, SE); provoca maior perda de sangue que Necator"),
    ("Trichuris trichiura",
     "Trichuris trichiura — Tricuríase",
     "Trichuridae", "helminto_nematoda",
     "Ingestão de ovos embrionados em solo contaminado; fecal-oral",
     "Humanos (hospedeiro definitivo)",
     "Coinfecção frequente com Ascaris; Norte e NE; solos úmidos e sombreados; geofagia como fator de risco"),
    ("Strongyloides stercoralis",
     "Strongyloides stercoralis — Estrongiloidíase",
     "Strongyloididae", "helminto_nematoda",
     "Penetração cutânea de larvas; autoinfecção endógena (via intestinal); raramente oral",
     "Humanos (hospedeiro definitivo); cão (reservatório secundário — S. stercoralis variante canis)",
     "Distribuição nacional; endemismo no Norte, NE, MG; capacidade de autoinfecção permite persistência por décadas; hiperinfecção letal em imunossuprimidos"),
    ("Enterobius vermicularis",
     "Enterobius vermicularis — Enterobíase / Oxiuríase",
     "Oxyuridae", "helminto_nematoda",
     "Fecal-oral: ovos em fômites, roupas de cama, unhas; autoinfecção; inalação de ovos",
     "Humanos (único hospedeiro definitivo)",
     "Distribuição universal; mais prevalente em crianças 5-14 anos; toda faixa socioeconômica; infecção familiar e em coletividades"),
    ("Wuchereria bancrofti",
     "Wuchereria bancrofti — Filariose Linfática",
     "Onchocercidae", "helminto_nematoda",
     "Picada de Culex quinquefasciatus (pernilongo-comum) infectado com microfilárias",
     "Humanos (único hospedeiro definitivo); Culex como vetor",
     "Foco endêmico restrito: Grande Recife (PE) e Grande Maceió (AL); programa de eliminação MS; prevalência histórica 5-10% em áreas endêmicas"),
    ("Toxocara canis",
     "Toxocara canis — Toxocaríase / Larva Migrans Visceral",
     "Toxocaridae", "helminto_nematoda",
     "Ingestão de ovos em solo contaminado por fezes de cão (geofagia); ingestão de hospedeiros paratênicos (fígado crú de frango)",
     "Cão e gato (hospedeiros definitivos); roedores (hospedeiros paratênicos)",
     "Distribuição nacional; alta soroprevalência (20-40%) em crianças com pica/geofagia; toxocaríase ocular pode causar cegueira unilateral"),
    ("Ancylostoma braziliense",
     "Ancylostoma braziliense — Larva Migrans Cutânea",
     "Ancylostomatidae", "helminto_nematoda",
     "Penetração de larvas filarióides de cão/gato em pele de humanos em contato com solo/areia contaminada",
     "Cão e gato (hospedeiros definitivos) — larva não completa ciclo em humanos",
     "Praias e parques de areia no litoral brasileiro; verão; crianças e frequentadores de praias; regiões Sudeste e Sul principalmente"),
    ("Onchocerca volvulus",
     "Onchocerca volvulus — Oncocercose (Cegueira dos Rios)",
     "Onchocercidae", "helminto_nematoda",
     "Picada de Simulium spp. (borrachudo) infectado com microfilárias",
     "Humanos (único hospedeiro definitivo); Simulium damnosum e S. guianense como vetores",
     "Foco endêmico Yanomami (RR e AM); ~30.000 pessoas em risco; programa de eliminação com ivermectina anual — próximo à eliminação"),
    # ── Trematoda ────────────────────────────────────────────
    ("Schistosoma mansoni",
     "Schistosoma mansoni — Esquistossomose",
     "Schistosomatidae", "helminto_trematoda",
     "Penetração de cercárias na pele/mucosas em contato com água doce contaminada por Biomphalaria spp.",
     "Humanos; caramujos do gênero Biomphalaria (hospedeiro intermediário)",
     "19 estados endêmicos; NE (BA, PE, AL, SE, PB, RN, CE), MG, ES, RJ, SP; 2-4 milhões de infectados; urbanização de favelas contribui para manutenção"),
    ("Fasciola hepatica",
     "Fasciola hepatica — Fasciolíase",
     "Fasciolidae", "helminto_trematoda",
     "Ingestão de metacercárias em vegetais aquáticos crus (agrião, alface-d'água) ou água contaminada",
     "Bovinos, ovinos (hospedeiros definitivos principais); Lymnaea viatrix e L. columella (caramujos intermediários)",
     "RS, SC, MG, SP, BA, PE; focos em várzeas úmidas e pastagens alagadas; casos esporádicos em todo o Brasil"),
    # ── Cestoda ───────────────────────────────────────────────
    ("Taenia solium",
     "Taenia solium — Teníase / Cisticercose",
     "Taeniidae", "helminto_cestoda",
     "Ingestão de carne suína com cisticercos (teníase); ingestão de ovos de T. solium em fezes humanas (cisticercose/NCC)",
     "Humanos (hospedeiro definitivo para a tênia adulta); suínos (hospedeiro intermediário)",
     "Norte, NE, MG, GO, SP; suinocultura sem inspeção sanitária; teníase e NCC associadas a baixa escolaridade e saneamento precário"),
    ("Taenia saginata",
     "Taenia saginata — Teníase bovina",
     "Taeniidae", "helminto_cestoda",
     "Ingestão de carne bovina com cisticercos malcozida ou crua",
     "Humanos (hospedeiro definitivo); bovinos (hospedeiro intermediário)",
     "Distribuição nacional onde há consumo de carne crua/malcozida; não causa cisticercose em humanos; vigilância sanitária da carne bovina"),
    ("Echinococcus granulosus",
     "Echinococcus granulosus — Hidatidose / Equinococose Cística",
     "Echinococcidae", "helminto_cestoda",
     "Ingestão de ovos de E. granulosus em alimentos/água contaminados por fezes de cão",
     "Cão doméstico (hospedeiro definitivo); ovinos (hospedeiro intermediário principal); humanos como hospedeiro acidental",
     "RS (principal), SC, PR, UR/MG; associada à pecuária ovina e criação de cães; doença notificável; cisto hepático em 60-70% dos casos"),
    # ── Ectoparasitos ─────────────────────────────────────────
    ("Pediculus humanus capitis",
     "Pediculus humanus capitis — Pediculose do Couro Cabeludo",
     "Pediculidae", "ectoparasito",
     "Contato direto cabeça a cabeça; fômites (pentes, chapéus, travesseiros) — menos frequente",
     "Humanos (parasitismo obrigatório)",
     "Distribuição nacional; prevalência 10-40% em escolares; toda faixa socioeconômica; epidemias em creches e escolas"),
    ("Sarcoptes scabiei",
     "Sarcoptes scabiei — Escabiose / Sarna",
     "Sarcoptidae", "ectoparasito",
     "Contato pele a pele prolongado; fômites (roupas, lençóis) — menos eficiente para sarna comum; eficiente para sarna crostosa",
     "Humanos (principal); animais domésticos (sarna animal — espécie hospedeiro-específica, não persiste em humanos)",
     "Distribuição nacional; surtos em famílias, abrigos, presídios, asilos; sarna crostosa (norueguesa) em imunossuprimidos com > 1 milhão de ácaros"),
    ("Cochliomyia hominivorax",
     "Cochliomyia hominivorax — Miiase",
     "Calliphoridae", "ectoparasito",
     "Postura de ovos por moscas adultas em feridas abertas, mucosas ou pele lesada; larvae penetram nos tecidos",
     "Bovinos (hospedeiro principal); humanos, cães, ovinos (hospedeiros acidentais)",
     "Distribuição nacional, maior prevalência no Norte e NE; sazonalidade no verão; problema de saúde pública e veterinária; tratamento mecânico de remoção"),
]

CLASSES_ANTIPARASITARIOS = [
    # (nome, mecanismo_acao, alvo_celular)
    ("Antimaláricos — Aminoquinolonas",
     "Inibição da detoxificação do heme — acúmulo de heme tóxico (ferriprotoporfirina IX) na vacúolo digestiva do parasito",
     "Vacúolo digestiva de Plasmodium spp. — heme polimerase"),
    ("Antimaláricos — Artemisininas",
     "Ativação pelo ferro do grupo endoperóxido — geração de radicais livres que alquilam e danificam proteínas e membranas do parasito",
     "Múltiplas proteínas de Plasmodium spp.; proteína PfATP6 (SERCA)"),
    ("Antimaláricos — 8-Aminoquinolonas",
     "Inibição da biossíntese do ubiquinol mitocondrial; metabolismo oxidativo das formas hepáticas dormentes (hipnozoítas); ação gametocida",
     "Cadeia respiratória mitocondrial de Plasmodium spp.; hipnozoítas de P. vivax e P. ovale"),
    ("Antileishmania — Antimoniais Pentavalentes",
     "Inibição da glicólise e β-oxidação de ácidos graxos do amastigota — depleção de ATP; ativação da apoptose parasitária",
     "Glicossomas (organelas de Leishmania) — enzimas da glicólise e biossíntese de ácidos graxos"),
    ("Antileishmania — Anfotericina B Lipossomal",
     "Ligação ao ergosterol da membrana do parasito — formação de poros iônicos e lise osmótica do amastigota e promastigota",
     "Ergosterol da membrana plasmática de Leishmania spp."),
    ("Antileishmania — Alquilfosfolipídios",
     "Inibição da síntese de fosfatidilcolina e da via PI3K/AKT — alteração de sinalização e apoptose parasitária",
     "Metabolismo de fosfolipídios e via de sinalização de PI3K em Leishmania spp."),
    ("Anti-Trypanosoma — Nitroheterocíclicos",
     "Redução enzimática a metabólitos reativos (nitrossoanion, radical livre) que danificam DNA, proteínas e membranas do tripanosoma",
     "DNA, proteínas e membranas de Trypanosoma cruzi — nitrorreductases parasitárias específicas"),
    ("Antiprotozoários — Nitroimidazóis",
     "Redução intracelular a nitrossoanion tóxico por ferredoxinas e piruvato:ferredoxina oxidorredutase (PFOR) — dano ao DNA",
     "DNA de protozoários anaeróbios e microaerófilos: Entamoeba, Giardia, Trichomonas"),
    ("Anti-helmínticos — Benzimidazóis",
     "Ligação seletiva à β-tubulina parasitária — inibição da polimerização de microtúbulos; captação de glicose prejudicada; morte por inanição",
     "β-tubulina de helmintos (alta afinidade) vs. β-tubulina humana (baixa afinidade)"),
    ("Anti-helmínticos — Avermectinas/Milbemicinas",
     "Potencialização dos canais de cloro glutamato-dependentes (GluCl) em neurônios e células musculares do nematódeo — hiperpolarização, paralisia e morte",
     "Canais iônicos de cloro glutamato-dependentes (GluCl) exclusivos de invertebrados; canais GABA-dependentes"),
    ("Anti-helmínticos — Praziquantel",
     "Aumento da permeabilidade da membrana ao Ca²⁺ — contração espástica da musculatura, vacuolização do tegumento, exposição de antígenos e lise pelo sistema imune",
     "Canais de cálcio voltagem-dependentes de trematódeos e cestódeos"),
    ("Anti-helmínticos — Salicilanilideos",
     "Desacoplamento da fosforilação oxidativa mitocondrial do helminto — depleção de ATP; inibição da captação anaeróbia de glicose",
     "Mitocôndria de cestódeos (T. saginata, T. solium) — ATP sintase e transportadores de prótons"),
    ("Antiparasitários — Piretroides",
     "Ligação aos canais de sódio voltagem-dependentes de insetos — prolonga abertura do canal, hiperpolarização e paralisia do artrópode",
     "Canais de sódio voltagem-dependentes (Nav) de artrópodes (piolhos, ácaros)"),
    ("Antiparasitários — Escabicidas e Pediculicidas Diversos",
     "Mecanismos variados: neurotoxicidade em artrópodes (benzil benzoato — disrupção de membrana; ivermectina — GluCl)",
     "Sistema nervoso e musculatura de Sarcoptes scabiei e Pediculus spp."),
    ("Antiparasitários — Antifolatos e Outros",
     "Inibição da di-hidrofolato redutase (DHFR) parasitária — bloqueio da síntese de tetrahidrofolato e replicação do DNA",
     "DHFR de Toxoplasma gondii, Plasmodium spp. (pirimetamina); DHPS (sulfonamidas)"),
]

ANTIPARASITARIOS = [
    # (nome_generico, nome_comercial, classe_nome, via, sus, anvisa, obs)
    # ── Antimaláricos ─────────────────────────────────────────
    ("Cloroquina",
     "Cloroquina Fosfato (Cloroquin / Cloroquina genérica)",
     "Antimaláricos — Aminoquinolonas", "oral", True, True,
     "1ª linha P. vivax e P. malariae no Brasil; disponível via FUNASA/SVS; P. falciparum resistente na Amazônia desde os anos 1980; também usado na profilaxia em áreas de P. vivax"),
    ("Primaquina",
     "Primaquina Fosfato",
     "Antimaláricos — 8-Aminoquinolonas", "oral", True, True,
     "Radical cure P. vivax (eliminação de hipnozoítas hepáticos); gametocida para P. falciparum; contraindicada em G6PD-deficientes graves, gestantes e lactantes; triagem G6PD obrigatória antes do uso"),
    ("Artemeter/Lumefantrina",
     "Coartem / Riamet",
     "Antimaláricos — Artemisininas", "oral", True, True,
     "1ª linha P. falciparum não complicado no Brasil (PCDT-MALARIA 2022); 6 doses em 3 dias; tomar com alimento gorduroso; teratogênica no 1º trimestre — usar quinino + clindamicina na gestação"),
    ("Artesunato",
     "Artesunato injetável (Guilin)",
     "Antimaláricos — Artemisininas", "iv/im", True, True,
     "Malária grave/complicada: superior à quinina IV em estudos AQUAMAT e SEAQUAMAT; 2,4 mg/kg EV nos tempos 0, 12h, 24h, depois 1x/dia até comer; disponível via SVS/FUNASA para hospitais"),
    ("Quinino",
     "Sulfato de Quinino / Quinino dicloridrato IV",
     "Antimaláricos — Aminoquinolonas", "oral/iv", True, True,
     "Malária grave (alternativa ao artesunato IV quando indisponível); malária na gestação (1º trimestre, com clindamicina); cinchonismo (zumbido, tontura, náusea) frequente; intervalo QT — ECG monitorar"),
    ("Mefloquina",
     "Lariam",
     "Antimaláricos — Aminoquinolonas", "oral", True, True,
     "Profilaxia e tratamento de P. falciparum; efeitos neuropsiquiátricos (pesadelos, ansiedade, psicose) em 1:10.000; evitar em história de convulsão e distúrbio psiquiátrico; resistência documentada no SE asiático"),
    ("Atovaquona/Proguanil",
     "Malarone",
     "Antimaláricos — Aminoquinolonas", "oral", False, True,
     "Profilaxia (iniciar 1-2 dias antes) e tratamento P. falciparum; alto custo — SUS apenas em situações especiais; alternativa para viajantes; seguro na maioria; associar com alimento"),
    ("Doxiciclina (antipalúdica)",
     "Doxiciclina (uso antipalúdico)",
     "Antimaláricos — Aminoquinolonas", "oral", True, True,
     "Associar ao artesunato ou quinino no tratamento de P. falciparum (7 dias); profilaxia para viajantes para Amazônia; não usar < 8 anos e na gestação"),
    # ── Antileishmania ────────────────────────────────────────
    ("Antimoniato de N-metilglucamina",
     "Glucantime",
     "Antileishmania — Antimoniais Pentavalentes", "im/iv", True, True,
     "Padrão-ouro LTA e LV no Brasil (PCDT-LEISH-TEG/VIS 2022); 20 mg SbV/kg/dia IM por 20-30 dias (LTA) ou 30 dias (LV); monitorar QT, amilase, lipase, creatinina; contraindicado em gestantes (Anf. B lipo 1ª linha), cardiopatas, renais graves"),
    ("Anfotericina B lipossomal",
     "AmBisome",
     "Antileishmania — Anfotericina B Lipossomal", "iv", True, True,
     "1ª linha LV em gestantes, crianças < 1 ano, idosos > 50 anos, insuficiência renal, cardiopatias, insucesso de antimoniato; 3-5 mg/kg/dia por 7 dias (dose total 21-40 mg/kg); menor toxicidade renal que Anf. B convencional"),
    ("Miltefosina",
     "Impavido",
     "Antileishmania — Alquilfosfolipídios", "oral", False, True,
     "LTA e LV — 1º antiparasitário oral eficaz para leishmaniose; 2,5 mg/kg/dia por 28 dias; teratogênica — contracepcão obrigatória; náusea/vômito em 30%; aprovada ANVISA; custo elevado; não disponível SUS rotina 2024"),
    ("Pentamidina isetionato",
     "Pentacarinat",
     "Antileishmania — Antimoniais Pentavalentes", "im", True, True,
     "2ª linha LTA — especialmente L. guyanensis (Amazônia) com resistência ao antimoniato; 4 mg/kg IM a cada 2 dias, 3-4 doses; hipoglicemia grave, nefrotoxicidade, diabetes permanente; monitorar glicemia"),
    # ── Anti-Chagas ───────────────────────────────────────────
    ("Benznidazol",
     "Rochagan / Radanil / Benznidazol genérico",
     "Anti-Trypanosoma — Nitroheterocíclicos", "oral", True, True,
     "1ª linha doença de Chagas (fase aguda e crônica recente); 5-7 mg/kg/dia em 2 doses por 60 dias; cura parasitológica >80% na fase aguda; eficácia na fase crônica indeterminada ~75% conforme ensaios; efeitos dermatológicos e neuropatia periférica frequentes"),
    ("Nifurtimox",
     "Lampit",
     "Anti-Trypanosoma — Nitroheterocíclicos", "oral", False, True,
     "2ª linha doença de Chagas (falha ou intolerância ao benznidazol); 8-10 mg/kg/dia adultos, 15-20 mg/kg/dia crianças por 60-90 dias; efeitos gastrointestinais e neurológicos; disponível via MS mediante solicitação"),
    # ── Antiprotozoários Intestinais ──────────────────────────
    ("Metronidazol",
     "Flagyl / Metronidazol genérico (uso antiparasitário)",
     "Antiprotozoários — Nitroimidazóis", "oral", True, True,
     "Amebíase intestinal e abscesso hepático amebiano, giardíase, tricomoníase; 500-750 mg 8/8h por 5-10 dias (amebíase); 500 mg 8/8h por 7 dias (tricomoníase); evitar álcool durante tratamento"),
    ("Tinidazol",
     "Fasigyn / Tinidazol genérico",
     "Antiprotozoários — Nitroimidazóis", "oral", True, True,
     "Alternativa ao metronidazol; maior meia-vida (t½ 12h); dose única 2 g giardíase e tricomoníase; melhor tolerância GI; 2 g/dia por 3-5 dias na amebíase intestinal; disponível SUS"),
    ("Secnidazol",
     "Secnidal",
     "Antiprotozoários — Nitroimidazóis", "oral", False, True,
     "Amebíase e giardíase; dose única 2 g — boa adesão; boa tolerância; não disponível SUS rotina; alternativa quando metronidazol não tolerado"),
    ("Nitazoxanida",
     "Annita / Alinia",
     "Antiparasitários — Antifolatos e Outros", "oral", False, True,
     "Criptosporidiose (única droga com aprovação; moderada eficácia em HIV/AIDS), giardíase; alternativa em falha de nitroimidazóis; 500 mg 12/12h por 3-7 dias; não disponível SUS rotina"),
    ("Sulfadiazina",
     "Sulfadiazina genérica",
     "Antiparasitários — Antifolatos e Outros", "oral", True, True,
     "Toxoplasmose (SNC, ocular, congênita) — sempre associar com pirimetamina + ácido folínico; 1-1,5 g 6/6h adultos; sulfonamida de longa duração; cristalúria — manter boa hidratação"),
    ("Pirimetamina",
     "Daraprim",
     "Antiparasitários — Antifolatos e Outros", "oral", True, True,
     "Toxoplasmose — inibidor da DHFR parasitária; sempre associar com ácido folínico 10-25 mg/dia para prevenir depressão medular; 200 mg ataque, depois 50-75 mg/dia; jamais usar sem folínico"),
    ("Ácido folínico",
     "Leucovorin / Ácido folínico genérico",
     "Antiparasitários — Antifolatos e Outros", "oral/iv", True, True,
     "Adjuvante obrigatório com pirimetamina no tratamento de toxoplasmose — previne mielotoxicidade (anemia megaloblástica, leucopenia); 10-25 mg/dia; não confundir com ácido fólico"),
    # ── Anti-helmintos ────────────────────────────────────────
    ("Albendazol",
     "Zentel / Albendazol genérico",
     "Anti-helmínticos — Benzimidazóis", "oral", True, True,
     "1ª linha ascaridíase, ancilostomíase, tricuríase, enterobíase, teníase intestinal; neurocisticercose (com dexametasona); toxocaríase; larva migrans cutânea; estrongiloidíase (alternativa); 400 mg dose única ou 400 mg/dia por 3 dias segundo indicação"),
    ("Mebendazol",
     "Pantelmin / Mebendazol genérico",
     "Anti-helmínticos — Benzimidazóis", "oral", True, True,
     "Alternativa ao albendazol; enterobíase (100 mg dose única), ascaridíase e ancilostomíase (100 mg 12/12h por 3 dias); má absorção sistêmica — eficaz apenas na luz intestinal; seguro em crianças > 2 anos"),
    ("Ivermectina",
     "Ivermec / Stromectol / Ivermectina genérica",
     "Anti-helmínticos — Avermectinas/Milbemicinas", "oral", True, True,
     "1ª linha estrongiloidíase (200 mcg/kg por 2 dias); enterobíase, oncocercose (150 mcg/kg dose única anual), escabiose (200 mcg/kg dose única repetir em 14 dias), larva migrans cutânea; filariose (MDA com DEC+albendazol)"),
    ("Praziquantel",
     "Biltricide / Praziquantel genérico",
     "Anti-helmínticos — Praziquantel", "oral", True, True,
     "Padrão-ouro esquistossomose mansoni (60 mg/kg dose única adultos; 50 mg/kg crianças); teníase (5-10 mg/kg dose única); fasciolíase (NÃO eficaz — usar triclabendazol); neurocisticercose (associar corticoterapia); evitar na gestação"),
    ("Niclosamida",
     "Yomesan",
     "Anti-helmínticos — Salicilanilideos", "oral", False, True,
     "Teníase por T. saginata e T. solium (sem NCC) — alternativa ao praziquantel; 2 g dose única; mastigar bem os comprimidos; não absorvida sistemicamente — pouco útil para larvas teciduais; não disponível SUS rotina"),
    ("Tiabendazol",
     "Mintezol",
     "Anti-helmínticos — Benzimidazóis", "oral/tópico", False, True,
     "Larva migrans cutânea tópica (solução/pomada 10-15%); estrongiloidíase (alternativa de 2ª linha); tolerância inferior ao albendazol; hepatotoxicidade; em desuso para uso sistêmico no Brasil"),
    ("Pirantel pamoato",
     "Combantrin / Pirantel genérico",
     "Anti-helmínticos — Avermectinas/Milbemicinas", "oral", True, True,
     "Enterobíase e ascaridíase — 11 mg/kg dose única (máx 1 g); paralisia neuromuscular do helminto (inibição colinesterase); seguro na gestação (> 1º trimestre); alternativa a albendazol em grávidas"),
    ("Oxamniquina",
     "Mansil",
     "Anti-helmínticos — Praziquantel", "oral", True, True,
     "Esquistossomose mansoni — alternativa ao praziquantel; 15 mg/kg dose única adultos (20 mg/kg crianças < 30 kg); resistência regional documentada no NE; disponível SUS em algumas áreas; sabor desagradável"),
    ("Dietilcarbamazina (DEC)",
     "Hetrazan / Notézine",
     "Antiparasitários — Antifolatos e Outros", "oral", True, True,
     "Filariose linfática (W. bancrofti) — microfilaricida + macrofilaricida parcial; 6 mg/kg/dia por 12 dias (tratamento individual) ou dose única no programa de eliminação (MDA: DEC+albendazol); reação de Mazzotti (febre, prurido) por morte de microfilárias; contraindicado na oncocercose"),
    ("Triclabendazol",
     "Egaten",
     "Anti-helmínticos — Benzimidazóis", "oral", False, True,
     "Fasciolíase — única droga eficaz; 10 mg/kg dose única (repetir em 12h para infecção intensa); eficácia >90%; não disponível no Brasil pela rede pública — solicitar via MS (acesso especial ANVISA)"),
    # ── Ectoparasitoses ───────────────────────────────────────
    ("Permetrina",
     "Nix (1%) / Scabina (5%) / Kwell permetrina",
     "Antiparasitários — Piretroides", "tópico", True, True,
     "Pediculose do couro cabeludo (1% loção/creme rinse — aplicar 10 min, enxaguar, repetir em 7-10 dias) e escabiose (5% creme — aplicar do pescoço para baixo, deixar 8-12h, repetir em 7 dias); segura em gestantes e lactantes; resistência documentada em algumas regiões"),
    ("Benzil benzoato 25%",
     "Miticar / Benzil benzoato genérico",
     "Antiparasitários — Escabicidas e Pediculicidas Diversos", "tópico", True, True,
     "Escabiose — 1ª linha SUS no Brasil; aplicar 25% de pescoço para baixo, 12-24h, repetir em 3-5 dias; irritante para pele e mucosas; não aplicar no rosto; eficácia similar à permetrina; alternativa em gestantes (usar com cautela)"),
]
