"""
Fontes oficiais, classes e medicamentos para doenças crônicas/não-infecciosas.
Fontes: PCDTs-MS, SBC, SBD, SBR, ABN, INCA, CFM, ANVISA.
"""

# (sigla, nome, orgao, tipo, url, ano, descricao)
FONTES_CRONICAS = [
    ("SBC-HAS",        "Diretrizes Brasileiras de Hipertensão Arterial 2020",
     "Sociedade Brasileira de Cardiologia", "Diretriz",
     "https://www.sbc.org.br", 2020,
     "Diretrizes nacionais para diagnóstico, estratificação de risco e tratamento da HAS"),
    ("SBC-ICC",        "Diretriz Brasileira de Insuficiência Cardíaca 2021",
     "Sociedade Brasileira de Cardiologia", "Diretriz",
     "https://www.sbc.org.br", 2021,
     "Diagnóstico e tratamento da insuficiência cardíaca crónica e aguda"),
    ("SBC-DISLIPID",   "Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2017",
     "Sociedade Brasileira de Cardiologia", "Diretriz",
     "https://www.sbc.org.br", 2017,
     "Metas de LDL e abordagem terapêutica das dislipidemias"),
    ("SBC-SCA",        "Diretriz de Síndrome Coronariana Aguda e Prevenção Cardiovascular SBC 2021",
     "Sociedade Brasileira de Cardiologia", "Diretriz",
     "https://www.sbc.org.br", 2021,
     "SCA, FA, TVP/TEP, AVC, DAP — anticoagulação e antiagregação"),
    ("SBD-DM2",        "Diretrizes da Sociedade Brasileira de Diabetes — DM tipo 2 — 2022",
     "Sociedade Brasileira de Diabetes", "Diretriz",
     "https://www.diabetes.org.br", 2022,
     "Metas glicêmicas, seleção de hipoglicemiante e manejo de complicações do DM2"),
    ("SBD-DM1",        "Diretrizes da Sociedade Brasileira de Diabetes — DM tipo 1 — 2022",
     "Sociedade Brasileira de Diabetes", "Diretriz",
     "https://www.diabetes.org.br", 2022,
     "Insulinoterapia intensiva, metas e complicações do DM1"),
    ("PCDT-HAS",       "PCDT Hipertensão Arterial Sistêmica — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Protocolo clínico e diretrizes terapêuticas para HAS — fornecimento SUS"),
    ("PCDT-DM2",       "PCDT Diabetes Mellitus tipo 2 — Ministério da Saúde 2020",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2020,
     "Protocolo DM2 — critérios de dispensação de medicamentos pelo SUS"),
    ("PCDT-DM1",       "PCDT Diabetes Mellitus tipo 1 — Ministério da Saúde 2020",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2020,
     "Protocolo DM1 — fornecimento de insulinas e insumos pelo SUS"),
    ("PCDT-OBESIDADE",  "PCDT Obesidade — Ministério da Saúde 2020",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2020,
     "Tratamento farmacológico e cirúrgico da obesidade pelo SUS"),
    ("PCDT-DISLIPID",  "PCDT Dislipidemia — Ministério da Saúde 2020",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2020,
     "Acesso a estatinas de alta intensidade e ezetimiba pelo componente especializado"),
    ("PCDT-HIPOTIREOID", "PCDT Hipotireoidismo — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Levotiroxina pelo componente básico do SUS — critérios e metas"),
    ("PCDT-OSTEOPOROSE", "PCDT Osteoporose — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Bisfosfonatos, denosumabe e ranelato de estrôncio pelo componente especializado"),
    ("PCDT-AR",        "PCDT Artrite Reumatoide — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "DMARDs convencionais e biológicos para AR — componente especializado SUS"),
    ("PCDT-LES",       "PCDT Lúpus Eritematoso Sistêmico — Ministério da Saúde 2021",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2021,
     "Imunossupressores e belimumabe para LES — componente especializado"),
    ("PCDT-EPILEPSIA", "PCDT Epilepsia — Ministério da Saúde 2020",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2020,
     "Antiepilépticos de primeira e segunda linha disponíveis pelo SUS"),
    ("PCDT-PARKINSON", "PCDT Doença de Parkinson — Ministério da Saúde 2017",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2017,
     "Levodopa, agonistas dopaminérgicos e ICOMT pelo componente especializado"),
    ("PCDT-ALZHEIMER", "PCDT Doença de Alzheimer — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Inibidores de colinesterase e memantina — componente especializado SUS"),
    ("PCDT-ASMA",      "PCDT Asma — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "ICS, LABA, LAMA e biológicos para asma grave — SUS"),
    ("PCDT-DPOC",      "PCDT DPOC — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Broncodilatadores de longa ação e tripla terapia para DPOC — SUS"),
    ("PCDT-DRC",       "PCDT Doença Renal Crônica — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Nefroproteção, eritropoetina e preparação para TRS — componente especializado"),
    ("PCDT-PSORIASE",  "PCDT Psoríase — Ministério da Saúde 2020",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2020,
     "Metotrexato, ciclosporina e biológicos anti-TNF para psoríase moderada-grave"),
    ("PCDT-CROHN",     "PCDT Doença de Crohn — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Azatioprina, infliximabe e vedolizumabe para Doença de Crohn — SUS"),
    ("PCDT-RCU",       "PCDT Retocolite Ulcerativa — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Mesalazina, imunossupressores e biológicos para RCU — SUS"),
    ("PCDT-ANEMIA-FALCIF", "PCDT Doença Falciforme — Ministério da Saúde 2022",
     "Ministério da Saúde / CONITEC", "PCDT",
     "https://www.gov.br/saude", 2022,
     "Hidroxiureia e cuidados integrais para anemia falciforme — componente básico SUS"),
    ("SBR-AR",         "Recomendações da Sociedade Brasileira de Reumatologia — AR, LES, EA 2021",
     "Sociedade Brasileira de Reumatologia", "Diretriz",
     "https://www.reumatologia.org.br", 2021,
     "DMARDs convencionais e biológicos — indicações e monitoramento"),
    ("ABN-EPILEPSIA",  "Recomendações da Academia Brasileira de Neurologia — Epilepsia 2020",
     "Academia Brasileira de Neurologia", "Diretriz",
     "https://www.abneuro.org.br", 2020,
     "Antiepilépticos de 1ª e 2ª linha por tipo de epilepsia"),
    ("ABN-PARKINSON",  "Recomendações da Academia Brasileira de Neurologia — Parkinson 2019",
     "Academia Brasileira de Neurologia", "Diretriz",
     "https://www.abneuro.org.br", 2019,
     "Tratamento farmacológico e não farmacológico da doença de Parkinson"),
    ("INCA-ONCOL",     "Protocolos Clínicos Oncológicos INCA/MS 2022",
     "Instituto Nacional de Câncer / Ministério da Saúde", "PCDT",
     "https://www.inca.gov.br", 2022,
     "Protocolos de quimioterapia, hormonioterapia e imunoterapia disponíveis no SUS"),
    ("CFM-SM",         "Diretrizes do Conselho Federal de Medicina — Saúde Mental 2021",
     "Conselho Federal de Medicina", "Diretriz",
     "https://www.cfm.org.br", 2021,
     "Tratamento farmacológico de transtornos mentais — ISRS, antipsicóticos, estabilizadores"),
]


# (nome, mecanismo_acao, alvo_terapeutico, area_terapeutica)
CLASSES_MEDICAMENTOS = [
    # ── Cardiovascular ────────────────────────────────────────────────────────
    ("IECA — Inibidores da Enzima Conversora de Angiotensina",
     "Inibição da ECA → ↓ angiotensina II e ↓ bradicinina → vasodilatação arteriovenosa, natriurese e redução de pré/pós-carga cardíaca",
     "ECA (dipeptidil carboxipeptidase) — sistema renina-angiotensina-aldosterona",
     "cardiovascular"),
    ("BRA — Bloqueadores do Receptor AT1 de Angiotensina",
     "Bloqueio seletivo do receptor AT1 → ↓ vasoconstrição, ↓ retenção sódio-água, ↓ aldosterona — sem efeito sobre bradicinina (menos tosse que IECA)",
     "Receptor AT1 de angiotensina II",
     "cardiovascular"),
    ("Betabloqueadores",
     "Bloqueio competitivo dos receptores β1 (cardioseletivos) e β2 (não seletivos) → ↓ FC, ↓ contratilidade, ↓ débito cardíaco e remodelamento reverso em IC",
     "Receptores β-adrenérgicos (β1 miocárdio, β2 vasculatura e brônquios)",
     "cardiovascular"),
    ("BCC Diidropiridínicos — Bloqueadores de Canal de Cálcio",
     "Bloqueio seletivo dos canais de cálcio voltagem-dependentes (tipo L) na musculatura lisa vascular → vasodilatação arterial periférica e coronariana",
     "Canais de Ca²⁺ tipo L em células musculares lisas vasculares",
     "cardiovascular"),
    ("BCC Não Diidropiridínicos (Fenilalquilaminas / Benzotiazepinas)",
     "Bloqueio de canais Ca²⁺ em nó SA e AV além do músculo liso vascular → cronotropismo e dromotropismo negativos + vasodilatação moderada",
     "Canais de Ca²⁺ tipo L em miocárdio e tecido de condução (verapamil, diltiazem)",
     "cardiovascular"),
    ("Diuréticos Tiazídicos e Tiazídico-like",
     "Inibição do cotransportador Na-Cl no túbulo contorcido distal → natriurese, diurese e redução da resistência vascular periférica a longo prazo",
     "Cotransportador NCC (SLC12A3) no túbulo distal renal",
     "cardiovascular"),
    ("Diuréticos de Alça",
     "Inibição do cotransportador Na-K-2Cl (NKCC2) na alça de Henle → intensa natriurese e diurese, eficaz mesmo em TFGe reduzida",
     "Cotransportador NKCC2 no ramo ascendente espesso da alça de Henle",
     "cardiovascular"),
    ("Diuréticos Poupadores de Potássio / Antagonistas de Aldosterona",
     "Bloqueio do receptor de aldosterona (mineralocorticoide) → ↓ reabsorção de Na+, ↓ excreção de K+; remodelamento cardíaco reverso em ICFEr",
     "Receptor de mineralocorticoide (MR) na célula principal do túbulo coletor",
     "cardiovascular"),
    ("Nitratos Orgânicos",
     "Liberação de NO → ativação guanilil ciclase → ↑ GMPc → relaxamento musculatura lisa vascular → venodilatação predominante (↓ pré-carga) e coronarodilatação",
     "Guanilil ciclase solúvel mediada por NO nas células musculares lisas vasculares",
     "cardiovascular"),
    ("Estatinas — Inibidores da HMG-CoA Redutase",
     "Inibição competitiva e reversível da HMG-CoA redutase → ↓ síntese hepática de colesterol → upregulation de receptores LDL → ↓ LDL plasmático; efeitos pleiotrópicos anti-inflamatórios",
     "HMG-CoA redutase — enzima limitante da biossíntese de mevalonato/colesterol",
     "cardiovascular"),
    ("Fibratos — Agonistas PPAR-α",
     "Ativação do receptor nuclear PPAR-α → ↑ oxidação de ácidos graxos, ↑ síntese de APO-AII/CII, ↑ LPL → ↓ triglicerídeos 30-50% e ↑ HDL 10-20%",
     "PPAR-α (receptor ativado por proliferadores de peroxissoma alfa) hepático e muscular",
     "cardiovascular"),
    ("Antiagregantes Plaquetários — Inibidores de COX-1 (Salicilatos)",
     "Acetilação irreversível da COX-1 plaquetária → ↓ síntese de TXA2 → inibição da agregação plaquetária dependente de TXA2 por toda a vida da plaqueta (~7-10 dias)",
     "COX-1 (ciclooxigenase-1) plaquetária — síntese de tromboxano A2",
     "cardiovascular"),
    ("Antiagregantes Plaquetários — Inibidores de P2Y12",
     "Bloqueio do receptor P2Y12 de ADP (irreversível: clopidogrel/prasugrel; reversível: ticagrelor) → inibição da ativação e agregação plaquetária",
     "Receptor P2Y12 (ADP) na membrana plaquetária",
     "cardiovascular"),
    ("Anticoagulantes — Antagonistas da Vitamina K",
     "Inibição da vitamina K epóxido redutase (VKORC1) → ↓ γ-carboxilação dos fatores de coagulação II, VII, IX, X e proteínas C/S",
     "VKORC1 — vitamina K epóxido redutase; fatores de coagulação vitamina K-dependentes",
     "cardiovascular"),
    ("Anticoagulantes Orais Diretos — Anti-Xa (Rivaroxabana, Apixabana)",
     "Inibição direta e reversível do fator Xa → bloqueio da conversão de protrombina em trombina — sem necessidade de monitoração de RNI",
     "Fator Xa da cascata de coagulação",
     "cardiovascular"),
    ("Anticoagulantes Orais Diretos — Inibidor Direto de Trombina (Dabigatrana)",
     "Inibição direta e reversível da trombina (fator IIa) livre e ligada ao coágulo de fibrina",
     "Trombina (fator IIa) — conversão de fibrinogênio em fibrina",
     "cardiovascular"),
    # ── Endócrino / Metabólico ───────────────────────────────────────────────
    ("Biguanidas — Metformina",
     "Ativação da AMPK hepática → ↓ gliconeogênese e glicogenólise hepática; ↑ sensibilidade à insulina no músculo; ↓ absorção intestinal de glicose; neutro ou leve perda de peso; sem hipoglicemia isolada",
     "AMPK (AMP-activated protein kinase) hepática; Complex I mitocondrial",
     "endocrino_metabolico"),
    ("Inibidores de SGLT-2 — Gliflozinas",
     "Inibição do cotransportador de sódio-glicose-2 (SGLT-2) no túbulo proximal renal → glicosúria e natriurese forçada → ↓ glicemia, ↓ PA, ↓ peso; cardioproteção e nefroproteção independente de DM",
     "SGLT-2 (SLC5A2) — cotransportador Na-glicose tipo 2 no túbulo proximal renal",
     "endocrino_metabolico"),
    ("Agonistas de GLP-1 — Análogos de GLP-1",
     "Mimetismo do GLP-1 → estimulação dependente de glicose da secreção de insulina, supressão do glucagon, retardo do esvaziamento gástrico, saciedade central (hipotálamo) → ↓ HbA1c e ↓ peso corporal; benefício cardiovascular",
     "Receptor de GLP-1 (glucagon-like peptide-1) em células β-pancreáticas, SNC e trato GI",
     "endocrino_metabolico"),
    ("Inibidores de DPP-4 — Gliptinas",
     "Inibição da dipeptidil peptidase-4 → ↑ meia-vida do GLP-1 e GIP endógenos → estimulação dependente de glicose da insulina e supressão de glucagon; neutros em peso",
     "Enzima DPP-4 (CD26) — principal enzima de degradação do GLP-1 endógeno",
     "endocrino_metabolico"),
    ("Sulfonilureias",
     "Bloqueio do canal de K+-ATP nas células β → despolarização → ↑ Ca²⁺ intracelular → liberação de insulina independente de glicose; risco de hipoglicemia",
     "Canal de K+-ATP (subunidade SUR1) nas células β-pancreáticas",
     "endocrino_metabolico"),
    ("Insulinas e Análogos de Insulina",
     "Ligação ao receptor de insulina (RTK) → ativação IRS-1/PI3K/AKT → captação de glicose (GLUT4 em músculo e adipócito), inibição da gliconeogênese e lipolise; reposição hormonal em DM1 e DM2 avançado",
     "Receptor de insulina (IR-A/IR-B) — tirosina quinase — músculo, fígado e adipócito",
     "endocrino_metabolico"),
    ("Hormônio Tireoidiano — Levotiroxina (T4)",
     "Reposição do T4 → conversão periférica em T3 (ativo) → ligação ao receptor nuclear de hormônio tireoidiano (TR) → regulação do metabolismo basal, termogênese, FC, crescimento e desenvolvimento",
     "Receptor nuclear de hormônio tireoidiano (TRα e TRβ) em múltiplos tecidos",
     "endocrino_metabolico"),
    ("Antitireoidianos — Tionamidas",
     "Inibição da peroxidase tireoidiana (TPO) → bloqueio da oxidação do iodeto e iodação da tiroglobulina → ↓ síntese de T3 e T4; metimazol também inibe conversão periférica de T4 em T3",
     "Peroxidase tireoidiana (TPO) na célula folicular tireoidiana",
     "endocrino_metabolico"),
    ("Uricostáticos — Inibidores de Xantina Oxidase",
     "Inibição da xantina oxidase → ↓ conversão de hipoxantina e xantina em ácido úrico → redução da uricemia",
     "Xantina oxidase (XO) — enzima limitante da síntese de ácido úrico",
     "endocrino_metabolico"),
    ("Bisfosfonatos — Inibidores da Reabsorção Óssea",
     "Incorporação na matriz óssea → fagocitados por osteoclastos → inibição da farnesil difosfato sintase (via do mevalonato) → apoptose de osteoclastos → ↓ reabsorção óssea",
     "Farnesil pirofosfato sintase em osteoclastos — via do mevalonato",
     "endocrino_metabolico"),
    # ── Oncológico ───────────────────────────────────────────────────────────
    ("Antimetabólitos — Análogos de Pirimidina/Purina",
     "Incorporação ao DNA/RNA em substituição aos nucleotídeos fisiológicos → terminação de cadeia ou inibição de enzimas-chave da biossíntese (TS, DHFR) → parada do ciclo celular e apoptose",
     "DNA polimerase, timidilato sintase (5-FU/capecitabina); DHFR (metotrexato)",
     "oncologico"),
    ("Agentes Alquilantes — Platinos",
     "Formação de adutos com DNA (ligações cruzadas intra e intercadeias) → inibição da replicação e transcrição → apoptose celular; especialmente em células com alto turnover",
     "DNA — formação de adutos platina-guanina (cisplatina, carboplatina, oxaliplatina)",
     "oncologico"),
    ("Taxanos — Estabilizadores de Microtúbulos",
     "Ligação à β-tubulina polimerizadas → estabilização do fuso mitótico → inibição da depolimerização → parada na fase G2/M → apoptose",
     "β-tubulina polimerizada (paclitaxel, docetaxel) — inibição da dinâmica de microtúbulos",
     "oncologico"),
    ("Antracíclicos — Inibidores de Topoisomerase II",
     "Intercalação no DNA + inibição da topoisomerase II → quebras de fita dupla → apoptose; geração de radicais livres (cardiotoxicidade cumulativa)",
     "Topoisomerase II + intercalação DNA (doxorrubicina, daunorrubicina, epirrubicina)",
     "oncologico"),
    ("Anticorpos Monoclonais Oncológicos — Anti-HER2/Anti-EGFR/Anti-CD20/Anti-VEGF",
     "Mecanismos variados: bloqueio de receptores de crescimento (trastuzumabe-HER2, cetuximabe-EGFR), depleção de linfócitos B (rituximabe-CD20), inibição de angiogênese (bevacizumabe-VEGF)",
     "HER2, EGFR, CD20, VEGF, PD-L1 — alvos moleculares específicos de tumores",
     "oncologico"),
    ("Inibidores de Tirosina Quinase (TKIs)",
     "Inibição competitiva de domínios tirosina quinase de receptores hiperativados por mutações oncogênicas (BCR-ABL, EGFR mut, ALK, HER2) → ↓ proliferação, ↑ apoptose tumoral",
     "BCR-ABL (imatinibe), EGFR mutado (erlotinibe/osimertinibe), ALK (crizotinibe/alectinibe)",
     "oncologico"),
    ("Imunoterapia — Inibidores de Checkpoint (Anti-PD-1/PD-L1/CTLA-4)",
     "Bloqueio dos receptores inibitórios do sistema imune (PD-1, PD-L1, CTLA-4) → reativação de linfócitos T esgotados → reconhecimento e destruição de células tumorais",
     "PD-1 (pembrolizumabe, nivolumabe), PD-L1 (atezolizumabe), CTLA-4 (ipilimumabe)",
     "oncologico"),
    ("Hormonioterapia Oncológica — Inibidores de Aromatase e SERMs/SERDs",
     "IA: inibição da aromatase → ↓ estrogênio em pós-menopausa; tamoxifeno: antagonista ER em mama, agonista em útero/osso; fulvestranto (SERD): degradador de ER",
     "Aromatase (CYP19A1); receptor de estrogênio α (ERα) em células de câncer de mama",
     "oncologico"),
    ("Inibidores de PARP",
     "Inibição da poli-ADP-ribose polimerase → acúmulo de quebras de fita simples de DNA → colapso na forquilha de replicação → letal em células com deficiência de recombinação homóloga (BRCA1/2 mutado)",
     "PARP-1 e PARP-2 (olaparibe, niraparibe, rucaparibe) — reparo de DNA por excisão de base",
     "oncologico"),
    # ── Saúde Mental / Neurológico ───────────────────────────────────────────
    ("ISRS — Inibidores Seletivos da Recaptação de Serotonina",
     "Bloqueio seletivo do transportador de serotonina (SERT) → ↑ serotonina na fenda sináptica → dessensibilização de autorreceptores 5-HT1A → efeito antidepressivo/ansiolítico em 2-4 semanas",
     "SERT (transportador de serotonina, SLC6A4) no terminal pré-sináptico",
     "saude_mental"),
    ("IRSN — Inibidores da Recaptação de Serotonina e Noradrenalina",
     "Bloqueio dual de SERT e NET (transportador de noradrenalina) → ↑ serotonina e noradrenalina → maior eficácia para dor neuropática e ansiedade que ISRS puro",
     "SERT (serotonina) + NET (noradrenalina, SLC6A2) no terminal pré-sináptico",
     "saude_mental"),
    ("Antidepressivos Tricíclicos (ADTs)",
     "Bloqueio não seletivo de SERT e NET + antagonismo de receptores H1 (sedação), α1 (hipotensão ortostática) e M1 (efeitos anticolinérgicos) — eficácia comparável a ISRS com mais efeitos adversos",
     "SERT + NET + H1 + α1-adrenérgico + M1 muscarínico",
     "saude_mental"),
    ("Antipsicóticos Típicos — Bloqueadores D2",
     "Bloqueio potente e não seletivo dos receptores dopaminérgicos D2 nas vias mesolímbica, nigroestriatal e tuberoinfundibular → controle de psicose, mas com efeitos extrapiramidais (EPS) e hiperprolactinemia",
     "Receptor D2 de dopamina (alta afinidade) — vias mesolímbica, nigroestriatal, tuberoinfundibular",
     "saude_mental"),
    ("Antipsicóticos Atípicos — Antagonistas D2/5-HT2A",
     "Bloqueio D2 de menor afinidade + antagonismo 5-HT2A proeminente → eficácia antipsicótica com menor EPS e menor hiperprolactinemia; ação em sintomas negativos; risco metabólico variável",
     "D2 dopaminérgico + 5-HT2A serotoninérgico (+ H1, α1, M1 em variados graus por fármaco)",
     "saude_mental"),
    ("Estabilizadores de Humor — Sais de Lítio",
     "Múltiplos mecanismos: inibição de GSK-3β e PKC, modulação de inositol fosfato, neuroproteção (↑ BDNF) e cronobiológico → estabilização do humor em TAB, anti-suicídio único com evidência robusta",
     "GSK-3β, PKC, inositol monofosfatase — múltiplas vias de sinalização intracelular",
     "saude_mental"),
    ("Antiepilépticos — Bloqueadores de Canal de Sódio",
     "Bloqueio dos canais de sódio voltagem-dependentes em estado inativado → estabilização de membranas neuronais hiperexcitáveis → supressão de crises parcias e generalizadas tônico-clônicas",
     "Canais de Na+ voltagem-dependentes (NaV1.1-NaV1.6) na membrana neuronal",
     "neurologico"),
    ("Antiepilépticos — Análogos e Moduladores GABAérgicos",
     "Mecanismos variados: potencialização do GABA (benzodiazepínicos — ↑ frequência GABA-A Cl−), inibição de GABA transaminase (vigabatrina), análogos estruturais (gabapentina/pregabalina — canais Ca²⁺ α2δ)",
     "Receptor GABA-A (benzodiazepínicos), subunidade α2δ de canais Ca²⁺ (gabapentina/pregabalina)",
     "neurologico"),
    ("Agonistas Dopaminérgicos — Anti-Parkinson",
     "Estimulação direta de receptores D2 (e D3) na via nigroestriatal → mimetismo da dopamina reduzida na doença de Parkinson → melhora de tremor, rigidez e bradicinesia; sem o efeito pulsátil da levodopa",
     "Receptores D2/D3 dopaminérgicos no estriado (pramipexol, ropinirol, rotigotina)",
     "neurologico"),
    ("Inibidores de Colinesterase — Antidemenciais",
     "Inibição reversível da acetilcolinesterase (e/ou butirilcolinesterase) → ↑ acetilcolina na fenda sináptica colinérgica → compensação da depleção colinérgica no Alzheimer → melhora cognitiva e funcional modesta",
     "Acetilcolinesterase (AChE) — donepezila; AChE + BuChE — rivastigmina; AChE — galantamina",
     "neurologico"),
    # ── Respiratório ─────────────────────────────────────────────────────────
    ("Beta-2 Agonistas de Curta Ação (SABA)",
     "Estimulação de receptores β2 na musculatura lisa brônquica → ativação adenilil ciclase → ↑ AMPc → PKA → relaxamento muscular e broncodilatação em minutos (alívio de crise)",
     "Receptores β2-adrenérgicos na musculatura lisa brônquica e mastócitos",
     "respiratorio"),
    ("Beta-2 Agonistas de Longa Ação (LABA)",
     "Estimulação prolongada (12-24h) de receptores β2 brônquicos → broncodilatação sustentada → uso associado a ICS (nunca como monoterapia em asma não controlada)",
     "Receptores β2-adrenérgicos — ação prolongada (formoterol, salmeterol, vilanterol, indacaterol)",
     "respiratorio"),
    ("Anticolinérgicos de Longa Ação (LAMA)",
     "Bloqueio prolongado (24h) dos receptores muscarínicos M3 na musculatura lisa brônquica e glândulas mucosas → ↓ broncoconstrição colinérgica, ↓ hipersecreção → broncodilatação DPOC",
     "Receptor muscarínico M3 na musculatura lisa brônquica (tiotrópio, umeclidínio, glicopirrônio)",
     "respiratorio"),
    ("Corticosteroides Inalatórios (ICS)",
     "Ligação ao receptor de glicocorticoide → translocação nuclear → supressão de genes pró-inflamatórios (IL-4, IL-5, IL-13) e ↑ genes anti-inflamatórios → ↓ eosinofilia, ↓ hiperresponsividade brônquica",
     "Receptor de glicocorticoide (GR) em células inflamatórias e epiteliais brônquicas",
     "respiratorio"),
    ("Antileucotrienos — Inibidores de Receptor de Cisteinil-Leucotrieno",
     "Bloqueio do receptor CysLT1 de leucotrienos (LTC4, LTD4, LTE4) na mucosa brônquica → ↓ broncoconstrição, ↓ edema mucoso e ↓ eosinofilia — especialmente em asma alérgica e rinite",
     "Receptor CysLT1 de cisteinil-leucotrienos na musculatura lisa e eosinófilos brônquicos",
     "respiratorio"),
    # ── GI / Hepático ────────────────────────────────────────────────────────
    ("IBP — Inibidores de Bomba de Prótons",
     "Inibição irreversível (covalente) da H+/K+-ATPase (bomba de prótons) da célula parietal gástrica → supressão da secreção ácida gástrica > 90%; pró-fármaco ativado em pH ácido",
     "H+/K+-ATPase (bomba de prótons) na membrana canalicular da célula parietal gástrica",
     "gastroenterologico"),
    ("Aminossalicilatos (5-ASA)",
     "Ação tópica na mucosa intestinal → inibição local de COX e LOX → ↓ prostaglandinas e leucotrienos inflamatórios → ↓ inflamação na mucosa colônica (RCU)",
     "COX e 5-LOX intestinal; NF-κB; PPAR-γ — ação anti-inflamatória tópica colônica",
     "gastroenterologico"),
    # ── Reumatológico / Imunológico ──────────────────────────────────────────
    ("DMARDs Convencionais — Metotrexato",
     "Inibição competitiva da di-hidrofolato redutase (DHFR) → ↓ disponibilidade de tetrahidrofolato → ↓ síntese de purinas e timidilato (anti-inflamatório via ↑ adenosina extracelular em baixas doses)",
     "DHFR (di-hidrofolato redutase) + enzimas dependentes de folato (AMP-deaminase via adenosina)",
     "reumatologico"),
    ("Antimaláricos — Hidroxicloroquina",
     "Alcalinização de lisossomas → inibição da apresentação de antígenos e ativação de TLRs → ↓ produção de citocinas pró-inflamatórias (IL-1, IL-6, TNF) — efeito anti-inflamatório e imunomodulador",
     "Lisossomos e TLR7/TLR9 em macrófagos e células dendríticas",
     "reumatologico"),
    ("Biológicos Anti-TNF",
     "Neutralização do TNF-α (solúvel e transmembranar) por anticorpos monoclonais (infliximabe, adalimumabe, golimumabe, certolizumabe) ou receptor de fusão (etanercepte) → ↓ inflamação articular, intestinal e cutânea",
     "TNF-α (fator de necrose tumoral) — citocina central na artrite reumatoide, Crohn e psoríase",
     "reumatologico"),
    ("Inibidores de IL-6 (Tocilizumabe)",
     "Bloqueio do receptor de IL-6 (IL-6R solúvel e transmembranar) → inibição da sinalização via JAK/STAT3 → ↓ inflamação sistêmica, ↓ PCR, ↓ reactantes de fase aguda",
     "Receptor de IL-6 (gp80/IL-6Rα) — sinalização JAK1/STAT3",
     "reumatologico"),
    ("Inibidores de JAK (JAKinibs)",
     "Inibição das Janus quinases (JAK1, JAK2, JAK3, TYK2) → bloqueio da sinalização de múltiplas citocinas pró-inflamatórias (IL-6, IFN, GM-CSF) → anti-inflamatório amplo por via oral",
     "JAK1/JAK2/JAK3/TYK2 — tirosina quinases intracelulares da via JAK-STAT",
     "reumatologico"),
    ("Uricostáticos — Inibidores de Xantina Oxidase (Alopurinol)",
     "Inibição da xantina oxidase → ↓ produção de ácido úrico a partir de hipoxantina e xantina → queda da uricemia e prevenção de cristais de urato",
     "Xantina oxidase hepática (XO/XDH) — enzima limitante da via de catabolismo das purinas",
     "reumatologico"),
    ("SERMs — Moduladores Seletivos de Receptores de Estrogênio",
     "Agonismo parcial nos receptores ER em osso (↑ densidade mineral óssea) e antagonismo em mama (tamoxifeno: antagonista ER mama, agonista útero; raloxifeno: antagonista mama e útero)",
     "Receptor de estrogênio α e β — conformação diferente por tecido confere seletividade",
     "reumatologico"),
    ("Inibidores de Calcineurina Tópicos (Tacrolimus/Pimecrolimus)",
     "Inibição da calcineurina → ↓ desfosforilação de NFAT → ↓ produção de IL-2 e outras citocinas em linfócitos T → ação anti-inflamatória tópica sem atrofia cutânea (ao contrário de CIs)",
     "Calcineurina (fosfatase dependente de Ca²⁺-calmodulina) em linfócitos T",
     "dermatologico"),
    ("Alfa-Bloqueadores — HPB",
     "Bloqueio seletivo de receptores α1A-adrenérgicos no estroma prostático e no colo vesical → relaxamento muscular liso → melhora do fluxo urinário e dos sintomas do trato urinário inferior (LUTS)",
     "Receptor α1A-adrenérgico (predominante na próstata) e α1D (bexiga, uretra)",
     "urologico"),
    ("Inibidores da 5-Alfa Redutase (5-ARI)",
     "Inibição da 5α-redutase tipo 2 (dutasterida: tipos 1 e 2) → ↓ conversão de testosterona em di-hidrotestosterona (DHT) → ↓ volume prostático 20-30% em 6-12 meses — mais lento que alfa-bloqueadores",
     "5α-redutase tipo 2 (finasterida) e tipos 1+2 (dutasterida) — DHT-dependente",
     "urologico"),
    # ── Hematológico / Renal ─────────────────────────────────────────────────
    ("Agentes Estimuladores de Eritropoiese (AEE)",
     "Mimetismo da eritropoetina endógena → ligação ao receptor EpoR em precursores eritroides na medula óssea → ↑ proliferação e diferenciação eritroide → ↑ hemoglobina; usado na anemia da DRC",
     "Receptor de eritropoetina (EpoR) em eritroblastos da medula óssea",
     "hematologico_renal"),
    ("Suplementos Minerais e Vitamínicos",
     "Reposição de micronutrientes essenciais deficientes (ferro, B12, B9, D) → correção de anemias carenciais e deficiências metabólicas sem mecanismo farmacológico receptor-específico",
     "Receptores de transferrina (ferro), receptores de cobalamina (B12) — reposição fisiológica",
     "hematologico_renal"),
    # ── Ginecológico / Obstetrícia ───────────────────────────────────────────
    ("Ocitócicos e Análogos de Prostaglandina",
     "Ocitocina: estimula receptores OT uterinos → contração do miométrio. Misoprostol (PGE1): ativa receptores EP uterinos → contração + amadurecimento cervical → indicados em indução do parto e HPP",
     "Receptor de ocitocina (OXTR) no miométrio; receptores EP1-4 de prostaglandina E em colo e miométrio",
     "ginecologico"),
    ("Progestogênios",
     "Ligação ao receptor de progesterona (PR) → efeitos gestagênicos: suporte de corpo lúteo, proteção endometrial em TRH, inibição de ovulação e preparação endometrial na reprodução assistida",
     "Receptor de progesterona (PRA e PRB) em endométrio, hipotálamo e hipófise",
     "ginecologico"),
    ("Estrogênios",
     "Ligação ao receptor de estrogênio (ERα/ERβ) → regulação de múltiplos tecidos: osso, cardiovascular, SNC, mucosas; reposição hormonal na menopausa; menor risco trombótico por via transdérmica",
     "Receptor de estrogênio α (ERα) e β (ERβ) em múltiplos tecidos",
     "ginecologico"),
    # ── Dermatológico ────────────────────────────────────────────────────────
    ("Retinoides",
     "Ligação aos receptores RAR e RXR nucleares → regulação da transcrição de genes envolvidos na diferenciação queratinocítica, ↓ sebo (isotretinoína), modulação imune cutânea e antiproliferativa",
     "Receptores de ácido retinoico (RAR-α/β/γ) e RXR — fatores de transcrição nucleares",
     "dermatologico"),
    ("Inibidores de Calcineurina Sistêmicos",
     "Ligação à ciclofilina (ciclosporina) ou FKBP12 (tacrolimus sistêmico) → inibição da calcineurina → ↓ NFAT → ↓ IL-2 e ativação de linfócitos T → imunossupressão potente usada em transplante e autoimunidade grave",
     "Calcineurina (PP2B) via ciclofilina-CsA ou FKBP12-FK506 — ↓ NFAT → ↓ IL-2",
     "dermatologico"),
    # ── Reumatológico adicional ──────────────────────────────────────────────
    ("DMARDs Imunossupressores — Análogos de Purina",
     "Pró-fármaco convertido em 6-mercaptopurina → inibição da síntese de purinas → ↓ proliferação de linfócitos T e B; usado em AR, DII, LES e transplante como agente poupador de corticoide",
     "HGPRT e enzimas da síntese de purinas em linfócitos — azatioprina/6-MP",
     "reumatologico"),
    ("DMARDs — Inibidores de Síntese de Pirimidina",
     "Inibição da di-hidroro-orotato desidrogenase (DHODH) mitocondrial → ↓ síntese de pirimidinas de novo → ↓ proliferação de linfócitos T ativados → efeito DMARD em AR",
     "DHODH (di-hidroro-orotato desidrogenase) mitocondrial em linfócitos T — leflunomida/teriflunomida",
     "reumatologico"),
    ("Antigotas — Inibidores de Polimerização de Microtúbulos",
     "Ligação à β-tubulina → inibição da polimerização de microtúbulos → ↓ migração e ativação de neutrófilos → anti-inflamatório em crise gotosa; sem efeito uricosúrico ou uricostático",
     "β-tubulina em neutrófilos — inibição do fuso mitótico e migração celular (colchicina)",
     "reumatologico"),
    ("Biológicos Anti-Integrina",
     "Bloqueio da integrina α4β7 (vedolizumabe) → ↓ recrutamento de linfócitos para a mucosa intestinal → seletividade GI com menor risco infeccioso sistêmico; 1ª linha biológica em Crohn e RCU",
     "Integrina α4β7 no endotélio vascular intestinal (MAdCAM-1) — vedolizumabe",
     "gastroenterologico"),
    # ── Respiratório adicional ───────────────────────────────────────────────
    ("Inibidores de PDE-4",
     "Inibição da fosfodiesterase-4 → ↑ AMPc intracelular em células inflamatórias → ↓ produção de TNF-α, IL-8 e mediadores pró-inflamatórios → anti-inflamatório oral em DPOC grave com exacerbações",
     "Fosfodiesterase-4 (PDE-4) em macrófagos, neutrófilos e células epiteliais brônquicas — roflumilaste",
     "respiratorio"),
    # ── Neurológico / Psiquiatria ────────────────────────────────────────────
    ("Psicoestimulantes — Inibidores de Recaptação de DA e NE",
     "Bloqueio e reversão do transportador de dopamina (DAT) e noradrenalina (NET) no córtex pré-frontal → ↑ DA e NE sináptica → melhora de atenção, controle inibitório e memória de trabalho no TDAH",
     "DAT (transportador de dopamina) e NET (transportador de noradrenalina) no CPF — metilfenidato/anfetamina",
     "neurologico"),
    # ── Endócrino adicional ──────────────────────────────────────────────────
    ("Inibidores de Lipase Pancreática",
     "Inibição covalente e irreversível das lipases gástrica e pancreática → ↓ hidrólise e absorção de triglicerídeos da dieta em ~30% → balanço calórico negativo; sem ação sistêmica significativa",
     "Lipase pancreática (triacilglicerol lipase) e gástrica no lúmen do trato GI — orlistate",
     "endocrino_metabolico"),
    # ── Cardiovascular / Neuro / Endócrino adicionais (S44) ───────────────────
    ("Glicosídeos Cardíacos (Digitálicos)",
     "Inibição da bomba Na+/K+-ATPase do miócito → ↑ Na+ intracelular → ↑ Ca²⁺ via trocador Na+/Ca²⁺ → inotropismo positivo; efeito vagotônico → ↓ condução no nó AV (controle de frequência)",
     "Na+/K+-ATPase (bomba de sódio-potássio) da membrana do cardiomiócito",
     "cardiovascular"),
    ("Corticosteroides Sistêmicos",
     "Agonismo do receptor de glicocorticoide → transrepressão de genes pró-inflamatórios (NF-κB/AP-1) e transativação de anti-inflamatórios → efeito anti-inflamatório e imunossupressor amplo",
     "Receptor de glicocorticoide (GR) citoplasmático/nuclear",
     "endocrino_metabolico"),
    ("Nitroimidazóis (Antimicrobianos)",
     "Redução do grupo nitro em ambiente anaeróbio → radicais citotóxicos que fragmentam o DNA do microrganismo",
     "DNA de bactérias anaeróbias e protozoários",
     "outros"),
]


# (nome_generico, nome_comercial, classe_nome, via, sus, anvisa_registrado, observacoes)
MEDICAMENTOS = [
    # ── Cardiovascular — IECA ────────────────────────────────────────────────
    ("Enalapril",          "Renitec / Enalapril Genérico",
     "IECA — Inibidores da Enzima Conversora de Angiotensina", "oral", True, True,
     "1ª linha HAS e ICFEr; tosse seca em 10-15%; contraindicado em gestação; monitorar K+ e Cr"),
    ("Captopril",          "Capoten / Captopril Genérico",
     "IECA — Inibidores da Enzima Conversora de Angiotensina", "oral", True, True,
     "Ação curta (2-3x/dia); opção em emergências hipertensivas (sublingual); IC, HAS"),
    ("Ramipril",           "Tritace / Ramipril Genérico",
     "IECA — Inibidores da Enzima Conversora de Angiotensina", "oral", True, True,
     "Indicado em pós-IAM com FE reduzida e nefroproteção em DM — ensaio HOPE"),
    # ── Cardiovascular — BRA ─────────────────────────────────────────────────
    ("Losartana",          "Cozaar / Losartana Genérico",
     "BRA — Bloqueadores do Receptor AT1 de Angiotensina", "oral", True, True,
     "1ª escolha BRA no Brasil (disponível RENAME); também reduz AU; HAS e nefroproteção"),
    ("Valsartana",         "Diovan / Valsartana Genérico",
     "BRA — Bloqueadores do Receptor AT1 de Angiotensina", "oral", True, True,
     "HAS e ICFEr (VAL-HeFT); associado à sacubitril em ARNI (Entresto)"),
    ("Olmesartana",        "Benicar / Olmesartana Genérico",
     "BRA — Bloqueadores do Receptor AT1 de Angiotensina", "oral", True, True,
     "Potente BRA; associado a enteropatia esprue-like em uso prolongado"),
    # ── Cardiovascular — Betabloqueadores ────────────────────────────────────
    ("Metoprolol Succinato", "Seloken ZOK / Metoprolol Genérico",
     "Betabloqueadores", "oral", True, True,
     "β1-seletivo de liberação prolongada; 1ª linha em ICFEr (MERIT-HF); HAS e FA"),
    ("Carvedilol",         "Coreg / Carvedilol Genérico",
     "Betabloqueadores", "oral", True, True,
     "α1+β bloqueio não seletivo; 1ª linha em ICFEr (COPERNICUS); HAS; vasodilatação arterial adicional"),
    ("Bisoprolol",         "Concor / Bisoprolol Genérico",
     "Betabloqueadores", "oral", True, True,
     "β1-seletivo altamente seletivo; 1ª linha em ICFEr (CIBIS-II); ICFEp"),
    ("Atenolol",           "Tenormin / Atenolol Genérico",
     "Betabloqueadores", "oral", True, True,
     "β1-seletivo de curta duração; menos evidência em IC que carvedilol/metoprolol; HAS e angina"),
    ("Propranolol",        "Inderal / Propranolol Genérico",
     "Betabloqueadores", "oral", True, True,
     "Não seletivo β1+β2; profilaxia de enxaqueca, tremor essencial, FA, HAS portal; hipertireoidismo"),
    # ── Cardiovascular — BCC ─────────────────────────────────────────────────
    ("Anlodipino",         "Norvasc / Anlodipino Genérico",
     "BCC Diidropiridínicos — Bloqueadores de Canal de Cálcio", "oral", True, True,
     "Longa ação (t½ 30-50h); HAS e angina crônica; 1ª linha; edema de tornozelos em 10-20%"),
    ("Nifedipino",         "Adalat CC / Nifedipino Genérico",
     "BCC Diidropiridínicos — Bloqueadores de Canal de Cálcio", "oral", True, True,
     "Formulação LP (ação prolongada) para HAS; evitar cápsula de liberação imediata na HAS"),
    ("Verapamil",          "Isoptin / Verapamil Genérico",
     "BCC Não Diidropiridínicos (Fenilalquilaminas / Benzotiazepinas)", "oral", True, True,
     "FA (controle de FC), SVT; evitar com betabloqueadores (bloqueio AV); constipação"),
    ("Diltiazem",          "Cardizem / Diltiazem Genérico",
     "BCC Não Diidropiridínicos (Fenilalquilaminas / Benzotiazepinas)", "oral", True, True,
     "FA (controle de FC), angina vasoespástica; menor cronotropia negativa que verapamil"),
    # ── Cardiovascular — Diuréticos ──────────────────────────────────────────
    ("Hidroclorotiazida",  "Clorana / HCT Genérico",
     "Diuréticos Tiazídicos e Tiazídico-like", "oral", True, True,
     "12,5-25 mg/dia; combinado com IECA/BRA/BCC; risco de hipocalemia, hiperglicemia e hiperuricemia"),
    ("Clortalidona",       "Higrotona / Clortalidona Genérico",
     "Diuréticos Tiazídicos e Tiazídico-like", "oral", True, True,
     "Tiazídico-like de longa ação; superior ao HCTZ em redução de eventos CV (ALLHAT); HAS"),
    ("Furosemida",         "Lasix / Furosemida Genérico",
     "Diuréticos de Alça", "oral/iv", True, True,
     "20-80 mg oral ou IV; IC congestiva; edema; TFGe reduzida; hipocalemia monitorar"),
    ("Espironolactona",    "Aldactone / Espironolactona Genérica",
     "Diuréticos Poupadores de Potássio / Antagonistas de Aldosterona", "oral", True, True,
     "ICFEr (RALES), hiperaldosteronismo, HAS resistente; ginecomastia; monitorar K+ e Cr"),
    ("Eplerenona",         "Inspra",
     "Diuréticos Poupadores de Potássio / Antagonistas de Aldosterona", "oral", False, True,
     "Mais seletivo que espironolactona (menos ginecomastia); pós-IAM com ICFEr (EPHESUS)"),
    # ── Cardiovascular — Nitratos / Outros ───────────────────────────────────
    ("Isossorbida Mononitrato", "Monoket / Isossorbida Mono Genérico",
     "Nitratos Orgânicos", "oral", True, True,
     "Angina estável; esquema de 2x/dia com intervalo de 8-12h livre (janela) para evitar tolerância"),
    ("Nitroglicerina",     "Tridil / NTG (IV e sublingual)",
     "Nitratos Orgânicos", "sublingual/iv", True, True,
     "Crise anginosa (sublingual); IC descompensada/hipertensão grave (IV); não usar com inibidores PDE5"),
    # ── Cardiovascular — Estatinas ───────────────────────────────────────────
    ("Atorvastatina",      "Lipitor / Atorvastatina Genérica",
     "Estatinas — Inibidores da HMG-CoA Redutase", "oral", True, True,
     "Estatina de alta intensidade (40-80 mg); 1ª linha para prevenção secundária; hepatite rara; miopatia"),
    ("Rosuvastatina",      "Crestor / Rosuvastatina Genérica",
     "Estatinas — Inibidores da HMG-CoA Redutase", "oral", True, True,
     "Estatina de alta intensidade (20-40 mg); menos interações CYP3A4; ↑ LDL-R mesmo em hepáticos"),
    ("Sinvastatina",       "Zocor / Sinvastatina Genérica",
     "Estatinas — Inibidores da HMG-CoA Redutase", "oral", True, True,
     "Estatina moderada (20-40 mg); máx 40 mg por risco de miopatia com inibidores CYP3A4; RENAME"),
    # ── Cardiovascular — Fibratos ─────────────────────────────────────────────
    ("Fenofibrato",        "Lipanthyl / Fenofibrato Genérico",
     "Fibratos — Agonistas PPAR-α", "oral", True, True,
     "↓ TG 30-50%, ↑ HDL 10-20%; 1ª linha para hipertrigliceridemia; menos risco de miopatia que genfibrozil"),
    ("Bezafibrato",        "Bezalip / Bezafibrato Genérico",
     "Fibratos — Agonistas PPAR-α", "oral", True, True,
     "TG e HDL; menos disponível no Brasil que fenofibrato; ajuste em DRC"),
    # ── Cardiovascular — Antiagregantes / Anticoagulantes ────────────────────
    ("Ácido Acetilsalicílico (antiagregante)", "AAS Cardio / AAS 100 mg",
     "Antiagregantes Plaquetários — Inibidores de COX-1 (Salicilatos)", "oral", True, True,
     "100 mg/dia em prevenção secundária CV; GI protetivo com IBP se alto risco; não indicado em prevenção primária de rotina (2018-2022)"),
    ("Clopidogrel",        "Plavix / Clopidogrel Genérico",
     "Antiagregantes Plaquetários — Inibidores de P2Y12", "oral", True, True,
     "75 mg/dia; pós-SCA e stent: 12 meses com AAS; AVC/AIT; interação com IBP (omeprazol)"),
    ("Ticagrelor",         "Brilinta",
     "Antiagregantes Plaquetários — Inibidores de P2Y12", "oral", False, True,
     "90 mg 12/12h pós-SCA — superior ao clopidogrel (PLATO); dispneia em 15%; reversível"),
    ("Warfarina",          "Coumadin / Warfarina Genérica",
     "Anticoagulantes — Antagonistas da Vitamina K", "oral", True, True,
     "RNI alvo 2-3 (FA/TVP) ou 2,5-3,5 (prótese mecânica); múltiplas interações; genética CYP2C9"),
    ("Rivaroxabana",       "Xarelto",
     "Anticoagulantes Orais Diretos — Anti-Xa (Rivaroxabana, Apixabana)", "oral", True, True,
     "FA: 20 mg/dia com janta; TVP/TEP: 15 mg 12/12h x 21d → 20 mg/dia; sem RNI; ajuste em DRC"),
    ("Apixabana",          "Eliquis",
     "Anticoagulantes Orais Diretos — Anti-Xa (Rivaroxabana, Apixabana)", "oral", True, True,
     "FA: 5 mg 12/12h (2,5 mg se ≥2 critérios); TVP: 10 mg 12/12h x 7d → 5 mg 12/12h; menos sangramento GI"),
    ("Dabigatrana",        "Pradaxa",
     "Anticoagulantes Orais Diretos — Inibidor Direto de Trombina (Dabigatrana)", "oral", False, True,
     "FA: 150 mg 12/12h; antídoto: idarucizumabe; contraindicado TFGe < 30; não triturar cápsula"),
    # ── Endócrino / Metabólico ───────────────────────────────────────────────
    ("Metformina",         "Glifage / Metformina Genérica",
     "Biguanidas — Metformina", "oral", True, True,
     "1ª linha DM2; iniciar 500 mg → até 2550 mg/dia; suspender se TFGe < 30 ou contraste IV; acidose láctica rara"),
    ("Empagliflozina",     "Jardiance",
     "Inibidores de SGLT-2 — Gliflozinas", "oral", True, True,
     "DM2, ICFEr, ICFEp e DRC: 10 mg/dia; ITU/candidíase genital; cetoacidose euglicêmica rara; hidratação"),
    ("Dapagliflozina",     "Forxiga",
     "Inibidores de SGLT-2 — Gliflozinas", "oral", True, True,
     "DM2/DRC (DAPA-CKD) /ICFEr/ICFEp: 10 mg/dia; não usar TFGe < 25 para DM2; amputação: monitorar"),
    ("Semaglutida SC",     "Ozempic (DM2) / Wegovy (obesidade)",
     "Agonistas de GLP-1 — Análogos de GLP-1", "subcutanea", True, True,
     "DM2: 0,25→0,5→1 mg/semana; obesidade: 2,4 mg/semana; NV, pancreatite rara; teratogênica"),
    ("Liraglutida",        "Victoza (DM2) / Saxenda (obesidade)",
     "Agonistas de GLP-1 — Análogos de GLP-1", "subcutanea", False, True,
     "DM2: 0,6→1,2→1,8 mg/dia; LIDER: ↓ mortalidade CV; obesidade: 3 mg/dia (Saxenda)"),
    ("Sitagliptina",       "Januvia / Sitagliptina Genérica",
     "Inibidores de DPP-4 — Gliptinas", "oral", True, True,
     "DM2: 100 mg/dia (50 mg se TFGe 30-49; 25 mg se < 30); neutro em CV; DRA raras"),
    ("Glibenclamida",      "Daonil / Glibenclamida Genérica",
     "Sulfonilureias", "oral", True, True,
     "DM2: 2,5-20 mg/dia; hipoglicemia mais frequente por meia-vida longa; evitar em idosos e DRC avançada"),
    ("Glicazida MR",       "Diamicron MR / Glicazida Genérica",
     "Sulfonilureias", "oral", True, True,
     "DM2: 30-120 mg/dia; menor risco de hipoglicemia; disponível SUS; pode ser usado em DRC leve"),
    ("Insulina Glargina",  "Lantus / Basaglar",
     "Insulinas e Análogos de Insulina", "subcutanea", True, True,
     "Basal 24h sem pico; DM1/DM2: 0,1-0,4 UI/kg/noite; meta glicemia jejum 80-130 mg/dL"),
    ("Insulina NPH",       "Humulin N / Insulatard / NPH Genérica",
     "Insulinas e Análogos de Insulina", "subcutanea", True, True,
     "Basal de ação intermediária (12-18h); DM1/DM2; 2x/dia usual; disponível SUS; pico às 4-6h"),
    ("Insulina Regular",   "Humulin R / Regular Humana",
     "Insulinas e Análogos de Insulina", "subcutanea/iv", True, True,
     "Prandial + correção; IV em cetoacidose diabética; BOLUS 30 min antes das refeições"),
    ("Insulina Lispro",    "Humalog / Insulina Lispro Genérica",
     "Insulinas e Análogos de Insulina", "subcutanea", True, True,
     "Análogo ultrarrápido; usar imediatamente antes da refeição (0-15 min); DM1 e DM2"),
    ("Levotiroxina",       "Puran T4 / Synthroid / Levotiroxina Genérica",
     "Hormônio Tireoidiano — Levotiroxina (T4)", "oral", True, True,
     "1,6 μg/kg/dia em adultos; em jejum 30 min antes; monitorar TSH a cada 4-6 semanas no início"),
    ("Metimazol",          "Tapazol / Metimazol Genérico",
     "Antitireoidianos — Tionamidas", "oral", True, True,
     "10-30 mg/dia → 5-10 mg/dia manutenção; preferido no Brasil; agranulocitose (0,2-0,5%); hepatite"),
    ("Propiltiouracil",    "PTU",
     "Antitireoidianos — Tionamidas", "oral", True, True,
     "Reservado para 1º trimestre de gestação e crise tireotóxica; hepatotoxicidade mais frequente que metimazol"),
    ("Alopurinol",         "Zyloric / Alopurinol Genérico",
     "Uricostáticos — Inibidores de Xantina Oxidase", "oral", True, True,
     "Iniciar 100 mg/dia, titular 50-100 mg a cada 2-4 semanas; meta AU < 6 mg/dL; ajuste rigoroso em DRC"),
    ("Alendronato",        "Fosamax / Alendronato Genérico",
     "Bisfosfonatos — Inibidores da Reabsorção Óssea", "oral", True, True,
     "70 mg/semana em jejum, com 200 mL de água, permanecer ereto 30 min; esofagite; osteocondrose maxilar"),
    ("Zoledronato",        "Zometa / Aclasta",
     "Bisfosfonatos — Inibidores da Reabsorção Óssea", "iv", False, True,
     "5 mg IV anual (osteoporose) ou 4 mg IV a cada 3-4 semanas (oncológico); nefrotoxicidade; febre pós-infusão"),
    ("Orlistate",          "Xenical / Orlistate Genérico",
     "Inibidores de Lipase Pancreática", "oral", True, True,
     "Inibidor de lipase pancreática; 120 mg 3x/dia com refeições; ↓ absorção de gordura 30%; efeitos GI"),
    # ── Oncológico ───────────────────────────────────────────────────────────
    ("Metotrexato (oncológico)", "MTX oncológico",
     "Antimetabólitos — Análogos de Pirimidina/Purina", "oral/iv", True, True,
     "Dose alta (g/m²) em oncologia com resgate de leucovorin; dose baixa (mg/semana) em reumatologia"),
    ("5-Fluorouracil",     "5-FU",
     "Antimetabólitos — Análogos de Pirimidina/Purina", "iv", True, True,
     "CCR, gástrico, ca mama (FOLFOX, FOLFIRI); cardiotoxicidade (vasoespasmo coronariano)"),
    ("Capecitabina",       "Xeloda",
     "Antimetabólitos — Análogos de Pirimidina/Purina", "oral", True, True,
     "Pró-fármaco oral do 5-FU; síndrome mão-pé; CCR adjuvante e metastático; ca mama"),
    ("Cisplatina",         "Platinol / Cisplatina Genérica",
     "Agentes Alquilantes — Platinos", "iv", True, True,
     "CPNPC, Ca colo útero, gástrico, testicular; nefrotoxicidade (hidratação vigorosa), ototoxicidade"),
    ("Carboplatina",       "Paraplatin / Carboplatina Genérica",
     "Agentes Alquilantes — Platinos", "iv", True, True,
     "Menos nefrotóxica que cisplatina; CPNPC, ovário, pulmão; mielossupressão predominante; área sob curva"),
    ("Oxaliplatina",       "Eloxatin / Oxaliplatina Genérica",
     "Agentes Alquilantes — Platinos", "iv", True, True,
     "FOLFOX para CCR adjuvante e metastático; neuropatia periférica (cumulativa e limitante)"),
    ("Paclitaxel",         "Taxol / Paclitaxel Genérico",
     "Taxanos — Estabilizadores de Microtúbulos", "iv", True, True,
     "Ca mama, CPNPC, ovário; neuropatia periférica; alopecia; hipersensibilidade (pré-medicação)"),
    ("Docetaxel",          "Taxotere / Docetaxel Genérico",
     "Taxanos — Estabilizadores de Microtúbulos", "iv", True, True,
     "Ca mama, CPNPC, gástrico, próstata; retenção hídrica; neuropatia periférica; neutropenia"),
    ("Doxorrubicina",      "Adriamycin / Doxorrubicina Genérica",
     "Antracíclicos — Inibidores de Topoisomerase II", "iv", True, True,
     "DLBCL, LH, Ca mama; cardiotoxicidade cumulativa (dose máx 550 mg/m²); monitorar FE antes"),
    ("Irinotecan",         "Camptosar / Irinotecan Genérico",
     "Antracíclicos — Inibidores de Topoisomerase II", "iv", True, True,
     "FOLFIRI (CCR); diarreia colinérgica aguda e secretória tardia; neutropenia"),
    ("Bevacizumabe",       "Avastin",
     "Anticorpos Monoclonais Oncológicos — Anti-HER2/Anti-EGFR/Anti-CD20/Anti-VEGF", "iv", True, True,
     "CCR, CPNPC, glioblastoma; HAS, proteinúria, perfuração GI, trombose arterial"),
    ("Trastuzumabe",       "Herceptin / Trastuzumabe Biossimilar",
     "Anticorpos Monoclonais Oncológicos — Anti-HER2/Anti-EGFR/Anti-CD20/Anti-VEGF", "iv/sc", True, True,
     "Ca mama e gástrico HER2+; cardiotoxicidade (monitorar FE); uso combinado com QT"),
    ("Rituximabe",         "MabThera / Rituximabe Biossimilar",
     "Anticorpos Monoclonais Oncológicos — Anti-HER2/Anti-EGFR/Anti-CD20/Anti-VEGF", "iv", True, True,
     "DLBCL, LLC, AR, LES vasculite; depleção de células B; reativação HBV (triagem obrigatória)"),
    ("Imatinibe",          "Glivec / Imatinibe Genérico",
     "Inibidores de Tirosina Quinase (TKIs)", "oral", True, True,
     "LMC (BCR-ABL), GIST; náusea, edema periorbital, mielossupressão; interações CYP3A4"),
    ("Osimertinibe",       "Tagrisso",
     "Inibidores de Tirosina Quinase (TKIs)", "oral", False, True,
     "CPNPC EGFR mut (ex19del, L858R) 1ª linha e EGFR T790M 2ª linha; QTc; ILD rara"),
    ("Alectinibe",         "Alecensa",
     "Inibidores de Tirosina Quinase (TKIs)", "oral", False, True,
     "CPNPC ALK-positivo 1ª linha (ALEX trial) e 2ª linha; superior ao crizotinibe em SNC"),
    ("Pembrolizumabe",     "Keytruda",
     "Imunoterapia — Inibidores de Checkpoint (Anti-PD-1/PD-L1/CTLA-4)", "iv", True, True,
     "CPNPC PD-L1+, melanoma, Ca colo útero, Ca mama TN; imunidade relacionada a eventos adversos (irAEs)"),
    ("Nivolumabe",         "Opdivo",
     "Imunoterapia — Inibidores de Checkpoint (Anti-PD-1/PD-L1/CTLA-4)", "iv", True, True,
     "CPNPC, melanoma, CHC (CHECKMATE-459), CCR, LH clássico; irAEs: pneumonite, colite, hepatite"),
    ("Tamoxifeno",         "Nolvadex / Tamoxifeno Genérico",
     "Hormonioterapia Oncológica — Inibidores de Aromatase e SERMs/SERDs", "oral", True, True,
     "Ca mama HR+ pré-menopausa; 20 mg/dia por 5-10 anos; risco TVP e câncer endométrio; fogachos"),
    ("Letrozol",           "Femara / Letrozol Genérico",
     "Hormonioterapia Oncológica — Inibidores de Aromatase e SERMs/SERDs", "oral", True, True,
     "Ca mama HR+ pós-menopausa; 2,5 mg/dia; artralgia, osteoporose; superior ao tamoxifeno em pós-meno"),
    ("Anastrozol",         "Arimidex / Anastrozol Genérico",
     "Hormonioterapia Oncológica — Inibidores de Aromatase e SERMs/SERDs", "oral", True, True,
     "IA não esteroidal pós-menopausa; Ca mama HR+; artralgia; osteoporose"),
    ("Olaparibe",          "Lynparza",
     "Inibidores de PARP", "oral", False, True,
     "Ca mama e ovário BRCA mutado; 300 mg 12/12h; anemia, náusea, fadiga; síndrome mielodisplásica rara"),
    # ── Saúde Mental / Neurológico ───────────────────────────────────────────
    ("Escitalopram",       "Lexapro / Escitalopram Genérico",
     "ISRS — Inibidores Seletivos da Recaptação de Serotonina", "oral", True, True,
     "10-20 mg/dia; 1ª linha depressão e ansiedade; melhor perfil de tolerabilidade ISRS; QTc leve"),
    ("Sertralina",         "Zoloft / Sertralina Genérica",
     "ISRS — Inibidores Seletivos da Recaptação de Serotonina", "oral", True, True,
     "50-200 mg/dia; 1ª linha depressão, TOC, TEPT, transtorno do pânico; diarreia inicial"),
    ("Fluoxetina",         "Prozac / Fluoxetina Genérica",
     "ISRS — Inibidores Seletivos da Recaptação de Serotonina", "oral", True, True,
     "20-60 mg/dia; t½ longa (4-6 dias → norfluoxetina semanas); menor risco de descontinuação"),
    ("Paroxetina",         "Paxil / Paroxetina Genérica",
     "ISRS — Inibidores Seletivos da Recaptação de Serotonina", "oral", True, True,
     "20-60 mg/dia; mais anticolinérgico; transtorno do pânico, TAG; descontinuação rigorosa"),
    ("Venlafaxina",        "Effexor / Venlafaxina Genérica",
     "IRSN — Inibidores da Recaptação de Serotonina e Noradrenalina", "oral", True, True,
     "75-225 mg/dia com refeição; efeito noradrenérgico > 150 mg; HAS dose-dependente; retirada gradual"),
    ("Duloxetina",         "Cymbalta / Duloxetina Genérica",
     "IRSN — Inibidores da Recaptação de Serotonina e Noradrenalina", "oral", True, True,
     "60-120 mg/dia; neuropatia diabética, fibromialgia, depressão, ansiedade; hepatotoxicidade rara"),
    ("Amitriptilina",      "Tryptanol / Amitriptilina Genérica",
     "Antidepressivos Tricíclicos (ADTs)", "oral", True, True,
     "25-150 mg/noite; depressão, fibromialgia, enxaqueca, neuropatia; ECG (QTc), HO; convulsões OD"),
    ("Nortriptilina",      "Pamelor / Nortriptilina Genérica",
     "Antidepressivos Tricíclicos (ADTs)", "oral", True, True,
     "25-150 mg/noite; menos anticolinérgico que amitriptilina; dor neuropática; nível sérico 50-150 ng/mL"),
    ("Haloperidol",        "Haldol / Haloperidol Genérico",
     "Antipsicóticos Típicos — Bloqueadores D2", "oral/iv/im", True, True,
     "5-20 mg/dia; delirium agudo (IV), psicose aguda; EPS frequente; QTc monitorar"),
    ("Risperidona",        "Risperdal / Risperidona Genérica",
     "Antipsicóticos Atípicos — Antagonistas D2/5-HT2A", "oral/im", True, True,
     "2-8 mg/dia; 1ª linha psicose; hiperprolactinemia; injeção depot mensal (Consta); crianças com autismo"),
    ("Olanzapina",         "Zyprexa / Olanzapina Genérica",
     "Antipsicóticos Atípicos — Antagonistas D2/5-HT2A", "oral/im", True, True,
     "10-20 mg/dia; síndrome metabólica significativa (peso, TG, glicemia); antiemétic IV/IM agudo"),
    ("Quetiapina",         "Seroquel / Quetiapina Genérica",
     "Antipsicóticos Atípicos — Antagonistas D2/5-HT2A", "oral", True, True,
     "50-800 mg/dia; psicose, TAB, depressão bipolar; sedação em doses baixas; menos EPS; parkinson"),
    ("Lítio (carbonato)",  "Carbolith / Litiocar",
     "Estabilizadores de Humor — Sais de Lítio", "oral", True, True,
     "300-1800 mg/dia; nível 0,6-1,2 mEq/L; monitorar TSH e Cr 6/6meses; tremor, poliúria; índice terapêutico estreito"),
    ("Ácido Valproico",    "Depakene / Valprato Genérico",
     "Antiepilépticos — Análogos e Moduladores GABAérgicos", "oral", True, True,
     "15-30 mg/kg/dia; epilepsia generalizada, TAB, profilaxia enxaqueca; teratogênico; hepatotoxicidade"),
    ("Carbamazepina",      "Tegretol / Carbamazepina Genérica",
     "Antiepilépticos — Bloqueadores de Canal de Sódio", "oral", True, True,
     "400-1600 mg/dia; epilepsia focal, neuralgia do trigêmeo, TAB; indutor CYP potente; HLA-B*1502"),
    ("Levetiracetam",      "Keppra / Levetiracetam Genérico",
     "Antiepilépticos — Análogos e Moduladores GABAérgicos", "oral/iv", True, True,
     "500-3000 mg/dia 12/12h; 1ª linha focal e generalizada; ajuste em DRC; irritabilidade (10%)"),
    ("Lamotrigina",        "Lamictal / Lamotrigina Genérica",
     "Antiepilépticos — Bloqueadores de Canal de Sódio", "oral", True, True,
     "Titular lentamente (↑ risco Stevens-Johnson se rápido, especialmente com valproato); epilepsia e TAB"),
    ("Oxcarbazepina",      "Trileptal / Oxcarbazepina Genérica",
     "Antiepilépticos — Bloqueadores de Canal de Sódio", "oral", True, True,
     "600-2400 mg/dia; epilepsia focal; menos interações que carbamazepina; hiponatremia (monitorar Na+)"),
    ("Levodopa/Carbidopa", "Prolopa / Sinemet / Levodopa Genérico",
     "Agonistas Dopaminérgicos — Anti-Parkinson", "oral", True, True,
     "100/25 mg 3-4x/dia; mais eficaz em Parkinson; flutuações motor e discinesias a longo prazo"),
    ("Pramipexol",         "Mirapex / Pramipexol Genérico",
     "Agonistas Dopaminérgicos — Anti-Parkinson", "oral", True, True,
     "0,375-4,5 mg/dia; Parkinson inicial (retarda início de levodopa em jovens); sonolência, impulso"),
    ("Donepezila",         "Aricept / Donepezila Genérica",
     "Inibidores de Colinesterase — Antidemenciais", "oral", True, True,
     "5-10 mg/noite; Alzheimer leve-grave; bradicardia sinusal, NV, insônia; não modifica progressão"),
    ("Memantina",          "Ebixa / Memantina Genérica",
     "Inibidores de Colinesterase — Antidemenciais", "oral", True, True,
     "Antagonista NMDA; 10-20 mg/dia; Alzheimer moderado-grave; associar a donepezila; bem tolerada"),
    ("Metilfenidato LP",   "Ritalina LA / Concerta / Venvanse (lisdex)",
     "Psicoestimulantes — Inibidores de Recaptação de DA e NE", "oral", False, True,
     "TDAH: 18-54 mg/dia pela manhã; monitorar PA e FC, apetite, crescimento em crianças; insônia"),
    # ── Respiratório ─────────────────────────────────────────────────────────
    ("Budesonida inalatória", "Pulmicort / Budesonida Genérica",
     "Corticosteroides Inalatórios (ICS)", "inalatoria", True, True,
     "200-800 μg/dia; asma e DPOC com eosinofilia; bocochão para candidiase oral"),
    ("Beclometasona inalatória", "Clenil / Becloforte",
     "Corticosteroides Inalatórios (ICS)", "inalatoria", True, True,
     "100-400 μg/dia; asma; extrafino atravessa vias aéreas pequenas; em RENAME"),
    ("Formoterol",         "Foradil / Oxis / Formoterol Genérico",
     "Beta-2 Agonistas de Longa Ação (LABA)", "inalatoria", True, True,
     "12 μg 12/12h; asma (com ICS) e DPOC; broncodilatador de alívio (início rápido) e manutenção"),
    ("Salmeterol",         "Serevent",
     "Beta-2 Agonistas de Longa Ação (LABA)", "inalatoria", False, True,
     "50 μg 12/12h; asma com ICS e DPOC; nunca como monoterapia em asma"),
    ("Tiotrópio",          "Spiriva",
     "Anticolinérgicos de Longa Ação (LAMA)", "inalatoria", True, True,
     "18 μg/dia (HandiHaler) ou 2,5 μg/dia (Respimat); DPOC 1ª linha; boca seca; glaucoma ângulo fechado"),
    ("Salbutamol",         "Aerolin / Salbutamol Genérico",
     "Beta-2 Agonistas de Curta Ação (SABA)", "inalatoria/nebulizacao", True, True,
     "100-200 μg (1-2 jatos) para crise; SABA SOS em asma e DPOC; taquicardia, tremor"),
    ("Montelucaste",       "Singulair / Montelucaste Genérico",
     "Antileucotrienos — Inibidores de Receptor de Cisteinil-Leucotrieno", "oral", True, True,
     "10 mg/noite (adultos); asma alérgica leve e rinite alérgica; efeitos neuropsiquiátricos (aviso FDA/ANVISA)"),
    ("Roflumilaste",       "Daxas",
     "Inibidores de PDE-4", "oral", False, True,
     "Inibidor de PDE-4; 500 μg/dia para DPOC grave com exacerbações; NV, diarreia, perda de peso; depressão"),
    # ── GI / Hepático ────────────────────────────────────────────────────────
    ("Omeprazol",          "Losec / Omeprazol Genérico",
     "IBP — Inibidores de Bomba de Prótons", "oral/iv", True, True,
     "20-40 mg em jejum 30 min antes de refeição principal; 8 semanas DRGE; H. pylori + ATB"),
    ("Pantoprazol",        "Pantozol / Pantoprazol Genérico",
     "IBP — Inibidores de Bomba de Prótons", "oral/iv", True, True,
     "20-40 mg; menos interação com clopidogrel que omeprazol (não inibe CYP2C19 potentemente)"),
    ("Esomeprazol",        "Nexium / Esomeprazol Genérico",
     "IBP — Inibidores de Bomba de Prótons", "oral/iv", True, True,
     "S-isômero do omeprazol; 20-40 mg; DRGE erosiva grave; mais potente que omeprazol racêmico"),
    ("Mesalazina",         "Asacol / Pentasa / Mesalazina Genérica",
     "Aminossalicilatos (5-ASA)", "oral/retal", True, True,
     "RCU: 4 g/dia oral + 1 g supositório; manutenção 2 g/dia; nefrite instersticial rara; monitorar Cr"),
    ("Sulfassalazina",     "Salazopyrin",
     "Aminossalicilatos (5-ASA)", "oral", True, True,
     "RCU e AR: 2-4 g/dia; pró-fármaco (5-ASA + sulfapiridina); efeitos sulfa; DHFR — contracepção"),
    ("Azatioprina",        "Imuran / Azatioprina Genérica",
     "DMARDs Imunossupressores — Análogos de Purina", "oral", True, True,
     "1,5-3 mg/kg/dia; Crohn, RCU, LES, transplante; hemograma mensal; TPMT deficientes: toxicidade grave"),
    ("Infliximabe",        "Remicade / Infliximabe Biossimilar",
     "Biológicos Anti-TNF", "iv", True, True,
     "5 mg/kg IV semanas 0,2,6 → 8/8 semanas; AR, Crohn, RCU, psoríase, EA; PPD e HBsAg antes"),
    ("Adalimumabe",        "Humira / Adalimumabe Biossimilar",
     "Biológicos Anti-TNF", "subcutanea", True, True,
     "40 mg SC cada 2 semanas; AR, psoríase, Crohn, EA, artrite psoriática; auto-injetor"),
    ("Vedolizumabe",       "Entyvio",
     "Biológicos Anti-Integrina", "iv", True, True,
     "Anti-integrina α4β7 seletivo para GI; Crohn e RCU; segurança infecciosa superior a anti-TNF sistêmico"),
    # ── Reumatológico ────────────────────────────────────────────────────────
    ("Metotrexato (reumatológico)", "MTX Reumatológico",
     "DMARDs Convencionais — Metotrexato", "oral/sc", True, True,
     "10-25 mg/semana + ácido fólico 5 mg/semana; DMARD âncora AR; hepatotóxico; pneumonite intersticial"),
    ("Hidroxicloroquina",  "Plaquinol / HCQ Genérica",
     "Antimaláricos — Hidroxicloroquina", "oral", True, True,
     "5 mg/kg/dia real (máx 400 mg); LES e AR; exame oftalmológico anual (retinopatia > 5 anos)"),
    ("Leflunomida",        "Arava / Leflunomida Genérica",
     "DMARDs — Inibidores de Síntese de Pirimidina", "oral", True, True,
     "20 mg/dia (100 mg/dia por 3 dias dose de ataque opcional); AR; hepatotoxicidade; teratogênica"),
    ("Etanercepte",        "Enbrel / Etanercepte Biossimilar",
     "Biológicos Anti-TNF", "subcutanea", True, True,
     "50 mg SC/semana (ou 25 mg 2x/semana); AR, EA, psoríase; proteína de fusão (TNFR2-Fc)"),
    ("Tocilizumabe",       "Actemra",
     "Inibidores de IL-6 (Tocilizumabe)", "iv/sc", True, True,
     "8 mg/kg IV 4/4 semanas ou 162 mg SC/semana; AR, AI sistêmica juvenil; monitorar TG, transaminases"),
    ("Tofacitinibe",       "Xeljanz",
     "Inibidores de JAK (JAKinibs)", "oral", False, True,
     "5 mg 12/12h; AR e RCU; infecção oportunista (Herpes Zoster); tromboembolismo (10 mg); monitorar CBC"),
    ("Baricitinibe",       "Olumiant",
     "Inibidores de JAK (JAKinibs)", "oral", False, True,
     "2-4 mg/dia; AR e dermatite atópica; TVP/TEP risco monitorar; Herpes Zoster profilaxia"),
    ("Colchicina",         "Colchivida / Colchicina Genérica",
     "Antigotas — Inibidores de Polimerização de Microtúbulos", "oral", True, True,
     "Crise gout: 1 mg + 0,5 mg após 1h; profilaxia: 0,5 mg 12/12h; pericardite; ajuste em DRC e CYP3A4"),
    ("Raloxifeno",         "Evista",
     "SERMs — Moduladores Seletivos de Receptores de Estrogênio", "oral", False, True,
     "60 mg/dia; osteoporose pós-menopausa; ↓ ca mama; ↑ risco TVP e fogachos; alternativa ao alendronato"),
    # ── Dermatológico ────────────────────────────────────────────────────────
    ("Tacrolimus tópico",  "Protopic",
     "Inibidores de Calcineurina Tópicos (Tacrolimus/Pimecrolimus)", "topica", False, True,
     "0,03% (crianças 2-15 anos) e 0,1% (adultos); dermatite atópica e vitiligo; ardência inicial"),
    ("Ciclosporina",       "Sandimmun / Neoral",
     "Inibidores de Calcineurina Sistêmicos", "oral", True, True,
     "2-5 mg/kg/dia; psoríase grave, AR refratária, transplante; nefrotóxica; HAS; monitorar Cr"),
    ("Isotretinoína",      "Roacutan / Isotretinoína Genérica",
     "Retinoides", "oral", False, True,
     "0,5-1 mg/kg/dia por 5-6 meses; acne grave; teratogênico (2 contraceptivos obrigatórios); PPT"),
    # ── Renal / Urológico ────────────────────────────────────────────────────
    ("Tansulosina",        "Omnic / Tansulosina Genérica",
     "Alfa-Bloqueadores — HPB", "oral", True, True,
     "0,4 mg/dia após desjejum; HPB sintomática; hipotensão ortostática; ejaculação retrógrada"),
    ("Dutasterida",        "Avodart / Dutasterida Genérica",
     "Inibidores da 5-Alfa Redutase (5-ARI)", "oral", False, True,
     "0,5 mg/dia; HPB (próstata > 40 g); volume ↓ 20-30% em 6-12 meses; PSA ÷ 2 no seguimento"),
    ("Finasterida",        "Proscar / Finasterida Genérica",
     "Inibidores da 5-Alfa Redutase (5-ARI)", "oral", True, True,
     "5 mg/dia HPB ou 1 mg/dia (Propecia) para alopecia androgênica; 6-12 meses resposta"),
    ("Darbepoetina alfa",  "Aranesp",
     "Agentes Estimuladores de Eritropoiese (AEE)", "subcutanea/iv", True, True,
     "Agente estimulador de eritropoiese; DRC: 0,45 μg/kg SC semanal; alvo Hb 10-12 g/dL; HAS, trombose"),
    ("Hidroxiureia",       "Hydrea / Hidroxiureia Genérica",
     "Antimetabólitos — Análogos de Pirimidina/Purina", "oral", True, True,
     "Falciforme: 15-35 mg/kg/dia; ↑ HbF, ↓ crises; monitorar CBC; policitemia vera; LMC"),
    # ── Ginecológico ─────────────────────────────────────────────────────────
    ("Progesterona micronizada", "Utrogestan",
     "Progestogênios", "oral/vaginal", False, True,
     "TRH: 200 mg/noite (proteção endometrial); suporte fase lútea em reprodução assistida"),
    ("Estradiol transdérmico", "Estradot / Climara",
     "Estrogênios", "transdermico", False, True,
     "TRH pós-menopausa; menor risco trombótico que VO; adesivo 25-100 μg/dia; sempre com progestógeno"),
    ("Sulfato de magnésio",  "MgSO4 IV",
     "Antiepilépticos — Análogos e Moduladores GABAérgicos", "iv", True, True,
     "Pré-eclâmpsia grave e eclâmpsia: ataque 4 g IV lento → manutenção 1-2 g/h; antídoto: gluconato de Ca"),
    ("Ocitocina",          "Syntocinon / Ocitocina Genérica",
     "Ocitócicos e Análogos de Prostaglandina", "iv/im", True, True,
     "Indução do parto, prevenção e tratamento de HPP; 10 UI IM após saída dos ombros (profilaxia)"),
    ("Misoprostol",        "Cytotec / Misoprostol Genérico",
     "Ocitócicos e Análogos de Prostaglandina", "sublingual/vaginal", True, True,
     "Análogo PGE1; HPP: 800 μg sublingual; maturação cervical; aborto; proteção gástrica com AINE"),
    ("Sulfato Ferroso",    "Noripurum / Sulfato Ferroso Genérico",
     "Suplementos Minerais e Vitamínicos", "oral", True, True,
     "300 mg 3x/dia em jejum; anemia ferropriva; tomar com suco de vitamina C; fezes escuras, constipação"),
    ("Cianocobalamina",    "Cyanokit / Cianocobalamina Genérica",
     "Suplementos Minerais e Vitamínicos", "im/oral", True, True,
     "B12 def: 1000 μg IM diário x 7d → semanal x 4sem → mensal (indefinido para perniciosa); VO: 2000 μg/dia"),
    # ── Fármacos crônicos ausentes do catálogo — cadastro S44 ─────────────────
    ("Digoxina", "Digoxina / Digoxina Genérico",
     "Glicosídeos Cardíacos (Digitálicos)", "oral", True, True,
     "IC com FE reduzida e controle de frequência na FA; RENAME (comp. 0,25 mg / elixir 0,05 mg/mL); "
     "janela terapêutica estreita — monitorar digoxinemia, K+ e função renal"),
    ("Fenitoína", "Hidantal / Fenitoína Genérica",
     "Antiepilépticos — Bloqueadores de Canal de Sódio", "oral", True, True,
     "Epilepsia (crises focais e tônico-clônicas); RENAME; cinética não linear — monitorar níveis séricos; "
     "hiperplasia gengival; indutor enzimático (CYP450)"),
    ("Prednisona", "Meticorten / Prednisona Genérico",
     "Corticosteroides Sistêmicos", "oral", True, True,
     "Corticoide sistêmico anti-inflamatório/imunossupressor; RENAME (comp. 5/20 mg); "
     "desmame gradual se uso prolongado"),
    # Registrado no domínio crônico para hospedar sua interação clinicamente
    # relevante (álcool → reação dissulfiram-like); RENAME. Uso agudo, não crônico.
    ("Metronidazol", "Flagyl / Metronidazol Genérico",
     "Nitroimidazóis (Antimicrobianos)", "oral", True, True,
     "Antimicrobiano para anaeróbios e protozoários (RENAME); evitar álcool durante o uso e por "
     "48h após (reação dissulfiram-like); sabor metálico, neuropatia periférica em uso prolongado"),
    # Formulação TÓPICA (rosácea): catalogada à parte para não herdar a via oral
    # nem a interação sistêmica com álcool (absorção sistêmica desprezível).
    ("Metronidazol tópico", "Rozex / Metronidazol Gel",
     "Nitroimidazóis (Antimicrobianos)", "tópico", True, True,
     "Gel/creme 0,75-1% para rosácea papulopustulosa (1-2x/dia); absorção sistêmica desprezível — "
     "não carrega a interação com álcool da forma oral; anti-inflamatório tópico de 1ª linha"),
]
