# Critérios Diagnósticos — Patologias Fúngicas (IDs 144–167)
# Fontes: MS/PCDT 2022/2023, MS-SVS, SBI 2023, SBPT 2022, SBD 2022,
#          SBGG, ANVISA, IDSA 2016 (adaptada) — diretrizes brasileiras mais recentes

CRITERIOS_FUNGICAS = [
    {
        "patologia_nome": "Paracoccidioidomicose (Blastomicose Sul-Americana)",
        "criterios": [
            {
                "nome": "Exame micológico direto com elementos fúngicos típicos (célula-piloto / roda de leme) em escarro, lavado broncoalveolar ou raspado de lesão",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "KOH 10–20% ou calcofluor: células esféricas de parede dupla birrefringente com brotamentos múltiplos periféricos (aspecto de 'roda de leme' ou 'Mickey Mouse')",
                "valor_referencia": "Célula-piloto com brotamentos múltiplos",
                "fonte": "MS/PCDT Paracoccidioidomicose 2017; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Cultura em Mycosel/Sabouraud com crescimento de P. brasiliensis (fase micelial) ou isolamento",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Crescimento lento (15–30 dias) a 25°C; dimorfismo: forma micelial (ambiente) e leveduriforme (37°C/hospedeiro)",
                "valor_referencia": "Crescimento de P. brasiliensis",
                "fonte": "MS/PCDT PCM 2017",
                "ordem": 2,
            },
            {
                "nome": "Sorologia (imunodifusão dupla ou ELISA) anti-P. brasiliensis positiva com título ≥ 1:8",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Imunodifusão (ID): banda de identidade com linha de precipitação = diagnóstico; títulos > 1:8 indicam doença ativa",
                "valor_referencia": "ID positivo ou título ≥ 1:8",
                "fonte": "MS/PCDT PCM 2017",
                "ordem": 3,
            },
            {
                "nome": "Lesões mucosas orofaríngeas (estomatite moreira) + infiltrado pulmonar bilateral + adenomegalia",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Forma crônica (adulto): lesões mucosas ulcerovacuolares; PCM aguda (juvenil): linfadenopatia generalizada, hepatoesplenomegalia",
                "valor_referencia": None,
                "fonte": "MS/PCDT PCM 2017",
                "ordem": 4,
            },
            {
                "nome": "Nexo epidemiológico: trabalhador rural em áreas endêmicas (Sul, Sudeste, Centro-Oeste do Brasil)",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "PCM: endêmica na América Latina (Brasil tem 80% dos casos mundiais); reativação de foco primário pulmonar",
                "valor_referencia": None,
                "fonte": "MS/PCDT PCM 2017; SBI 2023",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Histoplasmose (Doença de Darling)",
        "criterios": [
            {
                "nome": "Cultura ou exame direto com Histoplasma capsulatum em material clínico (escarro, LBA, medula, sangue)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Leveduras intracelulares pequenas (2–4 µm) em macrófagos; Giemsa ou PAS evidencia leveduras ovais intracelulares",
                "valor_referencia": "H. capsulatum identificado",
                "fonte": "MS/PCDT Histoplasmose; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Antígeno de Histoplasma na urina ou soro (Histoplasma Ag ELISA) positivo",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Sensibilidade 90% em histoplasmose disseminada; 70% na pulmonar grave; método de referência para diagnóstico rápido",
                "valor_referencia": "Ag Histoplasma positivo",
                "fonte": "SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Sorologia (imunodifusão, fixação de complemento) com banda H ou M ou títulos ≥ 1:32",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Banda H: infecção ativa/grave; banda M: infecção passada ou ativa; FC ≥ 1:32 indica infecção ativa",
                "valor_referencia": "Banda H ou FC ≥ 1:32",
                "fonte": "SBI 2023",
                "ordem": 3,
            },
            {
                "nome": "Nexo epidemiológico: exposição a morcegos, aves, cavernas, demolições em área endêmica",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "H. capsulatum em solo com guano de morcego e aves; endêmica no Brasil (Nordeste, Centro-Oeste, regiões de cavernas)",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Criptococose (Meningite Criptocócica e Forma Pulmonar)",
        "criterios": [
            {
                "nome": "Tinta da China (nanquim) em LCR positivo: leveduras com cápsula refringente",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Visualização direta de leveduras encapsuladas em LCR; sensibilidade 80% em HIV (cápsula volumosa); padrão de 'halo'",
                "valor_referencia": "Leveduras encapsuladas ao nanquim",
                "fonte": "MS/PCDT Criptococose 2018; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Antígeno criptocócico (CrAg) no LCR, soro ou urina positivo (ELISA ou aglutinação pelo látex)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "CrAg tem sensibilidade > 99% e especificidade > 95%; padrão-ouro diagnóstico no LCR; títulos altos indicam doença grave",
                "valor_referencia": "CrAg positivo",
                "fonte": "MS/PCDT Criptococose 2018",
                "ordem": 2,
            },
            {
                "nome": "Cultura de LCR ou hemocultura positiva para Cryptococcus neoformans/gattii",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Crescimento em Sabouraud; colonies marrons em ágar birdseed (niger); levedura de gemulação única",
                "valor_referencia": "Crescimento de Cryptococcus",
                "fonte": "MS/PCDT Criptococose 2018",
                "ordem": 3,
            },
            {
                "nome": "Contexto de imunodeficiência grave: HIV/CD4 < 100, transplante, corticóide",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "C. neoformans: imunocomprometidos (HIV). C. gattii: imunocompetentes em áreas tropicais",
                "valor_referencia": "CD4 < 100/mm³",
                "fonte": "MS/PCDT Criptococose 2018",
                "ordem": 4,
            },
            {
                "nome": "Pressão de abertura do LCR ≥ 25 cmH₂O (hipertensão intracraniana)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Hipertensão intracraniana (HIC) > 25 cmH₂O em > 50% dos casos; causa de mortalidade precoce; manejo com punções de alívio",
                "valor_referencia": "Pressão LCR ≥ 25 cmH₂O",
                "fonte": "MS/PCDT Criptococose 2018",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Lobomicose (Lacaziose — Doença de Jorge Lobo)",
        "criterios": [
            {
                "nome": "Exame histopatológico com leveduras de Lacazia loboi em cadeia (aspecto de 'roda de leme' sem brotamentos múltiplos simultâneos)",
                "categoria": "histopatologico",
                "tipo": "obrigatorio",
                "descricao": "Biópsia de lesão: histiócitos com leveduras em cadeia (aspecto de contas de rosário); GMS/PAS positivo; não há cultura disponível",
                "valor_referencia": "Leveduras em cadeia ao GMS/PAS",
                "fonte": "SBI 2023; SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Lesões cutâneas queloideanas (nódulos e placas queloides) em MMII ou tronco, de progressão lenta",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesões polimorfas: queloideanas, nodulares, verrucosas, ulceradas; assintomáticas ou levemente pruriginosas; progressão lenta por anos",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Nexo epidemiológico: comunidades indígenas ou populações ribeirinhas na Amazônia brasileira e colombiana",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Endêmica na Amazônia; Brasil tem > 90% dos casos mundiais; associação com golfinhos (Tursiops truncatus)",
                "valor_referencia": None,
                "fonte": "SBD 2022; SBI 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Candidemia e Candidíase Invasiva",
        "criterios": [
            {
                "nome": "Hemocultura positiva para Candida spp. (candida não-albicans ou albicans)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Candidemia: ≥ 1 hemocultura positiva; identificação de espécie obrigatória (C. albicans, C. glabrata, C. tropicalis, C. parapsilosis, C. krusei, C. auris)",
                "valor_referencia": "≥ 1 hemocultura positiva",
                "fonte": "ANVISA 2023; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Fatores de risco: cateter venoso central, nutrição parenteral, neutropenia, cirurgia abdominal maior, antibioticoterapia prolongada",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "CVC é o principal fator de risco; UTI cirúrgica > clínica; Candida tropicalis em neutropênicos; C. parapsilosis em neonatos",
                "valor_referencia": None,
                "fonte": "ANVISA 2023; SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Beta-D-glucano (1,3-β-D-glucana) sérico > 80 pg/mL (marcador de infecção fúngica invasiva)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Sensibilidade 70–80% para candidíase invasiva; não específico para Candida (positivo em PCP, aspergilose); negativo tem alto VPN",
                "valor_referencia": "> 80 pg/mL",
                "fonte": "SBI 2023",
                "ordem": 3,
            },
            {
                "nome": "Ecocardiograma (ETE) para excluir endoftalmite e endocardite (fundo de olho obrigatório)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Fundo de olho obrigatório em todas as candidemias (excluir endoftalmite); ETE se bacteremia persistente > 72h",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Candidíase Orofaríngea (Sapinho / Muguete)",
        "criterios": [
            {
                "nome": "Placas brancas cremosas removíveis na mucosa oral com base eritematosa",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Pseudomembranosa: placas brancas destacáveis à espátula (muguete clássico). Eritematosa: áreas vermelhas no palato",
                "valor_referencia": None,
                "fonte": "MS/PCDT HIV 2023; SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Exame direto com KOH/Gram positivo para blastosporos e pseudo-hifas",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Raspado de lesão: blastosporos de 3–4 µm com pseudo-hifas ao KOH ou Gram; diagnóstico confirmado na maioria dos casos",
                "valor_referencia": "Blastosporos e pseudo-hifas",
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Fator predisponente: imunossupressão (HIV/CD4 < 200), antibiótico sistêmico, corticóide inalatório, prótese dentária",
                "categoria": "epidemiologico",
                "tipo": "suporte",
                "descricao": "Doença indicadora de AIDS em PVHIV; corticóide inalatório sem higiene bucal; xerostomia em idosos",
                "valor_referencia": None,
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Candidíase Vaginal (Vulvovaginite por Candida)",
        "criterios": [
            {
                "nome": "Sintomas clínicos: prurido vulvar intenso + leucorreia branca grumosa (coalho) + eritema vulvar",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Leucorreia esbranquiçada espessa sem odor (diferencia de vaginose bacteriana); prurido intenso; disúria externa; dispareunia",
                "valor_referencia": None,
                "fonte": "MS/PCDT IST 2022; FEBRASGO 2023",
                "ordem": 1,
            },
            {
                "nome": "pH vaginal < 4,5 (ácido — normal para candidíase; alcalino sugere vaginose bacteriana ou tricomoníase)",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "pH ácido normal é característico da candidíase; pH > 4,5 afasta candidíase como causa única",
                "valor_referencia": "pH < 4,5",
                "fonte": "MS/PCDT IST 2022",
                "ordem": 2,
            },
            {
                "nome": "Exame a fresco ou KOH com blastosporos e pseudo-hifas de Candida",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "KOH 10%: dissolve células epiteliais, evidencia fungo; pseudo-hifas = formas invasivas associadas a sintomas",
                "valor_referencia": "Pseudo-hifas ao KOH",
                "fonte": "MS/PCDT IST 2022",
                "ordem": 3,
            },
            {
                "nome": "Cultura vaginal para Candida com identificação de espécie (casos recorrentes ou refratários)",
                "categoria": "microbiologico",
                "tipo": "suporte",
                "descricao": "C. albicans (85%); C. glabrata e C. krusei resistentes ao fluconazol (indicar boric acid/nistatina); indicada em candidíase recorrente (≥ 4 episódios/ano)",
                "valor_referencia": "Identificação de espécie",
                "fonte": "MS/PCDT IST 2022; FEBRASGO 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Candidíase Esofágica",
        "criterios": [
            {
                "nome": "Endoscopia digestiva alta com plaques brancas e friáveis na mucosa esofágica",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "EDA: placas brancas aderentes na mucosa esofágica; eritema; raramente erosões ou úlceras; doença indicadora de AIDS",
                "valor_referencia": None,
                "fonte": "MS/PCDT HIV 2023; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Biópsia esofágica com blastosporos/pseudo-hifas em histopatologia",
                "categoria": "histopatologico",
                "tipo": "maior",
                "descricao": "PAS ou GMS na biópsia: pseudo-hifas de Candida invadindo epitélio; confirma diagnóstico e exclui outras causas",
                "valor_referencia": "Pseudo-hifas em biópsia",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 2,
            },
            {
                "nome": "Disfagia ou odinofagia em paciente imunossuprimido (HIV/CD4 < 100) — diagnóstico empírico é aceitável",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Em PVHIV com CD4 < 100 e candidíase oral + disfagia: tratamento empírico com fluconazol é orientação do MS/PCDT",
                "valor_referencia": "CD4 < 100",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Aspergilose Invasiva (Pulmonar e Disseminada)",
        "criterios": [
            {
                "nome": "TC de tórax com sinal do halo (nódulo com halo em vidro fosco) ou sinal do crescente aéreo",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Sinal do halo: nódulo denso com halo de vidro fosco (hemorrágico) — precoce. Sinal do crescente: necrose central — tardio",
                "valor_referencia": "Sinal do halo ou crescente aéreo",
                "fonte": "SBI 2023; SBPT 2022",
                "ordem": 1,
            },
            {
                "nome": "Galactomanana sérica ou em LBA positiva (≥ 0,5 no soro; ≥ 1,0 no LBA)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Galactomanana: polissacarídeo da parede de Aspergillus; ELISA; índice ≥ 0,5 (soro) em 2 amostras = positivo",
                "valor_referencia": "GM ≥ 0,5 (soro) ou ≥ 1,0 (LBA)",
                "fonte": "SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Cultura ou histopatologia com hifas septadas de ângulo agudo (45°) em material clínico",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Hifas hialinas septadas com ramificação dicotômica a 45°; GMS em histologia; cultura em Sabouraud (crescimento rápido)",
                "valor_referencia": "Hifas de Aspergillus identificadas",
                "fonte": "SBI 2023",
                "ordem": 3,
            },
            {
                "nome": "Neutropenia profunda (< 500/mm³ por > 10 dias) ou corticóide ≥ 0,3 mg/kg/dia por > 3 semanas",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Neutropenia prolongada é o principal fator de risco; transplante de medula, transplante sólido, HIV avançado",
                "valor_referencia": "Neutrófilos < 500/mm³",
                "fonte": "SBI 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Aspergilose Broncopulmonar Alérgica (ABPA)",
        "criterios": [
            {
                "nome": "Critérios de Patterson 2016 (revisados): 3 critérios obrigatórios + ≥ 2 adicionais",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Obrigatórios: (1) condição predisponente (asma/FC); (2) IgE total > 1.000 UI/mL; (3) reação IgE específica anti-Aspergillus. Adicionais: precipitinas IgG anti-Aspergillus, eosinofilia, infiltrado pulmonar, bronquiectasias centrais",
                "valor_referencia": "3 obrigatórios + ≥ 2 adicionais",
                "fonte": "SBPT 2022; Patterson KC et al. 2016",
                "ordem": 1,
            },
            {
                "nome": "IgE total sérica > 1.000 UI/mL e IgE/IgG específica anti-A. fumigatus positivos",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "IgE total marcadamente elevada; skin prick test positivo para Af ou IgE específica > 0,35 kU/L",
                "valor_referencia": "IgE total > 1.000 UI/mL",
                "fonte": "SBPT 2022",
                "ordem": 2,
            },
            {
                "nome": "TC de tórax com bronquiectasias centrais, impacções mucóides ('dedo de luva') ou infiltrados recorrentes",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Bronquiectasias dos lobos superiores; impacções mucóides com atenuação alta (hiperdensas) são patognomônicas de ABPA",
                "valor_referencia": None,
                "fonte": "SBPT 2022",
                "ordem": 3,
            },
            {
                "nome": "Eosinofilia periférica > 500/mm³ (eosinofilia sangüínea)",
                "categoria": "laboratorial",
                "tipo": "menor",
                "descricao": "Eosinofilia presente em > 70% dos casos; pode estar suprimida pelo corticóide",
                "valor_referencia": "Eosinófilos > 500/mm³",
                "fonte": "SBPT 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Aspergiloma Pulmonar",
        "criterios": [
            {
                "nome": "TC de tórax com bola fúngica (fungus ball) em cavidade pré-existente com sinal do menisco ou do ar crescente",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Sinal do menisco/ar crescente: massa redonda ou oval em cavidade com espaço aéreo circundante; mobilidade ao decúbito confirma",
                "valor_referencia": "Fungus ball em cavidade",
                "fonte": "SBPT 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "IgG precipitante anti-Aspergillus fumigatus positivo (≥ 1:8 por imunodifusão)",
                "categoria": "laboratorial",
                "tipo": "obrigatorio",
                "descricao": "Precipitinas IgG (não IgE): positivas em > 90% dos aspergilomas; diferencia de ABPA (onde IgE é mais importante)",
                "valor_referencia": "Precipitinas IgG ≥ 1:8",
                "fonte": "SBPT 2022",
                "ordem": 2,
            },
            {
                "nome": "Cavidade pulmonar pré-existente (TB sequelada, sarcoidose, DPOC, bronquiectasia)",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Aspergiloma é complicação de cavidade pulmonar crônica; TB é a principal causa de cavidade no Brasil",
                "valor_referencia": None,
                "fonte": "SBPT 2022",
                "ordem": 3,
            },
            {
                "nome": "Hemoptise recorrente (sinal clínico mais comum e grave do aspergiloma)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Hemoptise em 50–80% dos casos; pode ser maciça e fatal; tosse e dispneia também frequentes",
                "valor_referencia": None,
                "fonte": "SBPT 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Mucormicose / Zigomicose (Rinocerebral, Pulmonar, Cutânea)",
        "criterios": [
            {
                "nome": "Histopatologia com hifas largas, não-septadas ou paucisseptadas, de ângulo reto (90°), em biópsia tecidual",
                "categoria": "histopatologico",
                "tipo": "obrigatorio",
                "descricao": "Hifas irregulares, largas (10–20 µm), angioinvasivas com trombose e necrose; HE, GMS ou coloração de prata; padrão-ouro",
                "valor_referencia": "Hifas largas não-septadas a 90°",
                "fonte": "SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "TC de seios paranasais ou crânio com destruição de estruturas ósseas + necrose de tecidos moles (rinocerebral)",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Forma rinocerebral (mais frequente no Brasil): velamento de seios, destruição óssea, exoftalmia, necrose; extensão intracraniana",
                "valor_referencia": "Destruição óssea na TC",
                "fonte": "SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Diabetes mellitus descompensado com cetoacidose (principal fator de risco) ou neutropenia profunda",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "DM (cetoacidose) = 50% dos casos; transplante de medula, corticóide, desferoxamina; voriconazol predispõe",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 3,
            },
            {
                "nome": "Lesão necrótica rino-orbital de evolução rápida: escara preta na mucosa nasal, nariz, palato ou órbita",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Escara negra na mucosa = necrose isquêmica por invasão vascular; exoftalmia por comprometimento da órbita; prognóstico grave",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Esporotricose (Cutânea Linfangítica, Cutânea Fixa e Disseminada)",
        "criterios": [
            {
                "nome": "Cultura de secreção ou biópsia positiva para Sporothrix schenckii (ou S. brasiliensis)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "S. brasiliensis é a espécie prevalente no Brasil; crescimento em Sabouraud a 25°C (fase micelial) e 37°C (fase leveduriforme)",
                "valor_referencia": "Crescimento de Sporothrix",
                "fonte": "MS/SVS Esporotricose 2022; SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Forma linfangítica: cadeia de lesões nodulares ulceradas ao longo do trajeto linfático (padrão esporotricoide)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesão primária no ponto de inoculação; disseminação linfangítica com nódulos secundários lineares — padrão clínico típico",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Nexo epidemiológico: arranhadura ou mordida de gato, contato com solo/espinhos de rosas",
                "categoria": "epidemiologico",
                "tipo": "maior",
                "descricao": "Epidemia urbana por S. brasiliensis transmitida por gatos no Rio de Janeiro desde 1998; notificação compulsória no estado",
                "valor_referencia": None,
                "fonte": "MS/SVS 2022; SBD 2022",
                "ordem": 3,
            },
            {
                "nome": "Histopatologia com granuloma supurativo e asteroides de Splendore-Hoeppli (corpos asteroides)",
                "categoria": "histopatologico",
                "tipo": "suporte",
                "descricao": "Corpúsculos asteroides: fragmentos de hifa com material eosinofílico radiante em torno; presente em < 30% das biópsias",
                "valor_referencia": "Asteroides de Splendore-Hoeppli",
                "fonte": "SBD 2022",
                "ordem": 4,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Cromoblastomicose",
        "criterios": [
            {
                "nome": "Exame direto ou histopatologia com células muriformes (corpos fumagoides/esclerotias — células de Medlar)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Células muriformes (células de Medlar): células acastanhadas, esféricas, septadas, com divisão por fissão; patognomônicas",
                "valor_referencia": "Células muriformes identificadas",
                "fonte": "SBD 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Lesões verrucosas, nodulares ou placas em membros inferiores de evolução lenta (anos)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesão inicial: pequena pápula eritematosa; evolução lenta (décadas) para verrucosidade extensa; MMII são os mais afetados",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Cultura com identificação de agente (F. pedrosoi, C. carrionii, P. verrucosa)",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "F. pedrosoi é o mais prevalente no Brasil; hifas dematiaceas acastanhadas em meio de cultura",
                "valor_referencia": "Agente dematiaceo identificado",
                "fonte": "SBD 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Micetoma Fúngico (Eumicetoma)",
        "criterios": [
            {
                "nome": "Tríade clínica: tumor + trajetos fistulosos + grânulos no exsudato",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Tríade patognomônica: tumefação localizada + fístulas com drenagem + grânulos no pus (negros: eumicetoma; brancos/amarelos: actinomicetoma)",
                "valor_referencia": None,
                "fonte": "OMS NTD; SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Exame microscópico dos grânulos: hifas largas com filamentos agrupados (eumicetoma) vs filamentos finos < 1 µm (actinomicetoma)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Grânulos pretos: Madurella mycetomatis (eumicetoma mais comum). Hifas largas (filamentos 2–4 µm) distinguem de actinomicetoma",
                "valor_referencia": "Hifas largas > 2 µm",
                "fonte": "OMS NTD; SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "RX, USG ou RM com destruição óssea cavitária, cavidades hiperecoicas, espessamento cortical",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "RM: 'dot-in-circle sign' — grânulos como pontos hipointensos em meio a cavidade hiperintensa; destruição óssea tardia",
                "valor_referencia": "Dot-in-circle na RM",
                "fonte": "OMS NTD; SBD 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Feohifomicose",
        "criterios": [
            {
                "nome": "Histopatologia com hifas dematiaceas acastanhadas (melanizadas) em tecido",
                "categoria": "histopatologico",
                "tipo": "obrigatorio",
                "descricao": "Coloração de Fontana-Masson (melanina) ou HE: hifas pigmentadas acastanhadas em paredes; diferenciar de cromoblastomicose (ausência de células muriformes)",
                "valor_referencia": "Hifas dematiaceas no tecido",
                "fonte": "SBD 2022; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Cultura com identificação de agente dematiáceo (Exophiala, Alternaria, Curvularia, Bipolaris)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Crescimento de colônia escura a preta em Sabouraud; identificação morfológica e molecular (ITS sequencing)",
                "valor_referencia": "Agente dematiáceo identificado",
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Lesão subcutânea, sinusal ou cerebral em imunossuprimido ou após trauma em área contaminada",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Formas: subcutânea (cistos); sinusal (pólipos); cerebral em imunossuprimidos; trauma como porta de entrada comum",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Fusariose (Hialohifomicose por Fusarium)",
        "criterios": [
            {
                "nome": "Hemocultura ou cultura de biópsia positiva para Fusarium spp.",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Fusarium: hifas hialinas septadas; microconídios ovais em monofialides em agrupamentos; Fusariose disseminada = hemocultura + positiva (40–70%)",
                "valor_referencia": "Fusarium identificado",
                "fonte": "SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Lesões cutâneas disseminadas dolorosas (nódulos eritematosos) com necrose central em neutropênico",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesões angioinvasivas com necrose central ('alvo') em múltiplos sítios; fungo único que causa lesões cutâneas + bacteremia em neutropênicos",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Neutropenia profunda (< 100/mm³) ou transplante de medula óssea como contexto",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "Fusariose disseminada exclusiva de neutropênicos graves; mortalidade > 70% sem recuperação de neutrófilos",
                "valor_referencia": "Neutrófilos < 100/mm³",
                "fonte": "SBI 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Rinossinusite Fúngica (Invasiva e Alérgica)",
        "criterios": [
            {
                "nome": "TC ou RM de seios paranasais com erosão óssea e invasão de estruturas vizinhas (forma invasiva)",
                "categoria": "imagem",
                "tipo": "obrigatorio",
                "descricao": "Rinossinusite fúngica invasiva (RSFI): erosão óssea, extensão orbitária ou intracraniana na TC; hipossinal T2 na RM (característico)",
                "valor_referencia": "Erosão óssea na TC",
                "fonte": "SBI 2023; CFM",
                "ordem": 1,
            },
            {
                "nome": "Biópsia com hifas de Aspergillus ou Mucor em tecido sinonasal (invasão vascular e necrose)",
                "categoria": "histopatologico",
                "tipo": "obrigatorio",
                "descricao": "Invasiva: hifas angioinvasivas com trombose e necrose tecidual; diferenciar Aspergillus (septadas) de Mucor (não-septadas)",
                "valor_referencia": "Hifas invasivas em biópsia",
                "fonte": "SBI 2023",
                "ordem": 2,
            },
            {
                "nome": "Contexto de imunodeficiência grave ou DM com cetoacidose (RSFI invasiva)",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "RSFI invasiva aguda: neutropênicos, transplantados. RSFI crônica: DM, corticóide. Forma alérgica: atópicos, asma",
                "valor_referencia": None,
                "fonte": "SBI 2023",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Tinea Capitis (Tinha do Couro Cabeludo)",
        "criterios": [
            {
                "nome": "Exame direto com KOH ou calcofluor de cabelo/escama positivo para dermatófitos (endotrix ou ectotrix)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Endotrix (Trichophyton tonsurans): esporos dentro do cabelo. Ectotrix (M. canis): esporos ao redor. Identificação do padrão guia tratamento",
                "valor_referencia": "Hifas/esporos em cabelo",
                "fonte": "SBD 2022; MS-SVS",
                "ordem": 1,
            },
            {
                "nome": "Cultura em Mycosel com identificação de espécie de dermatófito",
                "categoria": "microbiologico",
                "tipo": "maior",
                "descricao": "Crescimento em 1–3 semanas; M. canis (zoonótico), T. tonsurans (antropofílico); identificação correta orienta antifúngico e controle",
                "valor_referencia": "Espécie identificada",
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Alopecia com escamas, crostas e colarete de pelos fraturados em criança em idade escolar",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Placas de alopecia com descamação; 'pontos pretos' (cabelos fraturados = T. tonsurans); querion (reação inflamatória) → alopecia cicatricial",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Tinea Corporis, Cruris e Faciei (Tinha do Corpo)",
        "criterios": [
            {
                "nome": "Exame direto com KOH de escama da borda ativa da lesão positivo para dermatófitos",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "KOH 10–20%: hifas septadas e artroconídios no estrato córneo; coleta na borda ativa (mais infectante)",
                "valor_referencia": "Hifas ao KOH",
                "fonte": "SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Lesão anular eritematosa com bordas ativas vesiculosas/escamosas e clareamento central",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesão em anel (anular) com borda elevada eritematosa e ativa; centro claro/hiperpigmentado; prurido intenso",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Cultura para identificação de espécie (T. rubrum é o mais comum no Brasil)",
                "categoria": "microbiologico",
                "tipo": "suporte",
                "descricao": "T. rubrum (mais prevalente); T. mentagrophytes; M. canis (zoonótico); identificação necessária em casos resistentes",
                "valor_referencia": "Espécie identificada",
                "fonte": "SBD 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Tinea Pedis (Pé de Atleta) e Tinea Unguium (Onicomicose)",
        "criterios": [
            {
                "nome": "Exame direto com KOH de escama subungueal ou raspado interdigital positivo para hifas",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "KOH de raspado subungueal ou interdigital; hifas septadas e artroconídios; coleta de amostra adequada é crucial",
                "valor_referencia": "Hifas ao KOH",
                "fonte": "SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Cultura em Mycosel com identificação de espécie (T. rubrum > 70%, T. mentagrophytes var. interdigitale)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Cultura obrigatória antes de tratar onicomicose com antifúngico sistêmico (confirma etiologia e espécie)",
                "valor_referencia": "Dermatófito identificado",
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Tinea unguium: onicólise distal, hiperqueratose subungueal, espessamento e coloração amarelada/acastanhada da lâmina",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "DLSO (distal lateral subungueal onychomycosis) é o padrão mais comum; superficial branca; proximal subungueal (imunossuprimidos)",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Pitiríase Versicolor (Tinea Versicolor)",
        "criterios": [
            {
                "nome": "Exame direto com KOH de escama das lesões: aspecto de 'macarrão e almôndegas' (hifas curtas + esporos de Malassezia)",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "Padrão patognomônico ao KOH: hifas curtas e esporos esféricos em agrupamentos — 'macarrão com almôndegas'; diagnóstico simples e rápido",
                "valor_referencia": "Hifas curtas + esporos ao KOH",
                "fonte": "SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Máculas hipo ou hiperpigmentadas com fina descamação furfurácea no tronco (especialmente)",
                "categoria": "clinico",
                "tipo": "obrigatorio",
                "descricao": "Lesões múltiplas coalescentes com fina escama 'farinácea'; hipopigmentação (mais visível em negros) ou hiperpigmentação; fluorescência amarelo-esverdeada na lâmpada de Wood",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 2,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Dermatofitose Ungueal e Cutânea por Tricofíton (Tinea Manum e Tinea Barbae)",
        "criterios": [
            {
                "nome": "Exame direto com KOH e cultura para Trichophyton spp. em material de lesão",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "T. rubrum (tinea manum e ungueal) ou T. mentagrophytes e T. verrucosum (tinea barbae zoonótica); cultivo confirma espécie",
                "valor_referencia": "Trichophyton identificado",
                "fonte": "SBD 2022",
                "ordem": 1,
            },
            {
                "nome": "Tinea manum: hiperqueratose difusa palmar unilateral (two feet one hand syndrome) com prurido",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Hiperqueratose palmar unilateral assimétrica é característica de tinea manum (T. rubrum); associada a tinea pedis bilateral",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 2,
            },
            {
                "nome": "Tinea barbae: foliculite e perifoliculite na área da barba/bigode com kerion ou abscessos (zoonótica por gado/cavalo)",
                "categoria": "clinico",
                "tipo": "maior",
                "descricao": "Forma inflamatória grave da área da barba; T. verrucosum (bovino) é principal agente; responde a griseofulvina ou terbinafina sistêmica",
                "valor_referencia": None,
                "fonte": "SBD 2022",
                "ordem": 3,
            },
        ],
        "escores": [],
    },
    {
        "patologia_nome": "Pneumonia por Pneumocystis jirovecii (PCP)",
        "criterios": [
            {
                "nome": "PCR para P. jirovecii em LBA, escarro induzido ou aspirado traqueal positivo",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "PCR em tempo real: sensibilidade > 97%, especificidade > 90%; melhor método atual; resultado positivo mesmo em colonização (interpretar com clínica)",
                "valor_referencia": "PCR P. jirovecii positivo",
                "fonte": "MS/PCDT HIV 2023; SBI 2023",
                "ordem": 1,
            },
            {
                "nome": "Colorações diretas no LBA: Grocott/GMS (cistos em preto), Giemsa (trofozoítos) ou imunofluorescência",
                "categoria": "microbiologico",
                "tipo": "obrigatorio",
                "descricao": "GMS: cistos de 5–8 µm com face em 'pão amassado'; IF direta tem melhor sensibilidade que colorações convencionais",
                "valor_referencia": "Cistos de P. jirovecii identificados",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 2,
            },
            {
                "nome": "TC de tórax com opacidades em vidro fosco bilaterais perihilares (padrão típico)",
                "categoria": "imagem",
                "tipo": "maior",
                "descricao": "Vidro fosco bilateral com distribuição perihilar e preservação subpleural; pneumatoceles em 10–30%; cistos; RX pode ser normal",
                "valor_referencia": "Vidro fosco bilateral perihilar",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 3,
            },
            {
                "nome": "Gradiente alvéolo-arterial de O₂ elevado (P(A-a)O₂ > 35 mmHg) em repouso",
                "categoria": "laboratorial",
                "tipo": "maior",
                "descricao": "Gasometria arterial: hipoxemia com gradiente A-a alargado; LDH sérica > 500 UI/L em > 90% dos casos",
                "valor_referencia": "P(A-a)O₂ > 35 mmHg",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 4,
            },
            {
                "nome": "HIV positivo com CD4 < 200/mm³ (ou < 14%) como contexto de imunodeficiência grave",
                "categoria": "epidemiologico",
                "tipo": "obrigatorio",
                "descricao": "PCP é doença indicadora de AIDS; doença oportunista mais comum em PVHIV sem TARV; profilaxia com SMX-TMP se CD4 < 200",
                "valor_referencia": "CD4 < 200/mm³",
                "fonte": "MS/PCDT HIV 2023",
                "ordem": 5,
            },
        ],
        "escores": [],
    },
]
