"""
Dados de referência: fontes oficiais, bactérias, antibióticos e classes.
"""

FONTES_OFICIAIS = [
    # (sigla, nome, orgao, tipo, url, ano, descricao)
    ("PCDT-TB", "Protocolo Clínico e Diretrizes Terapêuticas da Tuberculose", "Ministério da Saúde", "PCDT", "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/t/tuberculose", 2022, "PCDT Tuberculose MS 2022"),
    ("PCDT-IST", "Protocolo Clínico e Diretrizes Terapêuticas para Atenção Integral às Pessoas com ISTs", "Ministério da Saúde", "PCDT", "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/ist/pcdt-ist-2022.pdf", 2022, "IST: sífilis, gonorreia, clamídia e outras"),
    ("PCDT-HANSENR", "Protocolo Clínico e Diretrizes Terapêuticas da Hanseníase", "Ministério da Saúde", "PCDT", "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/h/hanseniase", 2022, "PCDT Hanseníase MS 2022"),
    ("PCDT-LEPTO", "Guia de Vigilância em Saúde – Leptospirose", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/guia-de-vigilancia-em-saude_4ed.pdf", 2019, "GVS 4ª ed. capítulo Leptospirose"),
    ("PCDT-MENIN", "Nota Técnica CGPNI – Meningites Bacterianas", "Ministério da Saúde / SVS", "Nota Técnica", "https://www.gov.br/saude/pt-br", 2023, "Diretrizes de tratamento das meningites bacterianas"),
    ("ANVISA-IRAS", "Nota Técnica GVIMS/GGTES/ANVISA nº 05/2017 – IRAS e resistência", "ANVISA", "Nota Técnica", "https://www.anvisa.gov.br/servicosaude/manuais/iras.pdf", 2017, "Medidas de prevenção de IRAS e perfil de resistência"),
    ("ANVISA-SCIH", "Medidas de Prevenção de Infecções Hospitalares", "ANVISA", "Nota Técnica", "https://www.anvisa.gov.br", 2023, "Notas técnicas de controle de infecção hospitalar"),
    ("SBI-PNEUM", "Diretrizes Brasileiras para Pneumonia Adquirida na Comunidade", "Sociedade Brasileira de Infectologia / SBPT", "Diretriz", "https://www.infectologia.org.br", 2018, "PAC em adultos imunocompetentes"),
    ("SBI-ITU", "Diretrizes Brasileiras para Infecções do Trato Urinário", "Sociedade Brasileira de Infectologia", "Diretriz", "https://www.infectologia.org.br", 2020, "ITU não complicada, complicada e pielonefrite"),
    ("SBI-SEPSE", "Campanha Sobrevivendo à Sepse – Adaptação BR", "Associação de Medicina Intensiva Brasileira / SBI", "Diretriz", "https://www.infectologia.org.br", 2021, "Sepse e choque séptico"),
    ("SINAN-MS", "Sistema de Informação de Agravos de Notificação", "Ministério da Saúde / SVS", "Boletim", "https://datasus.saude.gov.br/sinan", 2023, "Dados epidemiológicos nacionais"),
    ("GVS-MS", "Guia de Vigilância em Saúde – 5ª edição", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/vigilancia/guia-de-vigilancia-em-saude", 2022, "Referência geral para doenças de notificação compulsória"),
    ("WHONET-BR", "Rede Nacional de Monitoramento de Resistência Microbiana – ANSIRE", "ANVISA", "Boletim", "https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/monitoramento-de-resistencia-microbiana", 2023, "Perfis de resistência isolados no Brasil"),
    ("PCDT-FEBRETIFO", "Guia de Vigilância em Saúde – Febre Tifoide", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br", 2022, "GVS capítulo Febre Tifoide"),
    ("PCDT-COQUELUCHE", "Nota Técnica – Coqueluche", "Ministério da Saúde / SVS", "Nota Técnica", "https://www.gov.br/saude/pt-br", 2023, "Tratamento e controle da coqueluche"),
    ("PCDT-RICKETTSIA", "Guia de Vigilância em Saúde – Rickettsioses", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br", 2022, "GVS capítulo Rickettsioses"),
    ("PCDT-BRUCELOSE", "Guia de Vigilância em Saúde – Brucelose", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br", 2022, "GVS capítulo Brucelose"),
    ("PCDT-COLERA", "Guia de Vigilância em Saúde – Cólera", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br", 2022, "GVS capítulo Cólera"),
    ("PCDT-TETANO", "Guia de Vigilância em Saúde – Tétano", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br", 2022, "GVS capítulo Tétano"),
    ("PCDT-DIFTERIA", "Guia de Vigilância em Saúde – Difteria", "Ministério da Saúde / SVS", "Diretriz", "https://www.gov.br/saude/pt-br", 2022, "GVS capítulo Difteria"),
]

FAMILIAS_BACTERIANAS = [
    # (nome, filo)
    ("Mycobacteriaceae", "Actinobacteria"),
    ("Leptospiraceae", "Spirochaetes"),
    ("Streptococcaceae", "Firmicutes"),
    ("Staphylococcaceae", "Firmicutes"),
    ("Enterobacteriaceae", "Proteobacteria"),
    ("Pseudomonadaceae", "Proteobacteria"),
    ("Neisseriaceae", "Proteobacteria"),
    ("Treponemataceae", "Spirochaetes"),
    ("Clostridiaceae", "Firmicutes"),
    ("Rickettsiaceae", "Proteobacteria"),
    ("Brucellaceae", "Proteobacteria"),
    ("Chlamydiaceae", "Chlamydiae"),
    ("Bordetellaceae", "Proteobacteria"),
    ("Corynebacteriaceae", "Actinobacteria"),
    ("Vibrionaceae", "Proteobacteria"),
    ("Campylobacteraceae", "Proteobacteria"),
    ("Listeriaceae", "Firmicutes"),
    ("Haemophilaceae", "Proteobacteria"),
    ("Bacteroidaceae", "Bacteroidetes"),
    ("Spirochaetaceae", "Spirochaetes"),
    ("Yersiniaceae", "Proteobacteria"),
    ("Bacillaceae", "Firmicutes"),
    ("Mycoplasmataceae", "Tenericutes"),
    ("Burkholderiaceae", "Proteobacteria"),
    ("Acinetobacteraceae", "Proteobacteria"),
    ("Enterococcaceae", "Firmicutes"),
    ("Moraxellaceae", "Proteobacteria"),
    ("Actinomycetaceae", "Actinobacteria"),
    ("Nocardiaceae", "Actinobacteria"),
    ("Bartonellaceae", "Proteobacteria"),
    ("Bordetellaceae", "Proteobacteria"),
    ("Phenazinaceae", "Actinobacteria"),
]

# (nome_cientifico, nome_comum, gram, familia_nome, aerobiose, formato, resistencia_natural, obs)
BACTERIAS = [
    ("Streptococcus pneumoniae", "Pneumococo", "positiva", "Streptococcaceae", "facultativo", "diplococo", "Metronidazol, aminoglicosídeos (intrínsecos)", "Principal causa de pneumonia, meningite e otite na comunidade"),
    ("Streptococcus pyogenes", "Estreptococo do grupo A", "positiva", "Streptococcaceae", "facultativo", "coco", "Nenhuma clinicamente relevante", "Agente da faringite, erisipela, escarlatina, febre reumática"),
    ("Streptococcus agalactiae", "Estreptococo do grupo B (GBS)", "positiva", "Streptococcaceae", "facultativo", "coco", "Nenhuma clinicamente relevante", "Principal causa de sepse neonatal precoce"),
    ("Streptococcus viridans (grupo)", "Estreptococos do grupo viridans", "positiva", "Streptococcaceae", "facultativo", "coco", "Variável", "Importante em endocardite subaguda"),
    ("Staphylococcus aureus", "Estafilococo dourado", "positiva", "Staphylococcaceae", "facultativo", "coco", "MRSA: oxacilina/meticilina", "Causa diversas infecções; MRSA é problema de saúde pública"),
    ("Staphylococcus aureus resistente à meticilina (MRSA)", "MRSA", "positiva", "Staphylococcaceae", "facultativo", "coco", "Betalactâmicos, aminoglicosídeos frequentes", "Resistência mediada por gene mecA"),
    ("Staphylococcus epidermidis", "Estafilococo coagulase-negativo", "positiva", "Staphylococcaceae", "facultativo", "coco", "Frequentemente resistente a oxacilina", "Infecções em próteses e cateteres"),
    ("Enterococcus faecalis", "Enterococo", "positiva", "Enterococcaceae", "facultativo", "coco", "Cefalosporinas, clindamicina", "ITU e endocardite; sensível a ampicilina em geral"),
    ("Enterococcus faecium", "Enterococo resistente", "positiva", "Enterococcaceae", "facultativo", "coco", "Ampicilina frequente; VRE em aumento", "VRE crescente no Brasil"),
    ("Escherichia coli", "E. coli", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Aminopenicilinas (muitas cepas)", "Principal agente de ITU, gastroenterite, sepse"),
    ("Klebsiella pneumoniae", "Klebsiela", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Aminopenicilinas intrínsecas", "ESBL e KPC são problemas críticos no Brasil"),
    ("Klebsiella pneumoniae produtora de carbapenemase (KPC)", "KPC", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Carbapenens, maioria dos betalactâmicos", "Resistência extrema; tratamento com ceftazidima-avibactam"),
    ("Proteus mirabilis", "Proteus", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Polimixinas (intrínseca)", "ITU, especialmente associada a sonda"),
    ("Pseudomonas aeruginosa", "Pseudômonas", "negativa", "Pseudomonadaceae", "aerobio", "bacilo", "Intrínseca a ampicilina, SMX-TMP, cefalosporinas 1ª/2ª", "Patógeno hospitalar crítico; MDR frequente"),
    ("Acinetobacter baumannii", "Acinetobacter", "negativa", "Acinetobacteraceae", "aerobio", "cocobacilo", "Ampla resistência intrínseca e adquirida", "CRAB (resistente a carbapenens) emergente no Brasil"),
    ("Haemophilus influenzae", "Haemófilo", "negativa", "Haemophilaceae", "facultativo", "cocobacilo", "Eritromicina, clindamicina", "Tipo b controlado pela vacina; não tipável em adultos"),
    ("Haemophilus ducreyi", "Agente do cancro mole", "negativa", "Haemophilaceae", "facultativo", "cocobacilo", None, "Ulceração genital; rara no Brasil atualmente"),
    ("Neisseria meningitidis", "Meningococo", "negativa", "Neisseriaceae", "aerobio", "diplococo", "Nenhuma clinicamente relevante até agora", "Sorogrupos B e C predominam no Brasil"),
    ("Neisseria gonorrhoeae", "Gonococo", "negativa", "Neisseriaceae", "aerobio", "diplococo", "Resistência crescente a quinolonas e penicilinas", "Multirresistência crescente; principal IST bacteriana"),
    ("Salmonella Typhi", "Salmonela tífica", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Variável; quinolona-resistente emergindo", "Febre tifoide; transmissão feco-oral"),
    ("Salmonella spp. (não-tíficas)", "Salmonela não-tífica", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Ampicilina em muitas cepas", "Principal causa de salmoneloses no Brasil"),
    ("Shigella spp.", "Shigela", "negativa", "Enterobacteriaceae", "facultativo", "bacilo", "Ampicilina em muitas cepas", "Disenteria bacilar; Shigella sonnei predomina no BR"),
    ("Campylobacter jejuni", "Campilóbacter", "negativa", "Campylobacteraceae", "microaerofilo", "espirilo", "Cefalosporinas de 1ª geração", "Principal causa bacteriana de diarreia aguda no Brasil"),
    ("Vibrio cholerae", "Vibrio da cólera", "negativa", "Vibrionaceae", "facultativo", "bacilo curvo", None, "Cólera: último surto BR 1991-2005; vigilância ativa"),
    ("Helicobacter pylori", "H. pylori", "negativa", "Campylobacteraceae", "microaerofilo", "espirilo", "Metronidazol (30-40% BR)", "Prevalência ~60-70% na população adulta brasileira"),
    ("Yersinia pestis", "Bacilo da peste", "negativa", "Yersiniaceae", "facultativo", "bacilo", None, "Peste bubônica; focos residuais no nordeste BR"),
    ("Treponema pallidum", "Treponema pálido", "indeterminada", "Treponemataceae", "microaerofilo", "espirilo", "Nenhuma documentada", "Sífilis; epidemia crescente no Brasil"),
    ("Borrelia spp.", "Borrelia", "indeterminada", "Spirochaetaceae", "microaerofilo", "espirilo", None, "Febre relapsante e doença de Lyme (B. burgdorferi rara no BR)"),
    ("Leptospira interrogans", "Leptospira", "indeterminada", "Leptospiraceae", "aerobio", "espirilo", None, "Leptospirose; endêmica no Brasil; pico em chuvas"),
    ("Mycobacterium tuberculosis", "Bacilo de Koch (BK)", "nao_aplicavel", "Mycobacteriaceae", "aerobio", "bacilo", "Intrínseca a cefalosporinas, macrólidos", "TB: Brazil está entre os 30 países de alta carga"),
    ("Mycobacterium leprae", "Bacilo de Hansen", "nao_aplicavel", "Mycobacteriaceae", "aerobio", "bacilo", "Intrínseca a maioria dos ATBs convencionais", "Hanseníase; Brasil 2º maior em casos do mundo"),
    ("Rickettsia rickettsii", "Rickettsia das Montanhas Rochosas", "negativa", "Rickettsiaceae", "aerobio", "cocobacilo", "Intrínseca a betalactâmicos, aminoglicosídeos", "Febre maculosa brasileira; alta letalidade sem tratamento"),
    ("Rickettsia spp.", "Rickettsias", "negativa", "Rickettsiaceae", "aerobio", "cocobacilo", "Intrínseca a betalactâmicos, aminoglicosídeos", "Rickettsioses em geral; transmitidas por carrapatos"),
    ("Brucella spp.", "Brucela", "negativa", "Brucellaceae", "aerobio", "cocobacilo", "Cefalosporinas 1ª geração (intrínseca)", "Brucelose; zoonose; bovinos e suínos principais reservatórios"),
    ("Chlamydia trachomatis", "Clamídia", "indeterminada", "Chlamydiaceae", "aerobio", "bacilo intracelular", "Intrínseca a betalactâmicos, aminoglicosídeos", "IST mais prevalente no Brasil; também tracoma ocular"),
    ("Chlamydophila pneumoniae", "Clamídia pneumônica", "indeterminada", "Chlamydiaceae", "aerobio", "bacilo intracelular", "Intrínseca a betalactâmicos, aminoglicosídeos", "Pneumonia atípica; soroprevalência alta no Brasil"),
    ("Mycoplasma pneumoniae", "Micoplasma pneumônico", "indeterminada", "Mycoplasmataceae", "facultativo", "pleomorfico", "Intrínseca a betalactâmicos (sem parede)", "Pneumonia atípica; tosse seca proeminente"),
    ("Bordetella pertussis", "Agente da coqueluche", "negativa", "Bordetellaceae", "aerobio", "cocobacilo", None, "Coqueluche; reemergência no Brasil desde 2011"),
    ("Corynebacterium diphtheriae", "Bacilo diftérico", "positiva", "Corynebacteriaceae", "aerobio", "bacilo", None, "Difteria; controlada pela vacinação no Brasil"),
    ("Clostridium tetani", "Agente do tétano", "positiva", "Clostridiaceae", "anaerobio", "bacilo", "Aminoglicosídeos, quinolonas", "Tétano acidental e neonatal"),
    ("Clostridium perfringens", "Agente da gangrena", "positiva", "Clostridiaceae", "anaerobio", "bacilo", None, "Gangrena gasosa, intoxicação alimentar"),
    ("Clostridioides difficile", "C. diff", "positiva", "Clostridiaceae", "anaerobio", "bacilo", "Metronidazol sistêmico (em desuso)", "Infecção associada a antibioticoterapia; crescente no Brasil"),
    ("Clostridium botulinum", "Agente do botulismo", "positiva", "Clostridiaceae", "anaerobio", "bacilo", None, "Botulismo alimentar, de ferida e infantil"),
    ("Listeria monocytogenes", "Listeria", "positiva", "Listeriaceae", "facultativo", "bacilo", "Cefalosporinas (intrínseca)", "Meningite em imunossuprimidos e neonatos; gestantes"),
    ("Bacteroides fragilis", "Bacteroides", "negativa", "Bacteroidaceae", "anaerobio", "bacilo", "Aminoglicosídeos, quinolonas em muitas cepas", "Infecções intra-abdominais; abscessos"),
    ("Burkholderia pseudomallei", "Agente da melioidose", "negativa", "Burkholderiaceae", "aerobio", "bacilo", "Colistina, aminoglicosídeos (intrínseca)", "Melioidose; rara no Brasil mas emergente no nordeste"),
    ("Actinomyces israelii", "Actinomices", "positiva", "Actinomycetaceae", "facultativo", "bacilo filamentoso", None, "Actinomicose; infecção crônica granulomatosa"),
    ("Nocardia spp.", "Nocardia", "positiva", "Nocardiaceae", "aerobio", "bacilo filamentoso", None, "Nocardiose; imunocomprometidos"),
    ("Bartonella henselae", "Bartonela", "negativa", "Bartonellaceae", "aerobio", "bacilo", None, "Doença da arranhadura do gato; angiomatose bacilar"),
    ("Staphylococcus saprophyticus", "Estafilococo saprófito", "positiva", "Staphylococcaceae", "facultativo", "coco", "Novobiocina (intrínseca)", "ITU em mulheres jovens sexualmente ativas"),
]

CLASSES_ANTIBIOTICOS = [
    # (nome, mecanismo_acao, alvo_celular)
    ("Penicilinas", "Inibição da síntese de parede celular", "Proteínas ligadoras de penicilina (PBPs)"),
    ("Cefalosporinas (1ª geração)", "Inibição da síntese de parede celular", "PBPs"),
    ("Cefalosporinas (2ª geração)", "Inibição da síntese de parede celular", "PBPs"),
    ("Cefalosporinas (3ª geração)", "Inibição da síntese de parede celular", "PBPs"),
    ("Cefalosporinas (4ª geração)", "Inibição da síntese de parede celular", "PBPs"),
    ("Cefalosporinas (5ª geração / anti-MRSA)", "Inibição da síntese de parede celular", "PBP2a"),
    ("Carbapenens", "Inibição da síntese de parede celular", "PBPs – amplo espectro"),
    ("Monobactâmicos", "Inibição da síntese de parede celular", "PBPs gram-negativos"),
    ("Inibidores de betalactamase (combinados)", "Inibição de betalactamases + síntese de parede", "PBPs + betalactamases"),
    ("Glicopeptídeos", "Inibição da síntese de parede celular", "Precursores da parede (D-Ala-D-Ala)"),
    ("Lipoglicopeptídeos", "Inibição da síntese de parede celular + membrana", "D-Ala-D-Ala + membrana"),
    ("Aminoglicosídeos", "Inibição da síntese proteica (30S)", "Subunidade 30S ribossômica"),
    ("Macrólidos", "Inibição da síntese proteica (50S)", "Subunidade 50S ribossômica"),
    ("Azálidos", "Inibição da síntese proteica (50S)", "Subunidade 50S ribossômica"),
    ("Cetólidos", "Inibição da síntese proteica (50S)", "Subunidade 50S ribossômica"),
    ("Lincosamidas", "Inibição da síntese proteica (50S)", "Subunidade 50S ribossômica"),
    ("Tetraciclinas", "Inibição da síntese proteica (30S)", "Subunidade 30S ribossômica"),
    ("Glicilciclinas", "Inibição da síntese proteica (30S)", "Subunidade 30S ribossômica – evasão de efflux"),
    ("Cloranfenicol", "Inibição da síntese proteica (50S)", "Subunidade 50S ribossômica"),
    ("Oxazolidinonas", "Inibição da síntese proteica (50S)", "Subunidade 50S / início da tradução"),
    ("Quinolonas / Fluoroquinolonas", "Inibição da replicação e transcrição do DNA", "DNA girase e topoisomerase IV"),
    ("Sulfonamidas + Diaminopirimidinas", "Inibição da síntese de folato", "Di-hidropteroato sintase + di-hidrofolato redutase"),
    ("Nitroimidazóis", "Dano ao DNA por radicais livres", "DNA bacteriano e protozoário"),
    ("Nitrofuranos", "Dano ao DNA por múltiplos mecanismos", "DNA bacteriano"),
    ("Polimixinas", "Disrupção da membrana externa", "Lipopolissacarídeo (gram-negativos)"),
    ("Rifamicinas", "Inibição da RNA polimerase", "RNA polimerase dependente de DNA"),
    ("Glicilglicinas / Estreptograminas", "Inibição da síntese proteica (50S)", "Subunidade 50S – dois pontos diferentes"),
    ("Lipopeptídeos", "Disrupção da membrana citoplasmática", "Membrana citoplasmática gram-positivos"),
    ("Fosfomicina", "Inibição da síntese de parede celular (fase inicial)", "MurA (UDP-GlcNAc enolpiruvil transferase)"),
    ("Diaminopirimidinas", "Inibição da di-hidrofolato redutase", "DHFR bacteriana"),
    ("Isonicotinato / INH", "Inibição da síntese de ácidos micólicos", "InhA e KatG (Mycobacterium)"),
    ("Pirazinamida", "Inibição da síntese de ácidos graxos (micobactérias)", "FAS I (pirazinoato ativo em pH ácido)"),
    ("Etambutol", "Inibição da síntese de arabinogalactano", "Arabinosil transferase (EmbB)"),
    ("Estreptomicina / Aminoglicosídeos antituberculose", "Inibição da síntese proteica (30S)", "Subunidade 30S – S12 ribossômica"),
    ("Diamino-difenilsulfona (Dapsona)", "Inibição da síntese de folato", "Di-hidropteroato sintase (Mycobacterium leprae)"),
    ("Novas cefalosporinas + inibidores (combo)", "Inibição de parede + betalactamases avançadas", "PBPs + KPC/OXA/NDM"),
]

# (nome_generico, nome_comercial, classe_nome, via, disponivel_sus, anvisa, obs)
ANTIBIOTICOS = [
    # Penicilinas
    ("Penicilina G benzatina", "Benzetacil", "Penicilinas", "im", True, True, "Primeira linha para sífilis, faringite estreptocócica"),
    ("Penicilina G cristalina", "Penicilina G", "Penicilinas", "iv", True, True, "Meningite, endocardite, tétano"),
    ("Penicilina V", "Fenoximetilpenicilina", "Penicilinas", "oral", True, True, "Faringite, infecções leves"),
    ("Ampicilina", "Binotal", "Penicilinas", "oral/iv", True, True, "Listeria, enterococo, H. influenzae sensível"),
    ("Amoxicilina", "Amoxil", "Penicilinas", "oral", True, True, "PAC leve, otite, sinusite, ITU não complicada"),
    ("Amoxicilina-clavulanato", "Clavulin / Augmentin", "Inibidores de betalactamase (combinados)", "oral/iv", True, True, "PAC moderada, ITU, IVAS"),
    ("Ampicilina-sulbactam", "Unasyn", "Inibidores de betalactamase (combinados)", "iv", True, True, "Infecções mistas, Acinetobacter sensível"),
    ("Piperacilina-tazobactam", "Tazocin", "Inibidores de betalactamase (combinados)", "iv", True, True, "Infecções graves hospital; Pseudomonas"),
    ("Oxacilina", "Staficilin", "Penicilinas", "iv", True, True, "Primeira linha para MSSA grave"),
    ("Nafcilina", None, "Penicilinas", "iv", False, False, "Equivalente à oxacilina; indisponível no Brasil"),
    # Cefalosporinas
    ("Cefalexina", "Keflex", "Cefalosporinas (1ª geração)", "oral", True, True, "Infecções cutâneas, ITU não complicada"),
    ("Cefazolina", "Kefazol", "Cefalosporinas (1ª geração)", "iv", True, True, "Profilaxia cirúrgica, infecções por MSSA"),
    ("Cefuroxima", "Zinnat", "Cefalosporinas (2ª geração)", "oral/iv", True, True, "IVAS, PAC leve-moderada"),
    ("Ceftriaxona", "Rocefin", "Cefalosporinas (3ª geração)", "iv/im", True, True, "Meningite, pneumonia, gonorreia, febres entéricas"),
    ("Cefotaxima", "Claforan", "Cefalosporinas (3ª geração)", "iv", True, True, "Meningite, infecções graves"),
    ("Ceftazidima", "Fortaz", "Cefalosporinas (3ª geração)", "iv", True, True, "Pseudomonas; kombinar com avibactam para KPC"),
    ("Cefepima", "Maxcef", "Cefalosporinas (4ª geração)", "iv", True, True, "Pseudomonas, infecções hospitalares"),
    ("Ceftazidima-avibactam", "Avycaz", "Novas cefalosporinas + inibidores (combo)", "iv", False, True, "KPC, OXA-48; principal opção anti-KPC no Brasil"),
    ("Ceftolozano-tazobactam", "Zerbaxa", "Novas cefalosporinas + inibidores (combo)", "iv", False, True, "Pseudomonas MDR"),
    ("Ceftaroline", "Teflaro / Zinforo", "Cefalosporinas (5ª geração / anti-MRSA)", "iv", False, True, "MRSA, PAC grave"),
    # Carbapenens
    ("Meropenem", "Meronem", "Carbapenens", "iv", True, True, "Infecções graves, gram-negativos ESBL"),
    ("Imipenem-cilastatina", "Tienam", "Carbapenens", "iv", True, True, "Infecções polimicrobianas graves"),
    ("Ertapenem", "Invanz", "Carbapenens", "iv/im", True, True, "Infecções comunitárias ESBL; não cobre Pseudomonas"),
    ("Doripenem", "Doribax", "Carbapenens", "iv", False, True, "Pseudomonas; alternativa ao meropenem"),
    # Glicopeptídeos / Lipoglicopeptídeos
    ("Vancomicina", "Vancocin", "Glicopeptídeos", "iv", True, True, "MRSA, C. difficile (oral), enterococo"),
    ("Teicoplanina", "Targocid", "Glicopeptídeos", "iv/im", True, True, "Alternativa à vancomicina; MRSA"),
    ("Dalbavancina", "Xydalba", "Lipoglicopeptídeos", "iv", False, True, "MRSA, dose única semanal"),
    # Aminoglicosídeos
    ("Gentamicina", "Garamicina", "Aminoglicosídeos", "iv/im", True, True, "Combinação em gram-negativos e endocardite"),
    ("Amicacina", "Amikin", "Aminoglicosídeos", "iv/im", True, True, "Gram-negativos MDR; ESBL; TB resistente"),
    ("Tobramicina", "Tobrex", "Aminoglicosídeos", "iv", True, True, "Pseudomonas; infecções hospitalares"),
    ("Estreptomicina", "Estreptomicina", "Estreptomicina / Aminoglicosídeos antituberculose", "im", True, True, "TB; brucelose; peste"),
    # Macrólidos / Azálidos
    ("Azitromicina", "Zitromax", "Azálidos", "oral/iv", True, True, "PAC atípica, clamídia, gonorreia (combo), coqueluche"),
    ("Claritromicina", "Klaricid", "Macrólidos", "oral/iv", True, True, "PAC atípica, H. pylori (combo), MAC"),
    ("Eritromicina", "Eritromicina", "Macrólidos", "oral/iv", True, True, "Alternativa histórica; difteria, coqueluche"),
    # Lincosamidas
    ("Clindamicina", "Dalacin", "Lincosamidas", "oral/iv", True, True, "Infecções anaeróbias, celulite MRSA (oral)"),
    # Tetraciclinas / Glicilciclinas
    ("Doxiciclina", "Vibramicina", "Tetraciclinas", "oral/iv", True, True, "Rickettsia, brucelose, clamídia, febre maculosa"),
    ("Minociclina", "Minociclina", "Tetraciclinas", "oral", False, True, "Acinetobacter sensível; MRSA (oral)"),
    ("Tigeciclina", "Tygacil", "Glicilciclinas", "iv", True, True, "Infecções polimicrobianas; MDR incluindo MRSA e KPC"),
    # Fluoroquinolonas
    ("Ciprofloxacino", "Cipro", "Quinolonas / Fluoroquinolonas", "oral/iv", True, True, "Gram-negativos, ITU, gastrointestinal, Pseudomonas"),
    ("Levofloxacino", "Levaquin", "Quinolonas / Fluoroquinolonas", "oral/iv", True, True, "PAC, ITU, TB resistente (2ª linha)"),
    ("Moxifloxacino", "Avelox", "Quinolonas / Fluoroquinolonas", "oral/iv", True, True, "PAC anaeróbios; TB resistente; sem cobertura para ITU"),
    # Sulfonamidas
    ("Sulfametoxazol-trimetoprima (SMX-TMP)", "Bactrim", "Sulfonamidas + Diaminopirimidinas", "oral/iv", True, True, "ITU, nocardiose, Pneumocystis, toxoplasmose"),
    # Nitroimidazóis
    ("Metronidazol", "Flagyl", "Nitroimidazóis", "oral/iv", True, True, "Anaeróbios, C. difficile, H. pylori, amebíase"),
    ("Tinidazol", "Fasigyn", "Nitroimidazóis", "oral", True, True, "Alternativa ao metronidazol; menor frequência"),
    # Nitrofuranos
    ("Nitrofurantoína", "Macrodantina", "Nitrofuranos", "oral", True, True, "ITU baixa não complicada; não serve para pielonefrite"),
    # Polimixinas
    ("Polimixina B", "Polymyxin B", "Polimixinas", "iv", True, True, "Gram-negativos pan-resistentes; KPC, CRAB"),
    ("Colistina (Polimixina E)", "Colistin", "Polimixinas", "iv/inalatória", True, True, "Gram-negativos pan-resistentes; alternativa ou combo"),
    # Oxazolidinonas
    ("Linezolida", "Zyvox", "Oxazolidinonas", "oral/iv", True, True, "MRSA, VRE, TB MDR/XDR"),
    ("Tedizolida", "Sivextro", "Oxazolidinonas", "oral/iv", False, True, "MRSA; menos mielotoxicidade que linezolida"),
    # Rifamicinas
    ("Rifampicina", "Rifadin", "Rifamicinas", "oral/iv", True, True, "TB (combo), hanseníase, meningite (quimioprofilaxia), S. aureus"),
    # Lipopeptídeos
    ("Daptomicina", "Cubicin", "Lipopeptídeos", "iv", False, True, "MRSA bacteremia, endocardite; VRE"),
    # Fosfomicina
    ("Fosfomicina", "Monurol", "Fosfomicina", "oral/iv", False, True, "ITU não complicada, ESBL; uso crescente"),
    # Tuberculose
    ("Isoniazida (INH)", "Hidrazida", "Isonicotinato / INH", "oral", True, True, "TB – esquema básico RHZE"),
    ("Pirazinamida", "Pirazinamida", "Pirazinamida", "oral", True, True, "TB – fase intensiva"),
    ("Etambutol", "Miambutol", "Etambutol", "oral", True, True, "TB – esquema básico, prevenção resistência"),
    # Hanseníase
    ("Dapsona", "DDS", "Diamino-difenilsulfona (Dapsona)", "oral", True, True, "Hanseníase (combo PQT), dermatoses"),
    ("Clofazimina", "Lamprene", "Cloranfenicol", "oral", True, True, "Hanseníase multibacilar; TB MDR adjuvante; classe Fenazina"),
    ("Ofloxacino", "Floxin", "Quinolonas / Fluoroquinolonas", "oral", True, True, "Hanseníase esquema ROM; UTI bacteriana"),
    ("Cefixima", "Suprax", "Cefalosporinas (3ª geração)", "oral", False, True, "Oral; gonorreia alternativa quando IM não disponível"),
    ("Tetraciclina", "Tetraciclina", "Tetraciclinas", "oral", True, True, "H. pylori terapia quádrupla bismuto (Pylera/PBMT)"),
    # Cloranfenicol
    ("Cloranfenicol", "Cloranfenicol", "Cloranfenicol", "oral/iv", True, True, "Febre maculosa (pediátrico), meningite, rickettsia"),
    # Monobactâmico
    ("Aztreonam", "Azactam", "Monobactâmicos", "iv", False, True, "Gram-negativos; alternativa em alergia a carbapenens"),
    # Vancomicina oral
    ("Fidaxomicina", "Dificid", "Rifamicinas", "oral", False, True, "C. difficile recorrente; superior à vancomicina oral em recorrência"),
]
