"""
Categorias e patologias parasitárias — fontes oficiais brasileiras.
Fontes: PCDT-MS, SVS/GVS 5ª ed. 2022, SBMT, SBI.
"""

CATEGORIAS_PARASITOSES = [
    # (nome, sistema)
    ("Protozooses Sistêmicas",             "Sistêmico / múltiplos órgãos — protozooses"),
    ("Protozooses Intestinais e Urogenitais", "Aparelho digestivo / urogenital — protozooses"),
    ("Helmintoses Intestinais",            "Aparelho digestivo — helmintoses"),
    ("Helmintoses Teciduais e Sistêmicas", "Sistêmico / tecidos — helmintoses"),
    ("Helmintoses Hepatobiliares",         "Fígado / aparelho biliar — helmintoses"),
    ("Ectoparasitoses",                    "Tegumento — ectoparasitoses"),
]

PATOLOGIAS_PARASITOSES = [
    # (nome, cid10, cat_nome, descricao, notif_compulsoria, tipo_notificacao,
    #  prevalencia_br, mortalidade_br, populacao_risco, fonte_sigla)

    # ── Protozooses Sistêmicas ────────────────────────────────
    ("Malária por Plasmodium falciparum",
     "B50", "Protozooses Sistêmicas",
     "Forma de malária mais grave; risco de malária cerebral, anemia grave, insuficiência respiratória, hipoglicemia e insuficiência renal; alta mortalidade sem tratamento rápido; principal causa de morte por malária no Brasil",
     True, "imediata",
     4.8, 0.08,
     "Residentes e viajantes para Amazônia Legal; populações ribeirinhas; garimpeiros; indígenas; militares em zonas endêmicas",
     "PCDT-MALARIA"),

    ("Malária por Plasmodium vivax",
     "B51", "Protozooses Sistêmicas",
     "Forma mais prevalente no Brasil (~84% dos casos); hipnozoítas hepáticos causam recidivas meses após a infecção inicial; ocasionalmente grave em gestantes, crianças e imunossuprimidos; síndrome de malária grave por P. vivax documentada na Amazônia",
     True, "imediata",
     12.5, 0.02,
     "Amazônia Legal (AM, PA, RR, AC, RO, AP, TO, MA, MT); garimpeiros; indígenas; viajantes para a região",
     "PCDT-MALARIA"),

    ("Malária por Plasmodium malariae",
     "B52", "Protozooses Sistêmicas",
     "Forma mais rara; parasitemia baixa e persistente por anos; síndrome nefrótica crônica (malária quartã nefrótica) em crianças com infecção de longa duração; não forma hipnozoítas — sem recidiva verdadeira",
     True, "imediata",
     0.3, 0.005,
     "Amazônia Legal; focos residuais em estados não-amazônicos; adultos com malária de longa data",
     "PCDT-MALARIA"),

    ("Leishmaniose Tegumentar Americana (LTA)",
     "B55.1", "Protozooses Sistêmicas",
     "Amplo espectro clínico: cutânea localizada (úlcera típica com bordas infiltradas), cutânea difusa (múltiplas lesões, anérgica) e mucosa (destruição mucosa nasal, palato, faringe); 30.000 casos/ano no Brasil; disfiguramento facial nas formas mucosas",
     True, "semanal",
     30.0, 0.05,
     "Trabalhadores rurais, extrativistas, indígenas, ecótonos floresta-urbano; Norte, Nordeste, CO, MG, ES, RJ, SP",
     "PCDT-LEISH-TEG"),

    ("Leishmaniose Visceral (Calazar)",
     "B55.0", "Protozooses Sistêmicas",
     "Febre prolongada, esplenomegalia maciça, hepatomegalia, perda de peso, pancitopenia, hipoalbuminemia; mortalidade 5-10% tratada, >90% sem tratamento; urbanização crescente no Brasil; 3.500 casos/ano; impacto maior em crianças < 5 anos",
     True, "imediata",
     3.5, 0.5,
     "Crianças < 5 anos, desnutridos, imunossuprimidos (HIV), idosos; áreas periurbanas no NE, Norte, CO; expansão para centros urbanos (SP, MG, MS, MS)",
     "PCDT-LEISH-VIS"),

    ("Doença de Chagas Aguda",
     "B57.0", "Protozooses Sistêmicas",
     "Febre prolongada, mal-estar, mialgias, sinal de Romaña (edema bipalpebral indolor), chagoma de inoculação; miocardite aguda (10%) e meningoencefalite (<5%) nas formas graves; surtos por transmissão oral (açaí, caldo de cana) crescentes no Norte do Brasil",
     True, "imediata",
     0.8, 0.1,
     "Crianças e adultos em áreas de triatomíneos; consumidores de alimentos contaminados (açaí, cana); trabalhadores rurais do Norte e NE; familiares de pacientes agudos",
     "PCDT-CHAGAS"),

    ("Doença de Chagas Crônica",
     "B57.2", "Protozooses Sistêmicas",
     "Forma indeterminada (assintomática, ~60%), cardíaca (cardiomiopatia chagásica — principal causa de ICC não-isquêmica no Brasil), digestiva (mega-esôfago, megacólon) ou mista; 2-3 milhões de infectados no Brasil; progressão para cardiopatia em ~30% ao longo da vida",
     True, "semanal",
     2500.0, 5.0,
     "Adultos de meia-idade procedentes de áreas endêmicas (NE, MG, GO, BA, PI); receptores de transfusão ou órgãos; transplantados",
     "PCDT-CHAGAS"),

    ("Toxoplasmose em Imunocompetentes",
     "B58.9", "Protozooses Sistêmicas",
     "Geralmente assintomática (80-90%) ou síndrome mononucleose-like com linfadenomegalia cervical e occipital; formas oculares (coriorretinite) podem ocorrer; soroprevalência 60-80% na população adulta brasileira — uma das mais altas do mundo",
     False, None,
     60000.0, 0.1,
     "Adultos jovens com contato com gatos; ingestão de carne crua ou malcozida; horticultores; gestantes soronegativas (risco congênita); Sul do Brasil (toxoplasmose ocular mais frequente)",
     "SBI-PARASIT"),

    ("Toxoplasmose em Imunocomprometidos (HIV/AIDS)",
     "B58.2", "Protozooses Sistêmicas",
     "Encefalite toxoplásmica: principal causa de lesão focal cerebral em HIV/AIDS com CD4 < 100 células/mm³; abcessos cerebrais múltiplos; febre, cefaleia, déficits focais, convulsões, rebaixamento de consciência; alta mortalidade sem tratamento imediato",
     True, "semanal",
     8.0, 1.5,
     "PVHIV com CD4 < 100 células/mm³ não recebendo profilaxia com SMX-TMP; soropositivos para T. gondii; transplantados de órgãos sólidos",
     "PCDT-TOXO"),

    ("Toxoplasmose Congênita",
     "P37.1", "Protozooses Sistêmicas",
     "Sequelas neurológicas e oculares em neonatos de mães com primoinfecção durante a gestação: coriorretinite, calcificações intracranianas, hidrocefalia, microcefalia, convulsões; triagem neonatal obrigatória em vários estados brasileiros (teste do olhinho e sorologia)",
     True, "semanal",
     3.0, 0.2,
     "Neonatos de mães com primoinfecção na gestação; maior risco de transmissão no 3º trimestre (60-80%) mas sequelas mais graves no 1º (90% dos infectados com sequelas)",
     "PCDT-TOXO"),

    # ── Protozooses Intestinais e Urogenitais ─────────────────
    ("Amebíase Intestinal",
     "A06.0", "Protozooses Intestinais e Urogenitais",
     "Colite amebiana: diarreia com muco e sangue (disenteria amebiana), cólicas, tenesmo; colite fulminante e perfuração intestinal nas formas graves; causada exclusivamente por E. histolytica (patogênica) — E. dispar morfologicamente idêntica mas não invasiva",
     True, "semanal",
     10000.0, 0.5,
     "Regiões com saneamento precário (Norte, NE); imigrantes; homens que fazem sexo com homens (amebíase invasiva); crianças de creches; desnutridos",
     "SVS-PARASIT"),

    ("Abscesso Hepático Amebiano",
     "A06.4", "Protozooses Intestinais e Urogenitais",
     "Complicação mais comum da amebíase extraintestinal; febre alta, dor no HD, hepatomegalia; único abscesso em 80% dos casos; imagem em 'soco' à TC; mortalidade 1-3% tratado, > 20% se roto; precedido por colite em apenas 10-15% dos casos",
     True, "semanal",
     500.0, 0.5,
     "Homens adultos (razão 9:1 em relação às mulheres); etilistas; uso de corticoides; imunossuprimidos; procedentes de áreas endêmicas",
     "SVS-PARASIT"),

    ("Giardíase",
     "A07.1", "Protozooses Intestinais e Urogenitais",
     "Diarreia crônica de mau cheiro, flatulência, distensão abdominal, má absorção de gorduras e vitaminas; assintomática em 50%; fonte d'água contaminada e creches são importantes; síndrome de má absorção prolongada em crianças (déficit de crescimento)",
     True, "semanal",
     15000.0, 0.05,
     "Crianças em creches e escolares; viajantes (diarreia do viajante por Giardia); imunodeficientes (IgA secretora deficiente); comunidades com água não filtrada",
     "SVS-PARASIT"),

    ("Tricomoníase",
     "A59.0", "Protozooses Intestinais e Urogenitais",
     "IST não-viral mais comum globalmente; vaginite (corrimento amarelo-esverdeado, odor fétido, prurido vulvovaginal), cervicite, uretrite masculina; associada a parto prematuro, baixo peso ao nascer e maior susceptibilidade ao HIV; assintomática em 50-80% dos homens",
     True, "semanal",
     500000.0, 0.01,
     "Mulheres em idade reprodutiva com parceiros múltiplos; sem uso de preservativo; coinfeção com gonorreia e clamídia; adolescentes",
     "SVS-PARASIT"),

    ("Criptosporidiose",
     "A07.2", "Protozooses Intestinais e Urogenitais",
     "Diarreia aquosa profusa autolimitada em imunocompetentes (7-14 dias); diarreia crônica debilitante com até 10 L/dia em AIDS (CD4 < 100) e transplantados; transmissão hídrica importante (resistente ao cloro e ozônio); surtos em piscinas públicas",
     True, "semanal",
     2000.0, 0.3,
     "Crianças < 5 anos; PVHIV com CD4 < 200; praticantes de natação em piscinas; surtos hídricos; creches; crianças desnutridas",
     "SVS-PARASIT"),

    # ── Helmintoses Intestinais ───────────────────────────────
    ("Ascaridíase",
     "B77.9", "Helmintoses Intestinais",
     "Helmintose mais prevalente no Brasil; dor abdominal, distensão, obstrução intestinal e biliar (complicações em cargas altas); síndrome de Löeffler (febre, tosse, infiltrado pulmonar) na fase larvária; causa importante de desnutrição e comprometimento cognitivo em crianças",
     False, None,
     40000.0, 0.1,
     "Crianças 2-10 anos em áreas de saneamento precário; Norte e Nordeste do Brasil; regiões rurais e periurbanas",
     "SVS-PARASIT"),

    ("Ancilostomíase / Necatoríase (Hookworm)",
     "B76.9", "Helmintoses Intestinais",
     "Anemia ferropriva crônica por perda sanguínea intestinal diária (0,03-0,15 mL/verme/dia); dermatite de penetração (prurido do solo) na fase larvária; síndrome de Löeffler pulmonar; principal causa de anemia helmíntica no Brasil; eosinofilia moderada",
     False, None,
     25000.0, 0.05,
     "Crianças e adultos rurais; trabalhadores agrícolas; solos úmidos, sombreados e arenosos; Norte, NE, CO e SE rural",
     "SVS-PARASIT"),

    ("Tricuríase",
     "B79", "Helmintoses Intestinais",
     "Disenteria tricurina em infecções intensas; prolapso retal em crianças com alta carga parasitária; dor abdominal crônica, tenesmo; coinfecção frequente com A. lumbricoides; eosinofilia moderada; geralmente assintomática em cargas leves",
     False, None,
     20000.0, 0.02,
     "Crianças em áreas de saneamento precário; solo úmido e sombreado; Norte e Nordeste; geofagia como fator de risco",
     "SVS-PARASIT"),

    ("Estrongiloidíase",
     "B78.9", "Helmintoses Intestinais",
     "Autoinfecção endógena permite persistência por décadas; dor abdominal, diarreia intermitente, urticária linear migratória (larva currens); hiperinfecção fatal em imunossuprimidos; 'síndrome de hiperinfecção': larvas disseminadas, sepse gram-negativa, meningite",
     False, None,
     5000.0, 0.5,
     "Adultos procedentes de áreas endêmicas; uso de corticoides ou imunossupressores; PVHIV; transplantados; pacientes oncológicos; infectados pelo HTLV-1",
     "SVS-PARASIT"),

    ("Estrongiloidíase com Síndrome de Hiperinfecção",
     "B78.0", "Helmintoses Intestinais",
     "Complicação grave da estrongiloidíase em imunocomprometidos: larvas migram em grande número para pulmões, SNC e outros órgãos arrastando bactérias intestinais; sepse por gram-negativos, meningite bacteriana, pneumonia hemorrágica; mortalidade > 80% sem diagnóstico precoce",
     True, "imediata",
     200.0, 3.0,
     "PVHIV avançados; corticoterapia em doses altas; transplantados; HTLV-1 coinfectado; leucemia/linfoma; malignidade hematológica",
     "SVS-PARASIT"),

    ("Enterobíase (Oxiuríase)",
     "B80", "Helmintoses Intestinais",
     "Prurido anal noturno intenso por migração das fêmeas para a margem anal para postura de ovos; escoriações, vulvovaginite em meninas; insônia por prurido; reinfecção intra-familiar frequente; diagnóstico pela fita-adesiva anal (Scotch test)",
     False, None,
     30000.0, 0.0,
     "Crianças 5-14 anos em creches, escolas e orfanatos; infecção familiar; toda faixa socioeconômica; coletividades",
     "SVS-PARASIT"),

    ("Teníase",
     "B68.9", "Helmintoses Intestinais",
     "Segmentos proglótes móveis nas fezes e na roupa íntima; dor abdominal leve, perda de peso, náusea; geralmente assintomática; risco de cisticercose autógena por T. solium (ingestão acidental de ovos); vigilância epidemiológica prioritária pelo risco de NCC",
     True, "semanal",
     8000.0, 0.1,
     "Adultos consumidores de carne bovina (T. saginata) ou suína (T. solium) crua ou malcozida; regiões com suinocultura sem inspeção; Norte, NE, MG, GO, SP",
     "SVS-PARASIT"),

    # ── Helmintoses Teciduais e Sistêmicas ────────────────────
    ("Neurocisticercose",
     "B69.0", "Helmintoses Teciduais e Sistêmicas",
     "Principal causa de epilepsia adquirida no Brasil e América Latina; cistos de T. solium no parênquima cerebral, subaracnóideo, ventricular ou medular; epilepsia (75% dos casos), cefaleia, hidrocefalia, hipertensão intracraniana; diagnóstico por TC/RNM + sorologia (ELISA/Western blot)",
     True, "semanal",
     15000.0, 2.0,
     "Adultos 20-50 anos; regiões com suinocultura precária; saneamento deficiente; MG, SP, PR, GO, BA, PE; vegetarianos em zonas endêmicas (ovos pelo ambiente)",
     "PCDT-NCC"),

    ("Esquistossomose Mansoni",
     "B65.1", "Helmintoses Teciduais e Sistêmicas",
     "Única espécie do Brasil (S. mansoni); fase aguda (febre de Katayama); forma intestinal (diarreia, hepatite periportal) e hepatoesplênica (hipertensão porta, esplenomegalia gigante, varizes de esôfago, ascite); 2-4 milhões de infectados no Brasil; endêmica em 19 estados",
     True, "semanal",
     3000.0, 0.8,
     "Populações de zonas endêmicas no NE (BA, PE, AL, SE, PB, RN, CE) e MG; contato com águas contaminadas por Biomphalaria spp.; pescadores, lavadeiras, agricultores, banhistas",
     "PCDT-ESQUIS"),

    ("Filariose Linfática (Bancroftose)",
     "B74.0", "Helmintoses Teciduais e Sistêmicas",
     "Única espécie de filariose linfática endêmica no Brasil (W. bancrofti); elefantíase dos membros inferiores e escroto, hidrocele, quilúria; fase assintomática: microfilaremia; programa de eliminação MS com MDA (DEC+albendazol) — prevalência em queda",
     True, "semanal",
     500.0, 0.1,
     "Populações de baixa renda em áreas endêmicas: Grande Recife (PE) e Grande Maceió (AL); transmissão por Culex quinquefasciatus noturno",
     "PCDT-FILARIA"),

    ("Toxocaríase (Larva Migrans Visceral)",
     "B83.0", "Helmintoses Teciduais e Sistêmicas",
     "Síndrome de larva migrans visceral: febre prolongada, hepatomegalia, pneumonite eosinofílica, eosinofilia intensa (> 3.000/mm³); comprometimento ocular (larva migrans ocular — granuloma, descolamento de retina, cegueira unilateral); neurológico (eosinofílica cerebral rara)",
     False, None,
     3000.0, 0.2,
     "Crianças 1-5 anos com pica/geofagia; contato frequente com fezes de cães e gatos; alta densidade canina sem vermifugação",
     "SVS-PARASIT"),

    ("Larva Migrans Cutânea",
     "B76.9", "Helmintoses Teciduais e Sistêmicas",
     "Dermatite serpiginosa pruriginosa intensa por larvas de A. braziliense na epiderme; lesão avança 1-2 cm/dia; eritema serpiginoso com prurido intenso; autoregressão em semanas; comum em praias, caixas de areia e playgrounds contaminados por fezes de cão/gato",
     False, None,
     20000.0, 0.0,
     "Frequentadores de praias e parques com areia; crianças; regiões costeiras (SE e Sul); verão; jardineiros; trabalhadores de construção",
     "SVS-PARASIT"),

    ("Hidatidose / Equinococose Cística",
     "B67.9", "Helmintoses Teciduais e Sistêmicas",
     "Cisto hidático hepático (60-70%), pulmonar (20-30%) e outros órgãos; crescimento lento e oligossintomático por anos; ruptura do cisto pode causar reação anafilática grave e disseminação; diagnóstico por imagem (US/TC) + sorologia; endêmica no Sul do Brasil (RS, SC, PR) ligada à pecuária ovina",
     True, "semanal",
     500.0, 0.5,
     "Comunidades rurais com pecuária ovina e caninocultura no RS, SC, PR; pastores; criadores de ovelhas; filhos de criadores",
     "SVS-PARASIT"),

    ("Oncocercose",
     "B73", "Helmintoses Teciduais e Sistêmicas",
     "Cegueira dos rios; oncodermatite pruriginosa, nódulos subcutâneos (oncocercomas), despigmentação (pele leopardo/lagarto); lesão ocular progressiva (ceratite, coriorretinite, cegueira) por microfilárias mortas; foco endêmico Yanomami (RR/AM); programa de eliminação próximo ao sucesso",
     True, "semanal",
     30.0, 0.05,
     "Comunidades Yanomami em RR e AM próximas a rios com corredeiras (Simulium spp.); distribuição geográfica restrita no Brasil",
     "SVS-PARASIT"),

    # ── Helmintoses Hepatobiliares ────────────────────────────
    ("Fasciolíase",
     "B66.3", "Helmintoses Hepatobiliares",
     "Colangite e obstrução biliar por Fasciola hepatica; fase aguda (hepatite parasitária): febre, dor no HD, eosinofilia intensa; fase crônica: colestase, colelitíase, obstrução biliar, colangite bacteriana secundária; transmissão por vegetais aquáticos crus (agrião)",
     True, "semanal",
     300.0, 0.1,
     "Consumidores de vegetais aquáticos crus (agrião, alface-d'água); pastores em zonas úmidas; RS, SC, MG, SP, Nordeste úmido; focos rurais bovinos",
     "SVS-PARASIT"),

    # ── Ectoparasitoses ───────────────────────────────────────
    ("Pediculose do Couro Cabeludo",
     "B85.0", "Ectoparasitoses",
     "Infestação pelo Pediculus humanus capitis; prurido intenso no couro cabeludo, nuca e atrás das orelhas; escoriações, impetigo secundário (infecção bacteriana por Staphylococcus aureus e Streptococcus); transmissão por contato cabeça a cabeça; muito prevalente em escolares",
     False, None,
     500000.0, 0.0,
     "Crianças 3-12 anos em idade escolar; creches e escolas; transmissão por contato cabeça a cabeça; toda faixa socioeconômica; cabelos compridos",
     "SVS-PARASIT"),

    ("Escabiose (Sarna)",
     "B86", "Ectoparasitoses",
     "Sarna por Sarcoptes scabiei; prurido noturno intenso generalizado (exceto face em adultos), pápulas e vesículas nos espaços interdigitais, pulsos, genitais, aréolas; transmissão por contato íntimo pele-a-pele; epidemias em famílias e comunidades fechadas; sarna crostosa (norueguesa) em imunossuprimidos com > 1 milhão de ácaros",
     False, None,
     200000.0, 0.0,
     "Crianças; contactantes domiciliares; comunidades fechadas (presídios, abrigos, asilos, hospitais); imunossuprimidos (risco de sarna crostosa transmissível)",
     "SVS-PARASIT"),

    ("Miiase",
     "B87.9", "Ectoparasitoses",
     "Infestação por larvas de Cochliomyia hominivorax (bicheira) em feridas, cavidades e mucosas; destruição tecidual progressiva; odor fétido; tratamento mecânico de remoção das larvas + tampão oclusivo; frequente em feridas crônicas de idosos e pessoas vulneráveis; problema de saúde pública e veterinária",
     False, None,
     5000.0, 0.1,
     "Idosos, pessoas em situação de rua, pacientes acamados com feridas expostas; crianças com feridas não tratadas; regiões rurais e periurbanas; áreas com alta densidade de moscas",
     "SVS-PARASIT"),
]
